/**
 * Sprite domain: early bosses (BSS-001..015). Owns `boss_` ids in this range.
 *
 * GDD refs: 18.3 / R-VIS-002 (distinct silhouette before palette is considered; a veteran
 *           reads the threat and its intent at a glance), R-ART-004 / R-DPT-005
 *           (grayscale-legible), 15.3 / R-BSS-004 (a boss must *draw* what it is about to
 *           do), Appendix E (the Core fight line quoted above each boss in content/bosses).
 *
 * The problem here is not "make fifteen enemies bigger". These sprites are baked at roughly
 * four times enemy scale — the renderer overrides `scale` from each boss's collision radius,
 * 1.3 through 2.3 — so every flaw is four times as visible and, worse, every *similarity* is
 * four times as obvious. Fifteen large grey shapes in a row is the failure mode. And four of
 * them are not creatures at all: The Open Plan is a floor, Legacy System is a machine, The
 * Boardroom is furniture, Quarter End is a date. They still have to fight you.
 *
 * So each boss is placed on four axes, and no two bosses share more than two values:
 *
 *   MASS CLASS      humanoid / machine / architecture / abstraction. Four classes, and the
 *                   class is readable from the outline alone: creatures have a head above
 *                   shoulders, machines are boxes with vents, architecture spans the full
 *                   grid edge-to-edge, abstractions are top-heavy and have no feet.
 *   WHERE THE MASS  above the head (a ring, a wheel), at the chest (a clock, a binder),
 *                   at the floor (a rampart, a table), or behind the body (a rack).
 *   THE ONE FEATURE a crown, aura, ring, extra arms, extra heads, a lit spine — something
 *                   no ordinary enemy in ENM-001..058 has. Never a scaled-up enemy.
 *   FIGHT TELEGRAPH the outline states the pattern set. Radial and spiral bosses are built
 *                   round a centre; summoners have open hands or open ports; the hydra shows
 *                   its three heads; chargers lean forward over a heavy leading edge; the
 *                   two wall bosses are literally walls and have no legs to chase with.
 *
 *   team_lead                wide-armed figure under a floating ring; open hands at both ends
 *   copy_chief               a copier with a torso growing out of its lid, sheets fanned off one side
 *   scrum_master             thin figure holding a note-covered wheel overhead
 *   the_open_plan            a floor plan standing up — pods and beams around one lit spine
 *   sysadmin                 a body welded into a server rack, a monitor for a head, beam out one side
 *   helpdesk_hydra           three headset heads on coiled cord necks over one shared desk
 *   legacy_system            a stepped mainframe, two tape reels, vents radiating from a cracked core
 *   firewall                 a brick rampart; no head, no legs, shuttered ports, flame along the top
 *   the_bottleneck           an hourglass of crates pinching to a jammed neck, leaning forward
 *   shift_manager            a punch clock for a chest, one arm raised with a whistle, rota down one side
 *   supply_chain             a segmented conveyor loop of crates; a chain with no head
 *   quarter_end              a top-heavy calendar wedge on a thin pillar of days, one sweeping hand
 *   vp_of_everything         a suit with four arms, each holding a different department's tool
 *   chief_operating_officer  broad suit behind a floor-plan table; a T-square arm, a searchlight eye
 *   the_boardroom            an oval table ringed with chair-heads; no body at all
 *
 * Grids are 24x24 — one and a half times the enemy grid, which buys the internal detail a boss
 * needs without pretending to be a portrait. Two frames each, and a boss idle is never a walk
 * cycle: it breathes, looms, or its light moves. `scale: 4` is a fallback only.
 */

const SCALE = 4;

const boss = (slug, silhouette, frames, anchor = [0.5, 0.9]) => ({
  id: `boss_${slug}`,
  anchor,
  scale: SCALE,
  silhouette,
  frames,
});

const early = [
  // BSS-001 The Team Lead — SUMMON_ADDS / BUFF_ADDS / RADIAL_BURST, radius 1.3. The first boss
  // in the game, so it must be the most legible: both arms thrown wide with open hands (the
  // adds arrive from there), a buzzword ring hovering free of the head (the buff), and a body
  // built symmetrically around a centre badge (the radial burst leaves from the middle).
  boss('team_lead', 'Wide-armed figure under a floating ring, open hands at both ends of the span.', [[
    '.....kkkkkkkkkkkkkk.....',
    '....kqqqqAAAAAAAAAAk....',
    '....kkkkkk....kkkkkk....',
    '........kkkkkkkk........',
    '.......kSSSSSSSSk.......',
    '.......kSnnnnnnSk.......',
    '.......kSSkwwkSSk.......',
    '........kkSSSSkk........',
    '.........kwwwwk.........',
    '......kkGGGGGGGGkk......',
    '.kkkkkkkGGGGGGGGkkkkkkk.',
    '.kSSSkGGGGGGGGGGGGkSSSk.',
    '.kkkkkGGGGGGGGGGGGkkkkk.',
    '.....kGGGGGGGGGGGGk.....',
    '.....kGGkwwwwwwkGGk.....',
    '.....kGGkwAAAAwkGGk.....',
    '.....kGGkwwwwwwkGGk.....',
    '.....kGGGGGGGGGGGGk.....',
    '......kggggggggggk......',
    '......kggg....gggk......',
    '......kgg......ggk......',
    '......kkk......kkk......',
    '......KKK......KKK......',
    '........................',
  ], [
    '.....kkkkkkkkkkkkkk.....',
    '....kaaaaaqqqqaaaaak....',
    '....kkkkkk....kkkkkk....',
    '........kkkkkkkk........',
    '.......kSSSSSSSSk.......',
    '.......kSnnnnnnSk.......',
    '.......kSSkHHkSSk.......',
    '........kkSSSSkk........',
    '.........kwwwwk.........',
    '......kkGGGGGGGGkk......',
    '.kkkkkkkGGGGGGGGkkkkkkk.',
    '.kSSSkGGGGGGGGGGGGkSSSk.',
    '.kkkkkGGGGGGGGGGGGkkkkk.',
    '.....kGGGGGGGGGGGGk.....',
    '.....kGGkwwwwwwkGGk.....',
    '.....kGGkwqqqqwkGGk.....',
    '.....kGGkwwwwwwkGGk.....',
    '.....kGGGGGGGGGGGGk.....',
    '......kggggggggggk......',
    '......kggg....gggk......',
    '......kgg......ggk......',
    '......kkk......kkk......',
    '......KKK......KKK......',
    '........................',
  ]]),

  // BSS-002 Copy Chief — FAN_SWEEP / SHEET_WAVE / TONER_BURST, radius 2.0. Half machine: the
  // wide flat glass bed is where the sheet waves come from, and the output tray jutting off the
  // right edge is the fan sweep's origin — the only asymmetry in the shape, deliberately so.
  boss('copy_chief', 'A copier the size of a desk with a torso growing out of its lid, sheets fanned off one side.', [[
    '.........kkkkk..........',
    '........kSSSSSk.........',
    '........kSnnnSk.........',
    '........kkSSSkk.........',
    '.........kwwwk..........',
    '......kkkGGGGGkkk.......',
    '.....kGGGGGGGGGGGk......',
    '.....kGGkwwwwwkGGk......',
    '..kkkkkkkkkkkkkkkkkk....',
    '..kHHHHHHHHHHHHHHHHk....',
    '..kHkwwwwwwwwwwwwkHk....',
    '..kHkwWWWWWWWWWWwkHk....',
    '..kHkwwwwwwwwwwwwkHk....',
    '..kHHHHHHHHHHHHHHHHk....',
    '..kGGGGGGGGGGGGGGGGkkkk.',
    '..kGGkwwwwwwwwkGGGkwwwk.',
    '..kGGkwwwwwwwwkGGGkwwwwk',
    '..kGGGGGGGGGGGGGGGGkwwwk',
    '..kGGGGGGGGGGGGGGGGkkkk.',
    '..kgggggggggggggggk.....',
    '..kkkkkkkkkkkkkkkkk.....',
    '...kkk........kkk.......',
    '...KKK........KKK.......',
    '..KKKKKKKKKKKKKKKKK.....',
  ], [
    '.........kkkkk..........',
    '........kSSSSSk.........',
    '........kSnnnSk.........',
    '........kkSSSkk.........',
    '.........kwwwk..........',
    '......kkkGGGGGkkk.......',
    '.....kGGGGGGGGGGGk......',
    '.....kGGkwwwwwkGGk......',
    '..kkkkkkkkkkkkkkkkkk....',
    '..kHHHHHHHHHHHHHHHHk....',
    '..kHkwWWWWWWWWWWWWkHk...',
    '..kHkwwwwwwwwwwwwkHk....',
    '..kHkwwwwwwwwwwwwkHk....',
    '..kHHHHHHHHHHHHHHHHk....',
    '..kGGGGGGGGGGGGGGGGkkkk.',
    '..kGGkwwwwwwwwkGGGkwwww.',
    '..kGGkwwwwwwwwkGGGkwwwwk',
    '..kGGGGGGGGGGGGGGGGkwwwk',
    '..kGGGGGGGGGGGGGGGGkkkk.',
    '..kgggggggggggggggk.....',
    '..kkkkkkkkkkkkkkkkk.....',
    '...kkk........kkk.......',
    '...KKK........KKK.......',
    '..KKKKKKKKKKKKKKKKK.....',
  ]]),

  // BSS-003 Scrum Master — ZONE_CONTROL / TARGETED_SLAM / CONTACT_CHARGE, radius 1.3. The wheel
  // held overhead IS the zone-control ring, and it is what comes down in the slam: all the mass
  // is above the head, on the narrowest body in the roster, so the wind-up is unmissable.
  boss('scrum_master', 'A thin figure holding a note-covered wheel overhead; all the mass above the head.', [[
    '.......kkkkkkkkkk.......',
    '.....kkwwyywwppwwkk.....',
    '....kwwkkkkkkkkkkwwk....',
    '....kwwk........kwwk....',
    '....kwwkkkkkkkkkkwwk....',
    '.....kkwwEEwwyywwkk.....',
    '.......kkkkkkkkkk.......',
    '........kk......kk......',
    '.......kSSk....kSSk.....',
    '.......kSSkkkkkkSSk.....',
    '.........kkkkkk.........',
    '........kSSSSSSk........',
    '........kSkwwkSk........',
    '.........kSSSSk.........',
    '..........kwwk..........',
    '.......kkGGGGGGkk.......',
    '......kGGGGGGGGGGk......',
    '......kGGkEEEEkGGk......',
    '......kGGkEEkkkGGk......',
    '......kGGGGGGGGGGk......',
    '.......kgggggggk........',
    '.......kgg..ggk.........',
    '.......kk....kk.........',
    '.......KK....KK.........',
  ], [
    '.......kkkkkkkkkk.......',
    '.....kkwwppwwyywwkk.....',
    '....kwwkkkkkkkkkkwwk....',
    '....kwwk........kwwk....',
    '....kwwkkkkkkkkkkwwk....',
    '.....kkwwyywwEEwwkk.....',
    '.......kkkkkkkkkk.......',
    '........kk......kk......',
    '.......kSSk....kSSk.....',
    '.......kSSkkkkkkSSk.....',
    '.........kkkkkk.........',
    '........kSSSSSSk........',
    '........kSkHHkSk........',
    '.........kSSSSk.........',
    '..........kwwk..........',
    '.......kkGGGGGGkk.......',
    '......kGGGGGGGGGGk......',
    '......kGGkEEkkkGGk......',
    '......kGGkEEEEkGGk......',
    '......kGGGGGGGGGGk......',
    '.......kgggggggk........',
    '.......kgg..ggk.........',
    '.......kk....kk.........',
    '.......KK....KK.........',
  ]]),

  // BSS-004 The Open Plan — SWEEPING_WALL / RADIAL_BURST / WEAK_POINT_EXPOSE / SPIRAL_STREAM,
  // radius 1.8. Not a creature: a floor. It spans the grid edge to edge with nothing above it
  // and no feet, the partition beams are the sweeping walls, and the lit spine down the middle
  // is both the radial/spiral origin and the drawn weak point R-BSS-004 demands.
  boss('the_open_plan', 'A floor plan standing up: desk pods and partition beams around one lit central spine.', [[
    '........................',
    '........................',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'kHHHHHHHHHHHHHHHHHHHHHHk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkk..kkkk..kkkk..kkkk.',
    '.kGGk..kGGk..kGGk..kGGk.',
    '.kwwk..kwwk..kwwk..kwwk.',
    '.kkkk..kkkk..kkkk..kkkk.',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'kHHHHHHHkkYYkkHHHHHHHHHk',
    'kkkkkkkkkYYYYkkkkkkkkkkk',
    '.kkkk..kkkkYYkkkk..kkkk.',
    '.kGGk..kGGkYYkGGk..kGGk.',
    '.kwwk..kwwkYYkwwk..kwwk.',
    '.kkkk..kkkkYYkkkk..kkkk.',
    'kkkkkkkkkYYYYkkkkkkkkkkk',
    'kHHHHHHHkkYYkkHHHHHHHHHk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkk..kkkk..kkkk..kkkk.',
    '.kGGk..kGGk..kGGk..kGGk.',
    '.kwwk..kwwk..kwwk..kwwk.',
    '.kkkk..kkkk..kkkk..kkkk.',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
  ], [
    '........................',
    '........................',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'khhhhhhhhhhhhhhhhhhhhhhk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkk..kkkk..kkkk..kkkk.',
    '.kGGk..kGGk..kGGk..kGGk.',
    '.khhk..kwwk..khhk..kwwk.',
    '.kkkk..kkkk..kkkk..kkkk.',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'khhhhhhhkkqqkkhhhhhhhhhk',
    'kkkkkkkkkqqqqkkkkkkkkkkk',
    '.kkkk..kkkkqqkkkk..kkkk.',
    '.kGGk..kGGkqqkGGk..kGGk.',
    '.kwwk..kwwkqqkwwk..kwwk.',
    '.kkkk..kkkkqqkkkk..kkkk.',
    'kkkkkkkkkqqqqkkkkkkkkkkk',
    'khhhhhhhkkqqkkhhhhhhhhhk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkk..kkkk..kkkk..kkkk.',
    '.kGGk..kGGk..kGGk..kGGk.',
    '.kwwk..khhk..kwwk..khhk.',
    '.kkkk..kkkk..kkkk..kkkk.',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
  ]]),

  // BSS-005 Sysadmin — SWEEPING_BEAM / SHOCK_LINE / NODE_ACTIVATION, radius 1.4. Fused into the
  // rack behind it, which is where the destructible nodes live (the LED columns), with a monitor
  // for a head and the beam leaving the frame on one side so its aim is readable before it fires.
  boss('sysadmin', 'A body welded into a server rack, a monitor for a head, a flat beam leaving one side.', [[
    '....kkkkkkkkkkkkkkkk....',
    '....kgGGGGGGGGGGGGgk....',
    '....kgkeeeeeeeeeekgk....',
    '....kgkGGGGGGGGGGkgk....',
    '....kgkeeeeeeeeeekgk....',
    '....kgkGGGGGGGGGGkgk....',
    '....kgkGGkkkkkkGGkgk....',
    '....kgkGkCCCCCCkGkgk....',
    '....kgkGkCwwwwCkGkgk....',
    '....kgkGkCCCCCCkGkgk....',
    '....kgkGkkkkkkkkGkgk....',
    '....kgkGGGGGGGGGGkgkCCC.',
    '....kgkGGwwwwwwGGkgkCCCC',
    '....kgkGGwwwwwwGGkgk....',
    '...kkGGGGGGGGGGGGGGkk...',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGkbbbbbbbbbbbbkGGk..',
    '..kGGkbwwwwwwwwwwbkGGk..',
    '..kGGkbbbbbbbbbbbbkGGk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '...kggggggggggggggggk...',
    '...kkkkkkkkkkkkkkkkkk...',
    '.....kkkk....kkkk.......',
    '.....KKKK....KKKK.......',
  ], [
    '....kkkkkkkkkkkkkkkk....',
    '....kgGGGGGGGGGGGGgk....',
    '....kgkEEEEEEEEEEkgk....',
    '....kgkGGGGGGGGGGkgk....',
    '....kgkeeeeeeeeeekgk....',
    '....kgkGGGGGGGGGGkgk....',
    '....kgkGGkkkkkkGGkgk....',
    '....kgkGkCCCCCCkGkgk....',
    '....kgkGkCCwwCCkGkgk....',
    '....kgkGkCCCCCCkGkgk....',
    '....kgkGkkkkkkkkGkgk....',
    '....kgkGGGGGGGGGGkgkCC..',
    '....kgkGGwwwwwwGGkgkCCC.',
    '....kgkGGwwwwwwGGkgk....',
    '...kkGGGGGGGGGGGGGGkk...',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGkbbbbbbbbbbbbkGGk..',
    '..kGGkbwwwwwwwwwwbkGGk..',
    '..kGGkbbbbbbbbbbbbkGGk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '...kggggggggggggggggk...',
    '...kkkkkkkkkkkkkkkkkk...',
    '.....kkkk....kkkk.......',
    '.....KKKK....KKKK.......',
  ]]),
  // BSS-006 Helpdesk Hydra — HEAD_ROTATION (its whole gimmick) / SHOCK_LINE / SUMMON_ADDS,
  // radius 1.9. If the heads are not visibly separate the rotation pattern is unreadable, so
  // there are three, at three different heights, on coiled cord necks off one shared desk. The
  // lit service windows in the desk front are where the adds come from.
  boss('helpdesk_hydra', 'Three headset heads on coiled cord necks rising from one shared desk.', [[
    '..kkkk..................',
    '.kSSSSk...........kkkk..',
    '.kSnnSk..........kSSSSk.',
    '.kSwwSk..........kSnnSk.',
    '.kkSSkk..........kSwwSk.',
    '..kbbk...kkkk....kkSSkk.',
    '..kbbk..kSSSSk...kbbk...',
    '...kbbk.kSnnSk...kbbk...',
    '...kbbk.kSwwSk..kbbk....',
    '....kbbkkkSSkk..kbbk....',
    '....kbbk.kbbk...kbbk....',
    '.....kbbkkbbk..kbbk.....',
    '.....kbbkbbk...kbbk.....',
    '......kbbbbk..kbbk......',
    '......kkbbbbkkkbbkk.....',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGkwwwwwwkGGkwwwwwwk..',
    '..kGkwHHHHwkGGkwHHHHwk..',
    '..kGkwwwwwwkGGkwwwwwwk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...kk..............kk...',
    '...KKKKKKKKKKKKKKKKKK...',
  ], [
    '........................',
    '..kkkk............kkkk..',
    '.kSSSSk..........kSSSSk.',
    '.kSnnSk..........kSnnSk.',
    '.kSwwSk..........kSHHSk.',
    '.kkSSkk..kkkk....kkSSkk.',
    '..kbbk..kSSSSk...kbbk...',
    '..kbbk..kSnnSk...kbbk...',
    '...kbbk.kSHHSk..kbbk....',
    '...kbbk.kkSSkk..kbbk....',
    '....kbbk.kbbk...kbbk....',
    '....kbbkkbbk....kbbk....',
    '.....kbbkbbk...kbbk.....',
    '......kbbbbk..kbbk......',
    '......kkbbbbkkkbbkk.....',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGkwwwwwwkGGkwwwwwwk..',
    '..kGkwwwwwwkGGkwHHHHwk..',
    '..kGkwwwwwwkGGkwwwwwwk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...kk..............kk...',
    '...KKKKKKKKKKKKKKKKKK...',
  ]]),

  // BSS-007 Legacy System — SPIRAL_STREAM / RADIAL_BURST / TONER_BURST, and an overclock
  // meltdown phase. Radius 2.3, the largest thing in this file. A machine, not a creature: a
  // stepped mainframe built concentrically around a cracked molten core, because every one of
  // its patterns leaves from that centre. The tape reels are the only moving parts.
  boss('legacy_system', 'A stepped mainframe with two tape reels above vents radiating from a cracked core.', [[
    '.......kkkkkkkkkk.......',
    '.......kGGGGGGGGk.......',
    '.....kkkGGGGGGGGkkk.....',
    '.....kkkkkkkkkkkkkk.....',
    '.....kGGGGGGGGGGGGk.....',
    '.....kGkkkkGGkkkkGk.....',
    '.....kGkHHkGGkHHkGk.....',
    '.....kGkHkkGGkkHkGk.....',
    '.....kGkHHkGGkHHkGk.....',
    '.....kGGGGGGGGGGGGk.....',
    '...kkkkkkkkkkkkkkkkkk...',
    '...kGGkkkkRRRRkkkkGGk...',
    '...kGGkwwkRROOkwwkGGk...',
    '...kGGkwwkOORRkwwkGGk...',
    '...kGGkwwkRRRRkwwkGGk...',
    '...kGGkkkkRRRRkkkkGGk...',
    '...kGGGGGGGGGGGGGGGGk...',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kgGGGGGGGGGGGGGGGGGGgk.',
    '.kgkGGkGGkGGkGGkGGkkkgk.',
    '.kgkGGkGGkGGkGGkGGkkkgk.',
    '.kgGGGGGGGGGGGGGGGGGGgk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
  ], [
    '.......kkkkkkkkkk.......',
    '.......kGGGGGGGGk.......',
    '.....kkkGGGGGGGGkkk.....',
    '.....kkkkkkkkkkkkkk.....',
    '.....kGGGGGGGGGGGGk.....',
    '.....kGkkkkGGkkkkGk.....',
    '.....kGkkHkGGkHkkGk.....',
    '.....kGkHHkGGkHHkGk.....',
    '.....kGkkHkGGkHkkGk.....',
    '.....kGGGGGGGGGGGGk.....',
    '...kkkkkkkkkkkkkkkkkk...',
    '...kGGkkkkOOOOkkkkGGk...',
    '...kGGkwwkOORRkwwkGGk...',
    '...kGGkwwkRROOkwwkGGk...',
    '...kGGkwwkOOOOkwwkGGk...',
    '...kGGkkkkOOOOkkkkGGk...',
    '...kGGGGGGGGGGGGGGGGk...',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kgGGGGGGGGGGGGGGGGGGgk.',
    '.kgkGGkGGkGGkGGkGGkkkgk.',
    '.kgkGGkGGkGGkGGkGGkkkgk.',
    '.kgGGGGGGGGGGGGGGGGGGgk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
  ]]),

  // BSS-008 Firewall — SWEEPING_WALL / AIMED_VOLLEY / NODE_ACTIVATION, and an "open ports"
  // phase. It is a wall. No head, no legs, nothing above the crenellation but flame, so it can
  // never be mistaken for something that will chase you. The three shuttered ports are the
  // activation nodes and the volley origins; the middle one is already open, which is the tell.
  boss('firewall', 'A brick rampart with no head and no legs; three shuttered ports and flame along the top.', [[
    '..r...r......r...r...r..',
    '.rRr.rRr....rRr.rRr.rRr.',
    'kRRRkRRRkkkkRRRkRRRkRRRk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'okkkkkkookkkkkkookkkkkko',
    'okggggkookrrrrkookggggko',
    'okggggkookrRRrkookggggko',
    'okggggkookrrrrkookggggko',
    'okkkkkkookkkkkkookkkkkko',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
    '........................',
  ], [
    '.r...r...r......r...r...',
    'rRr.rRr.rRr....rRr.rRr..',
    'kRRRkRRRkkkkRRRkRRRkRRRk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'okkkkkkookkkkkkookkkkkko',
    'okggggkookRRRRkookggggko',
    'okggggkookRppRkookggggko',
    'okggggkookRRRRkookggggko',
    'okkkkkkookkkkkkookkkkkko',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'koooookoooookoooookooooo',
    'oookoooookoooookoooookoo',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
    '........................',
  ]]),

  // BSS-009 The Bottleneck — OBSTACLE_DEPLOY / AIMED_VOLLEY / CONTACT_CHARGE / CROSS_LANES,
  // radius 2.1. An hourglass of stacked crates: wide above, pinched to a jammed red neck, then
  // flaring out onto a heavy leading slab that is wider than the rest and offset to one side.
  // That slab is the charge, and the crates it deploys are visibly the same crates it is made of.
  boss('the_bottleneck', 'An hourglass of stacked crates pinching to a jammed neck, over a heavy leading slab.', [[
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..kooookooookooookoook..',
    '..kooookooookooookoook..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kooookooookooookoook..',
    '..kooookooookooookoook..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...kkkkkkkkkkkkkkkkkk...',
    '....kooookoooookooook...',
    '.....kkkkkkkkkkkkkkk....',
    '......kooookoooook......',
    '.......kkkkkkkkkkk......',
    '.......kRRRkRRRRk.......',
    '.......kkkkkkkkkkk......',
    '.....kkkkkkkkkkkkkk.....',
    '....kooookooookooook....',
    '....kkkkkkkkkkkkkkkk....',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kooookooookooookoook..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    'kkkkkkkkkkkkkkkkkkkkkk..',
    'kGGGGGGGGGGGGGGGGGGGGk..',
    'kkkkkkkkkkkkkkkkkkkkkk..',
    'KKKKKKKKKKKKKKKKKKKKKK..',
  ], [
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..kooookooookooookoook..',
    '..kooookooookooookoook..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kooookooookooookoook..',
    '..kooookooookooookoook..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...kkkkkkkkkkkkkkkkkk...',
    '....kooookoooookooook...',
    '.....kkkkkkkkkkkkkkk....',
    '......kooookoooook......',
    '.......kkkkkkkkkkk......',
    '.......kOOOkRRRRk.......',
    '.......kkkkkkkkkkk......',
    '.....kkkkkkkkkkkkkk.....',
    '....kooookooookooook....',
    '....kkkkkkkkkkkkkkkk....',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kooookooookooookoook..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ]]),

  // BSS-010 Shift Manager — SUMMON_ADDS / BUFF_ADDS / AIMED_VOLLEY / CONTACT_CHARGE, radius 1.4.
  // Humanoid, and sharing a pattern set with BSS-001, so it must not share a shape: the mass is
  // at the chest (a punch clock, whose hands move) instead of above the head, one arm is raised
  // with a whistle instead of two spread wide, and the rota is pinned down one side only.
  boss('shift_manager', 'A punch clock for a chest, one arm raised with a whistle, rota pinned down one side.', [[
    '.....kkkk...............',
    '....kYYYYk..............',
    '....kYYYYk..kkkkkk......',
    '.....kkkk..kSSSSSSk.....',
    '.....kSSk..kSnnnnSk.....',
    '.....kSSk..kSkwwkSk.....',
    '.....kSSk...kkSSSSkk....',
    '.....kSSk....kwwwwk.....',
    '....kkSSkkkkkkGGGGkk....',
    '...kGGGGGGGGGGGGGGGGk...',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGGkkkkkkkkkkGkwwwwk.',
    '..kGGGkWWWWWWWWkGkwwwwk.',
    '..kGGGkWWkkkkWWkGkwwwwk.',
    '..kGGGkWWkkkkWWkGkwwwwk.',
    '..kGGGkWWWWWWWWkGkwwwwk.',
    '..kGGGkkkkkkkkkkGkkkkkk.',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '...kGGGGGGGGGGGGGGGGk...',
    '....kgggggggggggggggk...',
    '....kgggggk..kgggggk....',
    '....kgggggk..kgggggk....',
    '....kkkkkk....kkkkkk....',
    '....KKKKKK....KKKKKK....',
  ], [
    '.....kkkk...............',
    '....kqqqqk..............',
    '....kqqqqk..kkkkkk......',
    '.....kkkk..kSSSSSSk.....',
    '.....kSSk..kSnnnnSk.....',
    '.....kSSk..kSkHHkSk.....',
    '.....kSSk...kkSSSSkk....',
    '.....kSSk....kwwwwk.....',
    '....kkSSkkkkkkGGGGkk....',
    '...kGGGGGGGGGGGGGGGGk...',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGGkkkkkkkkkkGkwwwwk.',
    '..kGGGkWWWWWWWWkGkwwwwk.',
    '..kGGGkWWWWkkWWkGkwwwwk.',
    '..kGGGkWWkkkkWWkGkwwwwk.',
    '..kGGGkWWWWWWWWkGkwwwwk.',
    '..kGGGkkkkkkkkkkGkkkkkk.',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '...kGGGGGGGGGGGGGGGGk...',
    '....kgggggggggggggggk...',
    '....kgggggk..kgggggk....',
    '....kgggggk..kgggggk....',
    '....kkkkkk....kkkkkk....',
    '....KKKKKK....KKKKKK....',
  ]]),
  // BSS-011 Supply Chain — a circulating phase and a rerouted phase, radius 1.8. So the body is
  // a closed loop with a hole in the middle: a conveyor belt eating its own tail, crates riding
  // the top run, and one spur belt breaking out through the right wall and off the frame. That
  // spur is the reroute. Nothing here is a head, which is the point — you cannot decapitate it.
  boss('supply_chain', 'A segmented conveyor loop with a hollow centre and one spur belt leaving the frame.', [[
    '....kook..kook..kook....',
    '....kook..kook..kook....',
    '....kkkk..kkkk..kkkk....',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGkkkkkkkkkkkkkkkkGk..',
    '..kGk..............kGk..',
    '..kGk..............kGkkk',
    '..kGk..............kGGGG',
    '..kGk..............kGkkk',
    '..kGk..............kGk..',
    '..kGk..kkk....kkk..kGk..',
    '..kGk..kHk....kHk..kGk..',
    '..kGk..kkk....kkk..kGk..',
    '..kGk..............kGk..',
    '..kGk..............kGk..',
    '..kGk..............kGk..',
    '..kGk..............kGk..',
    '..kGkkkkkkkkkkkkkkkkGk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '....kkkk......kkkk......',
    '....KKKK......KKKK......',
    '..KKKKKKKKKKKKKKKKKKKK..',
  ], [
    '.....kook..kook..kook...',
    '.....kook..kook..kook...',
    '.....kkkk..kkkk..kkkk...',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGkkkkkkkkkkkkkkkkGk..',
    '..kGk..............kGk..',
    '..kGk..............kGkkk',
    '..kGk..............kGGkG',
    '..kGk..............kGkkk',
    '..kGk..............kGk..',
    '..kGk..kkk....kkk..kGk..',
    '..kGk..kGk....kGk..kGk..',
    '..kGk..kkk....kkk..kGk..',
    '..kGk..............kGk..',
    '..kGk..............kGk..',
    '..kGk..............kGk..',
    '..kGk..............kGk..',
    '..kGkkkkkkkkkkkkkkkkGk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '....kkkk......kkkk......',
    '....KKKK......KKKK......',
    '..KKKKKKKKKKKKKKKKKKKK..',
  ]]),

  // BSS-012 Quarter End — week one, first deadline, crunch: a fight that accelerates. Radius 1.6.
  // A date, given a body. Top-heavy on purpose — a calendar grid the full width of the frame,
  // stepping down to a pillar of days three pixels wide, with no feet at all. The gold cell is
  // the deadline, and between frames it advances one day, which is the only thing it ever does.
  boss('quarter_end', 'A top-heavy calendar wedge stepping down to a thin pillar of days; no feet.', [[
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'kRRRRRRRRRRRRRRRRRRRRRRk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'kwwwkwwwkwwwkwwwkwwwkwwk',
    'kwwwkwwwkwwwkwwwkwwwkwwk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kwwkwwwkwwwkwwwkwwwkwk.',
    '.kwwkwwwkwwwkwwwkwwwkwk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..kwwkwwwkwwwkAAAkwwwk..',
    '..kwwkwwwkwwwkAAAkwwwk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...kkkkkkkkkkkkkkkkkk...',
    '....kwwkwwwkwwwkwwwk....',
    '....kkkkkkkkkkkkkkkk....',
    '......kkkkkkkkkkkk......',
    '.......kwwkwwwkwwk......',
    '.......kkkkkkkkkkk......',
    '........kkkkkkkkk.......',
    '.........kkkkkkk........',
    '..........kkkkk.........',
    '...........kkk..........',
    '...........kkk..........',
    '..........KKKKK.........',
  ], [
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'krrrrrrrrrrrrrrrrrrrrrrk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    'kwwwkwwwkwwwkwwwkwwwkwwk',
    'kwwwkwwwkwwwkwwwkwwwkwwk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kwwkwwwkwwwkwwwkwwwkwk.',
    '.kwwkwwwkwwwkwwwkwwwkwk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..kwwkwwwkwwwkwwwkAAAk..',
    '..kwwkwwwkwwwkwwwkAAAk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...kkkkkkkkkkkkkkkkkk...',
    '....kwwkwwwkwwwkwwwk....',
    '....kkkkkkkkkkkkkkkk....',
    '......kkkkkkkkkkkk......',
    '.......kwwkwwwkwwk......',
    '.......kkkkkkkkkkk......',
    '........kkkkkkkkk.......',
    '.........kkkkkkk........',
    '..........kkkkk.........',
    '...........kkk..........',
    '...........kkk..........',
    '..........KKKKK.........',
  ]]),

  // BSS-013 VP of Everything — delegating, then a recognition exam, then personally involved.
  // Radius 1.7. Four arms, because the joke and the fight are the same joke: it holds every
  // department's tool at once. A phone, a chart, a mug, a pen, and a stack of nameplates above
  // the head instead of a crown. The widest thing in its outline is always something it is holding.
  boss('vp_of_everything', 'A suit with four arms, each holding a different tool, under a stack of nameplates.', [[
    '.......kkkkkkkkkk.......',
    '.......kaAAAAAAak.......',
    '......kkkkkkkkkkkk......',
    '......kaAAAAAAAAak......',
    '.......kkkkkkkkkk.......',
    '........kkkkkkkk........',
    '.......kSSSSSSSSk.......',
    '.......kSnnnnnnSk.......',
    '.......kSkwwwwkSk.......',
    '........kkSSSSkk........',
    '.........kwwwwk.........',
    'kkkk..kkGGGGGGGGkk..kkkk',
    'kbbk.kSGGGGGGGGGGSk.kwwk',
    'kkkk.kkGGGGGGGGGGkk.kkkk',
    '.....kGGGGGGGGGGGGk.....',
    'kkk.kkGGkwwwwwwkGGkk.kkk',
    'kOOkkSGGkwAAAAwkGGSkkYYk',
    'kkk.kkGGkwwwwwwkGGkk.kkk',
    '.....kGGGGGGGGGGGGk.....',
    '.....kgggggggggggk......',
    '.....kgggk..kgggk.......',
    '.....kgggk..kgggk.......',
    '.....kkkkk..kkkkk.......',
    '.....KKKKK..KKKKK.......',
  ], [
    '.......kkkkkkkkkk.......',
    '.......kaqqqqqqak.......',
    '......kkkkkkkkkkkk......',
    '......kaAAAAAAAAak......',
    '.......kkkkkkkkkk.......',
    '........kkkkkkkk........',
    '.......kSSSSSSSSk.......',
    '.......kSnnnnnnSk.......',
    '.......kSkwwHHkSk.......',
    '........kkSSSSkk........',
    '.........kwwwwk.........',
    'kkkk..kkGGGGGGGGkk..kkkk',
    'kBBk.kSGGGGGGGGGGSk.kWWk',
    'kkkk.kkGGGGGGGGGGkk.kkkk',
    '.....kGGGGGGGGGGGGk.....',
    'kkk.kkGGkwwwwwwkGGkk.kkk',
    'kOOkkSGGkwqqqqwkGGSkkyyk',
    'kkk.kkGGkwwwwwwkGGkk.kkk',
    '.....kGGGGGGGGGGGGk.....',
    '.....kgggggggggggk......',
    '.....kgggk..kgggk.......',
    '.....kgggk..kgggk.......',
    '.....kkkkk..kkkkk.......',
    '.....KKKKK..KKKKK.......',
  ]]),

  // BSS-014 Chief Operating Officer — zoning, security sweep, restructure. Radius 1.7. Stands
  // behind the floor plan it is rearranging, so the bottom third of the silhouette is furniture
  // and the boss cannot be read as something that walks at you. The searchlight lens replaces one
  // eye and throws a beam out of the frame (the sweep); the T-square is the only limb that shows.
  boss('chief_operating_officer', 'A broad suit behind a floor-plan table, a T-square arm and one searchlight eye.', [[
    '........................',
    '.......kkkkkkkkk........',
    '......kSSSSSSSSSk.......',
    '......kSnnnnnnnSk.......',
    'CCCCCCkSkCCkwwkSk.......',
    '......kkSSSSSSSkk.......',
    '........kwwwwwk.........',
    '...kkkkkGGGGGGGkkkkk....',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGGGkwwwwwwwkGGGGGk..',
    '..kGGGGkwAAAAAwkGGGGGk..',
    '..kGGGGkwwwwwwwkGGGGGk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGGGGGGGGGGGGGGGGGkkk',
    '..kGGGGGGGGGGGGGGGGGGkHk',
    '...kkkkkkkkkkkkkkkkkkkHk',
    '...kwwwwwwwwwwwwwwwwkkHk',
    '...kwGGwwGGwwGGwwGGwkkHk',
    '...kwwwwwwwwwwwwwwwwkkHk',
    '...kkkkkkkkkkkkkkkkkkkkk',
    '....kk............kk....',
    '....kk............kk....',
    '....kk............kk....',
    '...KKKKKKKKKKKKKKKKKK...',
  ], [
    '........................',
    '.......kkkkkkkkk........',
    '......kSSSSSSSSSk.......',
    '......kSnnnnnnnSk.......',
    '...CCCkSkCCkwwkSk.......',
    '......kkSSSSSSSkk.......',
    '........kwwwwwk.........',
    '...kkkkkGGGGGGGkkkkk....',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGGGkwwwwwwwkGGGGGk..',
    '..kGGGGkwqqqqqwkGGGGGk..',
    '..kGGGGkwwwwwwwkGGGGGk..',
    '..kGGGGGGGGGGGGGGGGGGk..',
    '..kGGGGGGGGGGGGGGGGGGkkk',
    '..kGGGGGGGGGGGGGGGGGGkhk',
    '...kkkkkkkkkkkkkkkkkkkhk',
    '...kwwwwwwwwwwwwwwwwkkhk',
    '...kwwGGwwGGwwGGwwGGkkhk',
    '...kwwwwwwwwwwwwwwwwkkhk',
    '...kkkkkkkkkkkkkkkkkkkkk',
    '....kk............kk....',
    '....kk............kk....',
    '....kk............kk....',
    '...KKKKKKKKKKKKKKKKKK...',
  ]]),

  // BSS-015 The Boardroom — a first vote phase, then a synchronized phase. Radius 2.0. Furniture,
  // not a person: an oval table ringed with high-backed chairs, and the chairs are the heads. The
  // synchronized phase is legible because the heads nod together between frames, and the empty
  // seat on the bottom right is the asymmetry — and the one that fills when it summons.
  boss('the_boardroom', 'An oval table ringed with high-backed chairs whose heads nod; no body at all.', [[
    '...kkkkk..kkkkk..kkkkk..',
    '...kgggk..kgggk..kgggk..',
    '...kgSgk..kgSgk..kgSgk..',
    '...kkkkk..kkkkk..kkkkk..',
    '....kkk....kkk....kkk...',
    '.....kkkkkkkkkkkkkk.....',
    '...kkoooooooooooooookk..',
    '..kooooooooooooooooook..',
    '..koOOOOOOOOOOOOOOOOok..',
    '..koOwwwwwwwwwwwwwwOok..',
    '..koOwwkAAkwwwkAAkwOok..',
    '..koOwwwwwwwwwwwwwwOok..',
    '..koOOOOOOOOOOOOOOOOok..',
    '..kooooooooooooooooook..',
    '...kkoooooooooooooookk..',
    '.....kkkkkkkkkkkkkk.....',
    '....kkk....kkk....kkk...',
    '...kkkkk..kkkkk..kkkkk..',
    '...kgSgk..kgSgk..kgggk..',
    '...kgggk..kgggk..kgggk..',
    '...kkkkk..kkkkk..kkkkk..',
    '....kk......kk......kk..',
    '....KK......KK......KK..',
    '..KKKKKKKKKKKKKKKKKKKK..',
  ], [
    '...kkkkk..kkkkk..kkkkk..',
    '...kgSgk..kgSgk..kgSgk..',
    '...kgggk..kgggk..kgggk..',
    '...kkkkk..kkkkk..kkkkk..',
    '....kkk....kkk....kkk...',
    '.....kkkkkkkkkkkkkk.....',
    '...kkoooooooooooooookk..',
    '..kooooooooooooooooook..',
    '..koOOOOOOOOOOOOOOOOok..',
    '..koOwwwwwwwwwwwwwwOok..',
    '..koOwwkaakwwwkaakwOok..',
    '..koOwwwwwwwwwwwwwwOok..',
    '..koOOOOOOOOOOOOOOOOok..',
    '..kooooooooooooooooook..',
    '...kkoooooooooooooookk..',
    '.....kkkkkkkkkkkkkk.....',
    '....kkk....kkk....kkk...',
    '...kkkkk..kkkkk..kkkkk..',
    '...kgggk..kgggk..kgSgk..',
    '...kgSgk..kgSgk..kgggk..',
    '...kkkkk..kkkkk..kkkkk..',
    '....kk......kk......kk..',
    '....KK......KK......KK..',
    '..KKKKKKKKKKKKKKKKKKKK..',
  ]]),
];

export default early;
