/**
 * Sprite domain: LATE and POSTGAME bosses (BSS-016..029). Owns `boss_` ids in this range.
 *
 * GDD refs: 18.3 / R-VIS-002 (distinct silhouette before palette is considered; intent
 *           readable at a glance), R-ART-004 / R-DPT-005 (grayscale-legible), 15.4 (the
 *           phase template — the silhouette has to telegraph the patterns), Appendix E
 *           (Core fight lines), 10.4 / 16.2 (the ownership chain these end on).
 *
 * The problem: fourteen bosses in a row, each stranger than the last, all still legible at
 * a glance. The mid roster could still lean on "person in a suit". This one cannot, and
 * should not: the GDD says the later and hidden floors "reveal impossible scale, conflicting
 * ownership, service spaces that do not fit inside the building, and corporate structures
 * that are architectural as well as organizational". So most of these are not people. A
 * committee is several bodies acting as one body. A viral campaign is a spreading pattern
 * with detached pieces. Red tape is material. The Conglomerate is a building.
 *
 * Escalation is carried by WHAT KIND OF THING each boss is, in roughly this order:
 *
 *   person (016, 019, 023)  ->  person-shaped but wrong (017, 021)
 *   ->  several bodies as one (018, 025)  ->  machine (024)
 *   ->  material / pattern (020, 022)  ->  mass that eats other bosses (026)
 *   ->  blank corporate object (027)  ->  architecture (028)  ->  almost nothing (029)
 *
 * Each silhouette also telegraphs the fight, per R-VIS-002: radial bursts get a radial
 * body, summons get visible ports or open arms, absorption gets a visible maw with other
 * bodies already inside it, and the three planted bosses have no legs at all.
 *
 * BSS-029 The Beneficial Owner runs against the whole file on purpose. Appendix E calls its
 * fight "a minimalist final duel that ... removes layers until only movement and core weapon
 * skill remain", and its phase data really does get simpler as its health drops. A busy
 * final sprite would lie about that. So the last boss in the game is the emptiest sprite in
 * the game: a hairline stroke, a single hollow ring, and negative space. Thirteen sprites
 * spend their budget earning that contrast; the fourteenth spends almost none.
 *
 *   ceo                   suited figure whose chest is an open machine core, gold crown collar
 *   the_auditor           a tall narrow lens-headed column with a tally tape hanging beside it
 *   budget_committee      three heads sharing one wide bench around a lit gold budget pot
 *   brand_manager         a figure holding a blank cut-out panel beside its own hollow decoy
 *   viral_campaign        a radial kernel with dotted arms out to four detached ad nodes
 *   general_counsel       a floor-length robe triangle, no legs, an open book with a seal
 *   red_tape              a giant roll with a whipping tongue and tape looped on the floor
 *   head_of_facilities    a tiny operator dwarfed by a wall panel of valves and breakers
 *   prototype_zero        a glowing core suspended inside a gimbal ring on a test rig
 *   the_board             five seated members ringing a hollow white table
 *   hostile_takeover      a lopsided mass with absorbed faces inside it and an open maw
 *   parent_company        a blank white slab with an erased brand patch and a ghost inside
 *   the_conglomerate      a skyline: three towers of different heights on a gold lobby band
 *   the_beneficial_owner  one hairline stroke under a single hollow ring; nothing else
 *
 * Grids are 24x24. `scale: 4` is only a fallback — main.js overrides it from each boss's
 * collision radius, which ranges 1.4..2.6 across this roster.
 */

const SCALE = 4;

const boss = (slug, silhouette, frames, anchor = [0.5, 0.9]) => ({
  id: `boss_${slug}`,
  anchor,
  scale: SCALE,
  silhouette,
  frames,
});

const late = [
  // BSS-016 CEO — "Three phases: charismatic presentation, hostile restructuring with adds,
  // and exposed machine-like corporate core." The reveal is baked into the idle: the suit is
  // already open, and what is inside it is a lit aperture, not a person. The gold collar is
  // wider than the shoulders so the crown reads before the face does.
  boss('ceo', 'Suited figure whose chest is an open machine core, under a gold crown collar wider than its shoulders.', [[
    '........................',
    '.........kkkkkk.........',
    '........kAAAAAAk........',
    '........kAqqqqAk........',
    '.......kkAAAAAAkk.......',
    '........kSSSSSSk........',
    '........kSnnnnSk..kkkkk.',
    '........ksSSSSsk..kAAAk.',
    '.........kwwwwk...kAAAk.',
    '....kkkkkGGGGGGkkkkkkkk.',
    '...kAAAAkGGGGGGkAAAAk...',
    '......kGGGGGGGGGGk......',
    '......kGkkkkkkkkGk......',
    '......kGkCCwwCCkGk......',
    '......kGkCwAAwCkGk......',
    '......kGkCCwwCCkGk......',
    '......kGkkkkkkkkGk......',
    '......kGGGGGGGGGGk......',
    '......kggggggggggk......',
    '.....kkkkkkkkkkkkk......',
    '....kHHHHHHHHHHHHHk.....',
    '....kHwwwwwwwwwwwHk.....',
    '....kkkkkkkkkkkkkkk.....',
    '.....KKKKKKKKKKKKK......',
  ], [
    '........................',
    '.........kkkkkk.........',
    '........kAqqqqAk........',
    '........kAAAAAAk........',
    '.......kkAAAAAAkk.......',
    '........kSSSSSSk..kkkkk.',
    '........kSnnnnSk..kAAAk.',
    '........ksSSSSsk..kAAAk.',
    '.........kwwwwk...kkkkk.',
    '....kkkkkGGGGGGkkkkkkkk.',
    '...kAAAAkGGGGGGkAAAAk...',
    '......kGGGGGGGGGGk......',
    '......kGkkkkkkkkGk......',
    '......kGkCwwwwCkGk......',
    '......kGkCAAAACkGk......',
    '......kGkCwwwwCkGk......',
    '......kGkkkkkkkkGk......',
    '......kGGGGGGGGGGk......',
    '......kggggggggggk......',
    '.....kkkkkkkkkkkkk......',
    '....kHHHHHHHHHHHHHk.....',
    '....kHwwwwwwwwwwwHk.....',
    '....kkkkkkkkkkkkkkk.....',
    '.....KKKKKKKKKKKKK......',
  ]]),

  // BSS-017 The Auditor — "Tracks spending, marks pickups, and creates ledger lanes that
  // reconcile after a delay." A turret, so no legs. The head is a lens twice the width of the
  // body, and the tally tape hanging down one side is the only asymmetry it needs; it also
  // reads as the delay itself, a thing already printed and waiting to settle.
  boss('the_auditor', 'A tall narrow lens-headed column with no legs and a long tally tape hanging down one side.', [[
    '.......kkkkkkkkkk.......',
    '......kCCCCCCCCCCk......',
    '.....kCCwwwwwwwwCCk.....',
    '.....kCwwWWWWWWwwCk.....',
    '.....kCwwWWWWWWwwCk.....',
    '.....kCCwwwwwwwwCCk.....',
    '......kCCCCCCCCCCk......',
    '.......kkkkGGkkkk.......',
    '.........kGGk...kkk.....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kkGGkk..kwwk....',
    '.........kGGk...kwwk....',
    '.........kGGk...kkkk....',
    '........kkkkkk..........',
    '.........KKKK...KKK.....',
  ], [
    '.......kkkkkkkkkk.......',
    '......kCCCCCCCCCCk......',
    '.....kCCwwwwwwwwCCk.....',
    '.....kCwwWWWWWWwwCk.....',
    '.....kCwwwwwwwwwwCk.....',
    '.....kCCwwWWWWwwCCk.....',
    '......kCCCCCCCCCCk......',
    '.......kkkkGGkkkk.......',
    '.........kGGk...........',
    '........kGGGGk..kkk.....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGwwGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kGGGGk..kwwk....',
    '........kkGGkk..kwwk....',
    '.........kGGk...kwwk....',
    '.........kGGk...kwwk....',
    '........kkkkkk..kkkk....',
    '.........KKKK...KKK.....',
  ]]),

  // BSS-018 Budget Committee — "Three members allocate armor, projectiles, and resource theft
  // through a visible rotating budget." Three heads, one body: the bench is continuous, so it
  // reads as one wide committee rather than three enemies. The pot is the brightest thing on
  // the sprite because the fight is about watching it, and its wedge rotates between frames.
  boss('budget_committee', 'Three heads sharing one continuous wide bench around a lit gold budget pot.', [[
    '........................',
    '..kkkk....kkkk....kkkk..',
    '.kSSSSk..kSSSSk..kSSSSk.',
    '.kSnnSk..kSNNSk..kSooSk.',
    '.kkSSkk..kkSSkk..kkSSkk.',
    '..kGGk....kGGk....kGGk..',
    '.kkGGkk..kkGGkk..kkGGkk.',
    'kGGGGGGkkGGGGGGkkGGGGGGk',
    'kGGGGGGGGGGGGGGGGGGGGGGk',
    'kGGGkkkkkkkkkkkkkkkkGGGk',
    'kGGGkAAAAAAAAAAAAAAkGGGk',
    'kGGGkAqqqqqqqqqqqqAkGGGk',
    'kGGGkAqqAAAAAAqqqqAkGGGk',
    'kGGGkAqqqqqqqqqqqqAkGGGk',
    'kGGGkAAAAAAAAAAAAAAkGGGk',
    'kGGGkkkkkkkkkkkkkkkkGGGk',
    'kGGGGGGGGGGGGGGGGGGGGGGk',
    'kggggggggggggggggggggggk',
    'kkgggggggggggggggggggykk',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwwwwwwwwwk.',
    '.kwwwwwwwwwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKKKKKKKKKK..',
  ], [
    '........................',
    '..kkkk....kkkk....kkkk..',
    '.kSSSSk..kSSSSk..kSSSSk.',
    '.kSNNSk..kSnnSk..kSOOSk.',
    '.kkSSkk..kkSSkk..kkSSkk.',
    '..kGGk....kGGk....kGGk..',
    '.kkGGkk..kkGGkk..kkGGkk.',
    'kGGGGGGkkGGGGGGkkGGGGGGk',
    'kGGGGGGGGGGGGGGGGGGGGGGk',
    'kGGGkkkkkkkkkkkkkkkkGGGk',
    'kGGGkAAAAAAAAAAAAAAkGGGk',
    'kGGGkAqqqqqqqqqqqqAkGGGk',
    'kGGGkAqqqqAAAAAAqqAkGGGk',
    'kGGGkAqqqqqqqqqqqqAkGGGk',
    'kGGGkAAAAAAAAAAAAAAkGGGk',
    'kGGGkkkkkkkkkkkkkkkkGGGk',
    'kGGGGGGGGGGGGGGGGGGGGGGk',
    'kggggggggggggggggggggggk',
    'kkgyggggggggggggggggggkk',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwwwwwwwwwk.',
    '.kwwwwwwwwwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKKKKKKKKKK..',
  ]]),
  // BSS-019 Brand Manager — "Creates decoy bosses and false reward silhouettes while the real
  // attacks remain identifiable by shadow and audio." The sprite states the trick: a real
  // figure holding a blank cut-out panel, and beside it the same panel drawn as a hollow
  // outline with nothing in it. The decoy is the half that breathes out of sync.
  boss('brand_manager', 'A figure holding up a blank cut-out panel beside a hollow outline of itself.', [[
    '........................',
    '..kkkkkkkkkk.hhhhhhhhhh.',
    '..kwwwwwwwwk.h........h.',
    '..kwwkkkkwwk.h........h.',
    '..kwwkAAkwwk.h........h.',
    '..kwwkkkkwwk.h........h.',
    '..kwwwwwwwwk.h........h.',
    '..kkkkkkkkkk.hhhhhhhhhh.',
    '.....kGGk...............',
    '....kkkkkk..............',
    '...kSSSSSSk.............',
    '...kSNNNNSk.............',
    '...kkSSSSkk.............',
    '..kkkGGGGkkk............',
    '.kGGGGGGGGGGk...........',
    '.kGGkppppkGGk...........',
    '.kGGGppppGGGk...........',
    '.kkGGGGGGGGkk...........',
    '..kgggggggk.............',
    '..kgggggggk.............',
    '..kgg..ggk..............',
    '..kgg..ggk..............',
    '..kkk..kkk..............',
    '..KKK..KKK..............',
  ], [
    '........................',
    '..kkkkkkkkkk............',
    '..kwwwwwwwwk.hhhhhhhhhh.',
    '..kwwkkkkwwk.h........h.',
    '..kwwkAAkwwk.h........h.',
    '..kwwkkkkwwk.h........h.',
    '..kwwwwwwwwk.h........h.',
    '..kkkkkkkkkk.h........h.',
    '.....kGGk....hhhhhhhhhh.',
    '....kkkkkk..............',
    '...kSSSSSSk.............',
    '...kSNNNNSk.............',
    '...kkSSSSkk.............',
    '..kkkGGGGkkk............',
    '.kGGGGGGGGGGk...........',
    '.kGGkppppkGGk...........',
    '.kGGGppppGGGk...........',
    '.kkGGGGGGGGkk...........',
    '..kgggggggk.............',
    '..kgggggggk.............',
    '..kgg..ggk..............',
    '..kgg..ggk..............',
    '..kkk..kkk..............',
    '..KKK..KKK..............',
  ]]),

  // BSS-020 Viral Campaign — "A central campaign spreads copies through ad nodes. Destroying
  // nodes limits pattern replication." Not a body at all. The kernel is radial because its
  // patterns are radial, and the four ad nodes are drawn DETACHED, joined only by a dotted
  // spread that advances a step between frames: the nodes are separate targets, so they are
  // separate shapes.
  boss('viral_campaign', 'A radial kernel with dotted arms reaching out to four detached ad nodes.', [[
    '.kkkk..............kkkk.',
    '.kOOk..............kOOk.',
    '.kOOk..............kOOk.',
    '.kkkk..............kkkk.',
    '....O............O......',
    '.....O..........O.......',
    '......O........O........',
    '.......kkkkkkkkkk.......',
    '......kRRRRRRRRRRk......',
    '.....kRROOOOOOOORRk.....',
    '.....kROOYYYYYYOORk.....',
    '.....kROOYWWWWYOORk.....',
    '.....kROOYWWWWYOORk.....',
    '.....kROOYYYYYYOORk.....',
    '.....kRROOOOOOOORRk.....',
    '......kRRRRRRRRRRk......',
    '.......kkkkkkkkkk.......',
    '......O........O........',
    '.....O..........O.......',
    '....O............O......',
    '.kkkk..............kkkk.',
    '.kOOk..............kOOk.',
    '.kkkk..............kkkk.',
    '.KKKK..............KKKK.',
  ], [
    '.kkkk..............kkkk.',
    '.kOOk..............kOOk.',
    '.kOOk..............kOOk.',
    '.kkkk..............kkkk.',
    '.....R..........R.......',
    '......R........R........',
    '.......R......R.........',
    '.......kkkkkkkkkk.......',
    '......kROOOOOOOORk......',
    '.....kROOYYYYYYOORk.....',
    '.....kOOYWWWWWWYOOk.....',
    '.....kOYWWWWWWWWYOk.....',
    '.....kOYWWWWWWWWYOk.....',
    '.....kOOYWWWWWWYOOk.....',
    '.....kROOYYYYYYOORk.....',
    '......kROOOOOOOORk......',
    '.......kkkkkkkkkk.......',
    '.......R......R.........',
    '......R........R........',
    '.....R..........R.......',
    '.kkkk..............kkkk.',
    '.kOOk..............kOOk.',
    '.kkkk..............kkkk.',
    '.KKKK..............KKKK.',
  ]]),

  // BSS-021 General Counsel — "Uses clauses, binding zones, and delayed rulings with explicit
  // icons and countdowns." The only pure triangle in the game: a robe that widens all the way
  // to the floor, with no legs, because it does not chase. The open book sits at the centre of
  // mass and its gold seal is the countdown — it is the one thing that changes between frames.
  boss('general_counsel', 'A floor-length robe triangle with no legs and an open book with a blinking seal.', [[
    '........................',
    '.........kkkkkk.........',
    '........kmmmmmmk........',
    '........kmSSSSmk........',
    '........kmSddSmk........',
    '........kkSSSSkk........',
    '.......kkkmmmmkkk.......',
    '......kmmmmmmmmmmk......',
    '.....kmmmmmmmmmmmmk.....',
    '.....kmmkwwwwwwkmmk.....',
    '....kmmkwwkkkkwwkmmk....',
    '....kmmkwwkAAkwwkmmk....',
    '....kmmkwwkkkkwwkmmk....',
    '...kmmmkwwwwwwwwkmmmk...',
    '...kmmmkkkkkkkkkkmmmk...',
    '..kmmmmmmmmmmmmmmmmmmk..',
    '..kmmmmmmmmmmmmmmmmmmk..',
    '.kmmmmmmmmmmmmmmmmmmmmk.',
    '.kmmvvmmmmmmmmmmmmvvmmk.',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmvvmmmmmmmmmmmmmmmmvvmk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ], [
    '........................',
    '.........kkkkkk.........',
    '........kmmmmmmk........',
    '........kmSSSSmk........',
    '........kmSddSmk........',
    '........kkSSSSkk........',
    '.......kkkmmmmkkk.......',
    '......kmmmmmmmmmmk......',
    '.....kmmmmmmmmmmmmk.....',
    '.....kmmkwwwwwwkmmk.....',
    '....kmmkwwkkkkwwkmmk....',
    '....kmmkwwkqqkwwkmmk....',
    '....kmmkwwkkkkwwkmmk....',
    '...kmmmkwwwwwwwwkmmmk...',
    '...kmmmkkkkkkkkkkmmmk...',
    '..kmmmmmmmmmmmmmmmmmmk..',
    '..kmmmmmmmmmmmmmmmmmmk..',
    '.kmmmmmmmmmmmmmmmmmmmmk.',
    '.kmmMMmmmmmmmmmmmmMMmmk.',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmMMmmmmmmmmmmmmmmmmMMmk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ]]),

  // BSS-022 Red Tape — "A giant living roll creates walls, knots, and temporary seals around
  // the arena." Material, not a person: no head, no face, no limbs. The roll is the body and
  // the free end is the weapon, so the tongue whips a pixel between frames while a second
  // length already lies knotted across the floor — the walls it makes, pre-announced.
  boss('red_tape', 'A giant roll with no head, a whipping free end, and tape already knotted on the floor.', [[
    '........................',
    '....................kkk.',
    '...................krrk.',
    '..............kkkkkrrk..',
    '.............krrrrrrrk..',
    '.............krrkkkkkk..',
    '....kkkkkk...krrk.......',
    '..kkrrrrrrkkkrrk........',
    '.krrrrrrrrrrrrrrk.......',
    '.krrrRRRRRRRRrrrk.......',
    '.krrRRRwwwwRRRrrk.......',
    '.krRRwwWWWWwwRRrk.......',
    '.krRRwwWWWWwwRRrk.......',
    '.krrRRRwwwwRRRrrk.......',
    '.krrrRRRRRRRRrrrk.......',
    '.krrrrrrrrrrrrrrk.......',
    '.kkrrrrrrrrrrrrkk.......',
    '..kkrrrrrrrrrrkk........',
    '....kkkkkkkkkk..........',
    '....kkrrrrrrrrrrrrrrrkk.',
    '...krrrrkkkkkkkkkkrrrrk.',
    '...kkkkk..........kkkkk.',
    '........................',
    '....KKKKKKKKKKKKKKKKKK..',
  ], [
    '..................kkk...',
    '.................krrk...',
    '................krrk....',
    '..............kkrrk.....',
    '.............krrrrk.....',
    '.............krrkkk.....',
    '....kkkkkk...krrk.......',
    '..kkrrrrrrkkkrrk........',
    '.krrrrrrrrrrrrrrk.......',
    '.krrrRRRRRRRRrrrk.......',
    '.krrRRRRRRRRRRRrk.......',
    '.krRRRwwwwwwwwRRk.......',
    '.krRRwwWWWWWWwwRk.......',
    '.krrRRRwwwwwwRRrk.......',
    '.krrrRRRRRRRRrrrk.......',
    '.krrrrrrrrrrrrrrk.......',
    '.kkrrrrrrrrrrrrkk.......',
    '..kkrrrrrrrrrrkk........',
    '....kkkkkkkkkk..........',
    '....kkrrrrrrrrrrrrrrrkk.',
    '...krrrrkkkkkkkkkkrrrrk.',
    '...kkkkk..........kkkkk.',
    '........................',
    '....KKKKKKKKKKKKKKKKKK..',
  ]]),
  // BSS-023 Head of Facilities — "Manipulates water, power, doors, and movable objects while
  // remaining physically vulnerable." The one boss whose sprite is mostly not the boss: the
  // mass is a wall panel of valves, breakers and gauges, and the actual killable body is a
  // small hi-vis worker standing under it. The panel is where the attacks come from; the
  // little figure in the middle is where the damage goes. Gauges flicker between frames.
  boss('head_of_facilities', 'A small hi-vis operator dwarfed by a wall panel of valves, breakers and gauges.', [[
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkkkkGGGGGGGGGGkkkkkGk.',
    '.kkcccckGGGGGGGGkcccckk.',
    '.kkcCCckGGwwGGGGkcCCckk.',
    '.kkcccckGGGGGGGGkcccckk.',
    '.kkkkkGGGGGGGGGGkkkkkGk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkYYkkYYkkYYkkYYkkYYkk.',
    '.kkbbkkbbkkbbkkbbkkbbkk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '...kbbkKKKKKKKKKKkbbk...',
    '...kbbk..kOOk....kbbk...',
    '...kbbk.kOOOOk...kbbk...',
    '...kbbk..kSSk....kbbk...',
    '...kbbk..kEEk....kbbk...',
    '...kkk..kEEEEk...kkk....',
    '........kEwwEk..........',
    '........kEEEEk..........',
    '........kgggggk.........',
    '........kgg.ggk.........',
    '........KKK.KKK.........',
  ], [
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkkkkGGGGGGGGGGkkkkkGk.',
    '.kkcccckGGGGGGGGkcccckk.',
    '.kkcCCckGGGGwwGGkcCCckk.',
    '.kkcccckGGGGGGGGkcccckk.',
    '.kkkkkGGGGGGGGGGkkkkkGk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkyykkyykkyykkyykkyykk.',
    '.kkBBkkBBkkBBkkBBkkBBkk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '...kBBkKKKKKKKKKKkBBk...',
    '...kBBk..kOOk....kBBk...',
    '...kBBk.kOOOOk...kBBk...',
    '...kBBk..kSSk....kBBk...',
    '...kBBk..kEEk....kBBk...',
    '...kkk..kEEEEk...kkk....',
    '........kEwwEk..........',
    '........kEEEEk..........',
    '........kgggggk.........',
    '........kgg.ggk.........',
    '........KKK.KKK.........',
  ]]),

  // BSS-024 Prototype Zero — "Cycles through a curated sequence of experimental weapon and
  // room-rule modules." It is unfinished lab equipment, still bolted to its test rig: a core
  // suspended inside a gimbal ring, with one module pod welded onto the ring's left side that
  // clearly was not part of the design. The core relights every frame — that is the cycle.
  boss('prototype_zero', 'A glowing core suspended in a gimbal ring on a test rig, one module pod bolted on crooked.', [[
    '...........kk...........',
    '..........kTTk..........',
    '..........kTTk..........',
    '.......kkkkkkkkkk.......',
    '.......kGGGGGGGGk.......',
    '.......kkkGGGGkkk.......',
    '.....kkkkkkkkkkkkkk.....',
    'kOkkkttttttttttttttkk...',
    'kOkttkkkkkkkkkkkkkkttk..',
    'kkkttk..kkkkkkkk..kttk..',
    '..kttk..kGGGGGGk..kttk..',
    '..kttk..kGCCCCGk..kttk..',
    '..kttk..kCWWWWCk..kttk..',
    '..kttk..kCWWWWCk..kttk..',
    '..kttk..kGCCCCGk..kttk..',
    '..kttk..kGGGGGGk..kttk..',
    '..kttk..kkkkkkkk..kttk..',
    '..kttkkkkkkkkkkkkkkttk..',
    '...kkttttttttttttttkk...',
    '.....kkkkkkkkkkkkkk.....',
    '.....kkk........kkk.....',
    '.....kGk........kGk.....',
    '....kkkkk......kkkkk....',
    '....KKKKK......KKKKK....',
  ], [
    '...........kk...........',
    '..........kTTk..........',
    '..........kTTk..........',
    '.......kkkkkkkkkk.......',
    '.......kGGGGGGGGk.......',
    '.......kkkGGGGkkk.......',
    '.....kkkkkkkkkkkkkk.....',
    'kOkkkTTTTTTTTTTTTTTkk...',
    'kOkttkkkkkkkkkkkkkkttk..',
    'kkkttk..kkkkkkkk..kttk..',
    '..kttk..kGGGGGGk..kttk..',
    '..kttk..kGCWWCGk..kttk..',
    '..kttk..kCWCCWCk..kttk..',
    '..kttk..kCWCCWCk..kttk..',
    '..kttk..kGCWWCGk..kttk..',
    '..kttk..kGGGGGGk..kttk..',
    '..kttk..kkkkkkkk..kttk..',
    '..kttkkkkkkkkkkkkkkttk..',
    '...kkTTTTTTTTTTTTTTkk...',
    '.....kkkkkkkkkkkkkk.....',
    '.....kkk........kkk.....',
    '.....kGk........kGk.....',
    '....kkkkk......kkkkk....',
    '....KKKKK......KKKKK....',
  ]]),

  // BSS-025 The Board — "A coordinated multi-entity boss whose votes select pattern families
  // and rewrite arena priorities." Deliberately NOT the Budget Committee: that one is three
  // heads on a solid bench, this one is five members ringed around a hollow white table, so
  // the negative space in the middle is the tell. The violet marker on the table is the vote,
  // and it moves between frames. HEAD_ROTATION is why the members face inward.
  boss('the_board', 'Five seated members ringed around a hollow white table, with a vote marker on it.', [[
    '...kkk....kkkk....kkk...',
    '..kGGGk..kGGGGk..kGGGk..',
    '..kSSSk..kSSSSk..kSSSk..',
    '..kSnSk..kSnnSk..kSoSk..',
    '..kkSkk..kkSSkk..kkSkk..',
    '..kGGGk..kGGGGk..kGGGk..',
    '.kkGGGkkkkGGGGkkkkGGGkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kGGkkkkkkkkkkkkkkkkGGk.',
    '.kGGk..............kGGk.',
    'kkGGk...kkkkkkkk...kGGkk',
    'kSSSk...kWWWWWWk...kSSSk',
    'kSnSk...kWvvvvWk...kSoSk',
    'kkSkk...kWvvvvWk...kkSkk',
    'kGGGk...kWWWWWWk...kGGGk',
    'kGGGk...kkkkkkkk...kGGGk',
    'kkGGkkkkkkkkkkkkkkkkGGkk',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kggggggggggggggggggggk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..kk..kk..kk..kk..kk....',
    '..kk..kk..kk..kk..kk....',
    '..kk..kk..kk..kk..kk....',
    '..KK..KK..KK..KK..KK....',
  ], [
    '...kkk....kkkk....kkk...',
    '..kGGGk..kGGGGk..kGGGk..',
    '..kSSSk..kSSSSk..kSSSk..',
    '..kSoSk..kSNNSk..kSnSk..',
    '..kkSkk..kkSSkk..kkSkk..',
    '..kGGGk..kGGGGk..kGGGk..',
    '.kkGGGkkkkGGGGkkkkGGGkk.',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kGGkkkkkkkkkkkkkkkkGGk.',
    '.kGGk..............kGGk.',
    'kkGGk...kkkkkkkk...kGGkk',
    'kSSSk...kWvvvvWk...kSSSk',
    'kSnSk...kWWvvWWk...kSoSk',
    'kkSkk...kWWWWWWk...kkSkk',
    'kGGGk...kWWWWWWk...kGGGk',
    'kGGGk...kkkkkkkk...kGGGk',
    'kkGGkkkkkkkkkkkkkkkkGGkk',
    '.kGGGGGGGGGGGGGGGGGGGGk.',
    '.kggggggggggggggggggggk.',
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    '..kk..kk..kk..kk..kk....',
    '..kk..kk..kk..kk..kk....',
    '..kk..kk..kk..kk..kk....',
    '..KK..KK..KK..KK..KK....',
  ]]),

  // BSS-026 Hostile Takeover — "Aggressive merger entity absorbs adds and inherits one attack
  // from each." ABSORB_ADDS needs a visible mouth and visible victims, so it has both: a maw
  // fifteen pixels wide at the front, and two faces already inside the mass, still looking
  // out. Lopsided on purpose — the highlight and the flank thicknesses do not match, because
  // this thing grew by eating rather than by being designed.
  boss('hostile_takeover', 'A lopsided purple mass with absorbed faces trapped inside it and a wide open maw.', [[
    '........................',
    '..........kkkk..........',
    '.........kmMMmk.........',
    '........kmMwwMmk........',
    '........kmMMMMmk........',
    '.......kkmMMMMmkk.......',
    '....kkkmmMMMMMMmmkkk....',
    '..kkmmmmMMMMMMMMmmmmkk..',
    '.kmmmmmmMMMMMMMMmmmmmmk.',
    '.kmmmmmmmMMMMMMmmmmmmmk.',
    'kmmmmkSSkmmmmmmkkSSkmmmk',
    'kmmmmkddkmmmmmmkkddkmmmk',
    'kmmmmkkkkmmmmmmkkkkmmmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmmMMMMMMmmmmmmmmMMMMMmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmmkkkkkkkkkkkkkkkkkmmmk',
    'kmmkRRRRRRRRRRRRRRRkmmmk',
    'kmmkRkRkRkRkRkRkRkRkmmmk',
    'kmmkRRRRRRRRRRRRRRRkmmmk',
    'kmmkkkkkkkkkkkkkkkkkmmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ], [
    '........................',
    '..........kkkk..........',
    '.........kmMMmk.........',
    '........kmMwwMmk........',
    '........kmMMMMmk........',
    '.......kkmMMMMmkk.......',
    '....kkkmmMMMMMMmmkkk....',
    '..kkmmmmMMMMMMMMmmmmkk..',
    '.kmmmmmmmMMMMMMmmmmmmmk.',
    '.kmmmmmmmmMMMMmmmmmmmmk.',
    'kmmmmkddkmmmmmmkkddkmmmk',
    'kmmmmkSSkmmmmmmkkSSkmmmk',
    'kmmmmkkkkmmmmmmkkkkmmmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmMMMMMMMmmmmmmmmMMMMmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kmmkkkkkkkkkkkkkkkkkmmmk',
    'kmmkRRRRRRRRRRRRRRRkmmmk',
    'kmmkkRkRkRkRkRkRkRkkmmmk',
    'kmmkRRRRRRRRRRRRRRRkmmmk',
    'kmmkkkkkkkkkkkkkkkkkmmmk',
    'kmmmmmmmmmmmmmmmmmmmmmmk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ]]),
  // BSS-027 Parent Company — "Reconstructs sanitized versions of earlier bosses and erases its
  // own branding between phases." So it is not a creature: it is a blank white slab, the only
  // object in the roster with no face and no limbs at all. The grey rectangle low on its front
  // is where a logo used to be. The pale grey shape floating inside it is the reconstruction,
  // and it is a DIFFERENT shape in each frame — the sprite is already quoting other bosses.
  boss('parent_company', 'A blank white slab with an erased brand patch and a pale ghost of another boss inside it.', [[
    '....kkkkkkkkkkkkkkkk....',
    '...kwwwwwwwwwwwwwwwwk...',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwkkkkkkkkkkwwwwwk..',
    '..kwwwkhhhhhhhhkwwwwwk..',
    '..kwwwkhWWWWWWhkwwwwwk..',
    '..kwwwkhWhhhhWhkwwwwwk..',
    '..kwwwkhWhWWhWhkwwwwwk..',
    '..kwwwkhWhhhhWhkwwwwwk..',
    '..kwwwkhWWWWWWhkwwwwwk..',
    '..kwwwkhhhhhhhhkwwwwwk..',
    '..kwwwkkkkkkkkkkwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwkkkkkkkwwk..',
    '..kwwwwwwwwwkGGGGGkwwk..',
    '..kwwwwwwwwwkGgggGkwwk..',
    '..kwwwwwwwwwkGGGGGkwwk..',
    '..kwwwwwwwwwkkkkkkkwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...KKKKKKKKKKKKKKKKKK...',
  ], [
    '....kkkkkkkkkkkkkkkk....',
    '...kwwwwwwwwwwwwwwwwk...',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwkkkkkkkkkkwwwwwk..',
    '..kwwwkhhhhhhhhkwwwwwk..',
    '..kwwwkhhhWWhhhkwwwwwk..',
    '..kwwwkhhWWWWhhkwwwwwk..',
    '..kwwwkhWWhhWWhkwwwwwk..',
    '..kwwwkhWhhhhWhkwwwwwk..',
    '..kwwwkhhhhhhhhkwwwwwk..',
    '..kwwwkhhhhhhhhkwwwwwk..',
    '..kwwwkkkkkkkkkkwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kwwwwwwwwwkkkkkkkwwk..',
    '..kwwwwwwwwwkGGGGGkwwk..',
    '..kwwwwwwwwwkGGGGGkwwk..',
    '..kwwwwwwwwwkGGGGGkwwk..',
    '..kwwwwwwwwwkkkkkkkwwk..',
    '..kwwwwwwwwwwwwwwwwwwk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '...KKKKKKKKKKKKKKKKKK...',
  ]]),

  // BSS-028 The Conglomerate — "Massive composite boss using carefully sequenced
  // cross-department mechanics and arena transformations." The GDD's promise that corporate
  // structure becomes architectural, taken literally: this boss is a building. Three towers of
  // three different heights, so the skyline itself is the silhouette, and its MODULE_CYCLE
  // divisions are readable as which floors are lit. The gold lobby band is its crown.
  boss('the_conglomerate', 'A skyline: three towers of different heights standing on one gold lobby band.', [[
    '..........kkk...........',
    '..........kGk...........',
    '.........kkkkkk.........',
    '.........kGGGGk.........',
    '.........kGwwGk.........',
    '.........kGGGGk.........',
    '..kkkkkkkkGwwGk.........',
    '..kGGGGGkkGGGGk.........',
    '..kGwwwGkkGwwGkkkkkkkk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '.kAAAAAAAAAAAAAAAAAAAAk.',
    '.kAqqAAqqAAqqAAqqAAqqAk.',
    'kHHHHHHHHHHHHHHHHHHHHHHk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ], [
    '..........kkk...........',
    '..........kGk...........',
    '.........kkkkkk.........',
    '.........kGGGGk.........',
    '.........kGGGGk.........',
    '.........kGwwGk.........',
    '..kkkkkkkkGGGGk.........',
    '..kGwwwGkkGwwGk.........',
    '..kGGGGGkkGGGGkkkkkkkk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGwwGkkHwwwHk..',
    '..kGGGGGkkGGGGkkHHHHHk..',
    '..kGwwwGkkGGGGkkHwwwHk..',
    '..kkkkkkkkkkkkkkkkkkkk..',
    '.kAqqAAqqAAqqAAqqAAqqAk.',
    '.kAAAAAAAAAAAAAAAAAAAAk.',
    'kHHHHHHHHHHHHHHHHHHHHHHk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.KKKKKKKKKKKKKKKKKKKKKK.',
  ]]),

  // BSS-029 The Beneficial Owner — "Minimalist final duel that echoes selected mechanics from
  // the current run, then removes layers until only movement and core weapon skill remain."
  //
  // This is the emptiest sprite in the game, and that is the whole design. Its phase data
  // really does shrink as its health drops — fewer patterns, not more — so a busy final boss
  // would be a lie told by the art. Thirteen sprites above this one spend their entire budget
  // on mass, internal detail and crowns; this one spends almost none: a hairline stroke, one
  // hollow ring, and negative space. There is nothing to read except where it is, which by
  // then is the only thing left to read. The whole shape rises and falls a pixel — the single
  // quietest idle here, against the loudest roster in the file.
  boss('the_beneficial_owner', 'A single hairline stroke beneath one hollow white ring; almost entirely negative space.', [[
    '........................',
    '........................',
    '.........kkkkk..........',
    '........kWWWWWk.........',
    '........kWW.WWk.........',
    '........kWWWWWk.........',
    '.........kkkkk..........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '.........kWWWk..........',
    '.........kkkkk..........',
    '..........KKK...........',
  ], [
    '........................',
    '........................',
    '........................',
    '.........kkkkk..........',
    '........kWWWWWk.........',
    '........kWW.WWk.........',
    '........kWWWWWk.........',
    '.........kkkkk..........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '..........kWk...........',
    '.........kWWWk..........',
    '.........kkkkk..........',
    '..........KKK...........',
  ]]),
];

export default late;
