/**
 * Sprite domain: non-passive collectibles. Owns the `active_`, `card_`, `sup_`,
 * `charm_`, and `trn_` id prefixes.
 *
 * GDD refs: 18.2 (32px reference grid), R-ART-001 (readable at native gameplay
 *           scale), R-ART-002 / R-ITM-002 (a unique sprite per collectible),
 *           9.7 / R-CON-003 (a Supplement sprite is the EFFECT icon, never the
 *           wrapper — wrappers are assigned per run and must not be predictable
 *           from content data), 8.7 (catalogue presentation).
 *
 * Split out of items.js because that file already carries the sixty passives, and
 * because these five classes read differently on the floor: a card is a flat rectangle,
 * a Supplement is a blister or capsule, a charm is small, an active is an object with
 * a button. Keeping them together here makes those family silhouettes easy to compare.
 *
 * Family rules, in silhouette terms:
 *   active_  a real object, roughly filling the grid, with a visible button/lever/handle.
 *   card_    every one shares the SAME portrait card outline (rows 2-14, cols 4-12);
 *            only the face glyph changes, so an Action Card reads as "a card" first.
 *   sup_     small centred capsules, tablets and blisters. The sprite is the EFFECT,
 *            drawn only after identification; the four up/down pairs mirror each other
 *            in shape as well as in colour so they survive grayscale.
 *   charm_   trinkets, kept inside the middle 10x10 so the class reads as "small thing".
 *   trn_     the most elaborate of the five; rare milestones, free to fill the grid.
 */

const SCALE = 2;

const spr = (id, silhouette, grid) => ({
  id,
  anchor: [0.5, 0.75],
  scale: SCALE,
  silhouette,
  frames: [grid],
});

const active = (slug, silhouette, grid) => spr(`active_${slug}`, silhouette, grid);

// -- 15 actives: objects with a button, lever or handle -----------------------

const actives = [
  active('task_manager', 'A window with a title bar, a red X and ragged list rows.', [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kGGGGGGGGGkrRk.',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kwkkkkkwwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwkkkkkkkwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwkkkkkwwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwGGGGkwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKK..',
    '................',
  ]),

  active('print_screen', 'A tall keycap whose face carries a pale-blue screen.', [
    '................',
    '................',
    '.kkkkkkkkkkkkk..',
    '.kHHHHHHHHHHHk..',
    '.kHwwwwwwwwwHk..',
    '.kHwkkkkkkkwHk..',
    '.kHwkCCCCCkwHk..',
    '.kHwkCCCCCkwHk..',
    '.kHwkkkkkkkwHk..',
    '.kHwwwkkkwwwHk..',
    '.kHHHHHHHHHHHk..',
    '.kGGGGGGGGGGGk..',
    '.kGGGGGGGGGGGk..',
    '.kkkkkkkkkkkkk..',
    '..KKKKKKKKKKK...',
    '................',
  ]),

  active('ctrl_z', 'A narrow keycap with a blue undo arrow curling back on itself.', [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kHHHHHHHHHHk..',
    '..kHwwwwwwwwHk..',
    '..kHwbbwwwwwHk..',
    '..kHbbbbbbwwHk..',
    '..kHwbbwwbbwHk..',
    '..kHwwwwwwbbHk..',
    '..kHwwwwwbbwHk..',
    '..kHwbbbbbwwHk..',
    '..kHwwwwwwwwHk..',
    '..kGGGGGGGGGGk..',
    '..kkkkkkkkkkkk..',
    '...KKKKKKKKKK...',
    '................',
  ]),

  active('out_of_office', 'A tall door hanger punched with a hole and banded in red.', [
    '................',
    '....kkkkkkkk....',
    '....kHHHHHHk....',
    '....kHkkkkHk....',
    '....kHk..kHk....',
    '....kHkkkkHk....',
    '....kHHHHHHk....',
    '....krrrrrrk....',
    '....krwwwwrk....',
    '....krrrrrrk....',
    '....kwkkkkwk....',
    '....kwwwwwwk....',
    '....kwkkwwwk....',
    '....kwwwwwwk....',
    '....kkkkkkkk....',
    '.....KKKKKK.....',
  ]),

  active('emergency_coffee_pot', 'A carafe with a side handle, red lid and a brown fill line.', [
    '................',
    '...kkkkkkkk.....',
    '...kRRRRRRk.....',
    '...kkkkkkkk.....',
    '..kwwwwwwk......',
    '..kwwwwwwkkkk...',
    '..kwwwwwwkkHk...',
    '..kwwwwwwkkHk...',
    '..kooooookkHk...',
    '..kooooookkHk...',
    '..kooooookkkk...',
    '..kooooook......',
    '..kooooook......',
    '..kkkkkkkk......',
    '...KKKKKK.......',
    '................',
  ]),

  active('meeting_invite', 'An envelope whose flap folds to a V, with a clock face on it.', [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwkkwwwwwwkkwk.',
    '.kwwkkwwwwkkwwk.',
    '.kwwwkkwwkkwwwk.',
    '.kwwwwkkkkwwwwk.',
    '.kwkkkwwwwwwwwk.',
    '.kkwwwkwwwwwwwk.',
    '.kkwkwkwwwwwwwk.',
    '.kkwwwkwwwwwwwk.',
    '.kwkkkwwwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKK..',
    '................',
  ]),

  active('power_cycle', 'A square switch plate carrying a green power ring and bar.', [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '...kHHHHHHHHk...',
    '...kHwwwwwwHk...',
    '...kHwwEEwwHk...',
    '...kHEEwwEEHk...',
    '...kHEwwwwEHk...',
    '...kHEwwwwEHk...',
    '...kHEEwwEEHk...',
    '...kHwEEEEwHk...',
    '...kHwwwwwwHk...',
    '...kHHHHHHHHk...',
    '...kkkkkkkkkk...',
    '....KKKKKKKK....',
    '................',
  ]),

  active('shredder_bin', 'A slotted lid over a tapering bin, paper strips rising out.', [
    '...w..w..w......',
    '...w..w..w......',
    '..ww..w..ww.....',
    '..kkkkkkkkkkkk..',
    '..kGkkGkkGkkGk..',
    '..kkkkkkkkkkkk..',
    '...kGGGGGGGGk...',
    '...kGhhhhhhGk...',
    '...kGhhhhhhGk...',
    '...kGhhhhhhGk...',
    '...kGhhhhhhGk...',
    '....kGhhhhGk....',
    '....kGhhhhGk....',
    '....kGGGGGGk....',
    '....kkkkkkkk....',
    '.....KKKKKK.....',
  ]),

  active('fire_extinguisher', 'A red cylinder with a top handle, gauge nub and a hose curling right.', [
    '................',
    '.....kkk........',
    '.....kGkkHk.....',
    '...kkkkkkk......',
    '...krrrrrkkkkk..',
    '...krRRRrk...kk.',
    '...krRRRrk...kk.',
    '...krRRRrk..kk..',
    '...krrrrrk......',
    '...kwwwwwk......',
    '...kwkkkwk......',
    '...krrrrrk......',
    '...krRRRrk......',
    '...krrrrrk......',
    '...kkkkkkk......',
    '....KKKKK.......',
  ]),

  active('red_phone', 'A red handset lying across a wide cradle with a dark keypad.', [
    '................',
    '................',
    '..kkkk....kkkk..',
    '..krrk....krrk..',
    '..krrrrrrrrrrk..',
    '...kkkkkkkkkk...',
    '................',
    '....kkkkkkkk....',
    '...krrrrrrrrk...',
    '..krrkkkkkkrrk..',
    '..krrkkkkkkrrk..',
    '..krrrrrrrrrrk..',
    '.krrrrrrrrrrrrk.',
    '.kRRRRRRRRRRRRk.',
    '.kkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKK..',
  ]),

  active('expense_report', 'Stacked pages offset behind one another, closed by a gold total bar.', [
    '................',
    '....kkkkkkkkkkk.',
    '....kwwwwwwwwwk.',
    '.kkkkkkkkkkkwwk.',
    '.kwwwwwwwwwkwwk.',
    '.kwkkkkkwwwkwwk.',
    '.kwkkkkkkkwkwwk.',
    '.kwwwwwwwwwkwwk.',
    '.kwkkkkkwwwkwwk.',
    '.kwkkkkkkkwkwwk.',
    '.kwwwwwwwwwkwwk.',
    '.kwkkkkkwwwkwwk.',
    '.kwwwwwwwwwkkkk.',
    '.kkkkkAAAAwk....',
    '.kkkkkkkkkkk....',
    '..KKKKKKKKK.....',
  ]),

  active('copier_jam', 'Crumpled paper erupting in a jagged plume from a machine slot.', [
    '................',
    '.....kwk........',
    '....kwwwk.......',
    '...kwwwwwkk.....',
    '..kwwkwwwwwk....',
    '..kwwwwkwwwk....',
    '.kwwwwwwwkwwk...',
    '.kwwwwwwwwwwk...',
    '.kkwwwwwwwwkk...',
    '.kkkkkkkkkkkkkk.',
    '.kGGkkkkkkkkGGk.',
    '.kGGGGGGGGGGGGk.',
    '.kGyGGGGGGGGGGk.',
    '.kGGGGGGGGGGGGk.',
    '.kkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKK..',
  ]),

  active('floor_plan', 'A blue sheet folded into two offset panels of room outlines.', [
    '................',
    '................',
    '.kkkkkkkkk......',
    '.kbbbbbbbkkkkkk.',
    '.kbwwwwwbkbbbbk.',
    '.kbwbbbwbkbwwbk.',
    '.kbwwwwwbkbwwbk.',
    '.kbbbbbbbkbbbbk.',
    '.kbwwwwwbkbwwbk.',
    '.kbwbwwwbkbwbbk.',
    '.kbwwwwwbkbwwbk.',
    '.kbbbbbbbkbbbbk.',
    '.kkkkkkkkkbwwbk.',
    '.........kkkkkk.',
    '..........KKKK..',
    '................',
  ]),

  active('performance_improvement_plan', 'A clipboard with a clip on top and a red line stepping downward.', [
    '................',
    '......kkkk......',
    '.....kGGGGk.....',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwwk..',
    '..kkwwwwwwwwwk..',
    '..kkRwwwwwwwwk..',
    '..kkwRRwwwwwwk..',
    '..kkwwwRRwwwwk..',
    '..kkwwwwwRRwwk..',
    '..kkwwwwwwwRRk..',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    '...KKKKKKKKKK...',
    '................',
  ]),

  active('desk_bell', 'A gold dome on a flat base with a plunger stem on top.', [
    '................',
    '.......kk.......',
    '......kAAk......',
    '......kAAk......',
    '....kkkkkkkk....',
    '..kkAAAAAAAAkk..',
    '.kAAAAqqAAAAAAk.',
    '.kAAAqqAAAAAAAk.',
    'kAAAAAAAAAAAAAAk',
    'kAAAAAAAAAAAAAAk',
    'kkkkkkkkkkkkkkkk',
    '.kaaaaaaaaaaaak.',
    '.kkkkkkkkkkkkkk.',
    '..KKKKKKKKKKKK..',
    '................',
    '................',
  ]),
];

// -- 18 cards: one shared outline, eighteen faces ----------------------------
//
// Every card is the same portrait rectangle (rows 2-14, cols 4-12) so the class
// reads before the individual. `face` is the 11x7 interior; only it may vary.

const card = (slug, silhouette, face) => spr(`card_${slug}`, silhouette, [
  '................',
  '................',
  '....kkkkkkkkk...',
  ...face.map((row) => `....k${row}k...`),
  '....kkkkkkkkk...',
  '.....KKKKKKK....',
]);

const cards = [
  card('meeting_canceled', 'Card face: a tabbed calendar block struck through by a red X.', [
    'wwwwwww',
    'wkwwwkw',
    'kkkkkkk',
    'kGGGGGk',
    'kkkkkkk',
    'kRwwwRk',
    'kwRwRwk',
    'kwwRwwk',
    'kwRwRwk',
    'kRwwwRk',
    'kkkkkkk',
  ]),

  card('company_wide_email', 'Card face: an envelope with short rays above and below it.', [
    'wwwwwww',
    'kwwwwwk',
    'wkwwwkw',
    'kkkkkkk',
    'kwbbbwk',
    'kbwbwbk',
    'kbbwbbk',
    'kbbbbbk',
    'kkkkkkk',
    'wkwwwkw',
    'kwwwwwk',
  ]),

  card('sick_day', 'Card face: an upright thermometer with a fat red bulb.', [
    'wwkkkww',
    'wkHHHkw',
    'wkHrHkw',
    'wkHrHkw',
    'wkHrHkw',
    'wkHrHkw',
    'wkrrrkw',
    'kkrrrkk',
    'krrrrrk',
    'krrrrrk',
    'wkkkkkw',
  ]),

  card('approved_overtime', 'Card face: a clock with a green arrowhead climbing below it.', [
    'wwkkkww',
    'wkwwwkw',
    'kwwkwwk',
    'kwwkwwk',
    'kwwkkwk',
    'kwwwwwk',
    'wkwwwkw',
    'wwkkkww',
    'wwwEwww',
    'wwEEEww',
    'wEEwEEw',
  ]),

  card('expense_approved', 'Card face: a gold coin with a green tick to its lower right.', [
    'wwkkkww',
    'wkAAAkw',
    'kAAAAAk',
    'kAAqAAk',
    'kAqqqAk',
    'kAAAAAk',
    'wkAAAkw',
    'wwkkkww',
    'wwwwwEE',
    'wEwwEEw',
    'wwEEEww',
  ]),

  card('budget_freeze', 'Card face: a six-armed snowflake, all spokes and no mass.', [
    'wwwwwww',
    'wwwbwww',
    'wbwbwbw',
    'wwbbbww',
    'bwwbwwb',
    'bbbbbbb',
    'bwwbwwb',
    'wwbbbww',
    'wbwbwbw',
    'wwwbwww',
    'wwwwwww',
  ]),

  card('reorganization', 'Card face: two violet arrows chasing each other in a loop.', [
    'wwwwwww',
    'wvvvvvw',
    'vvwwwwv',
    'wwwwwwv',
    'wwwwwwv',
    'vwwwwwv',
    'vwwwwww',
    'vwwwwvv',
    'wvvvvvw',
    'wwwwwww',
    'wwwwwww',
  ]),

  card('calendar_block', 'Card face: the same calendar block, filled solid purple.', [
    'wwwwwww',
    'wkwwwkw',
    'kkkkkkk',
    'kGGGGGk',
    'kkkkkkk',
    'kmmmmmk',
    'kmmmmmk',
    'kmmmmmk',
    'kmmmmmk',
    'kkkkkkk',
    'wwwwwww',
  ]),

  card('access_granted', 'Card face: a padlock whose shackle stands open on one side.', [
    'wwwkkkw',
    'wwkwwkw',
    'wwkwwww',
    'wwkwwww',
    'kkkkkkk',
    'kAAAAAk',
    'kAAkAAk',
    'kAAkAAk',
    'kAAAAAk',
    'kkkkkkk',
    'wwwwwww',
  ]),

  card('all_hands', 'Card face: three identical stick figures shoulder to shoulder.', [
    'wwwwwww',
    'wkwkwkw',
    'wkwkwkw',
    'kkkkkkk',
    'kbkbkbk',
    'kbkbkbk',
    'kbkbkbk',
    'kkkkkkk',
    'wwwwwww',
    'wwwwwww',
    'wwwwwww',
  ]),

  card('performance_review', 'Card face: an open eye staring down at three rising bars.', [
    'wwwwwww',
    'wwkkkww',
    'wkCCCkw',
    'kCkkkCk',
    'wkCCCkw',
    'wwkkkww',
    'wwwwwww',
    'wwwwwGw',
    'wwwGwGw',
    'wGwGwGw',
    'kkkkkkk',
  ]),

  card('remote_day', 'Card face: a gabled house under two wifi arcs.', [
    'wwCCCww',
    'wCwwwCw',
    'wwwwwww',
    'wwwkwww',
    'wwkkkww',
    'wkkkkkw',
    'kkkkkkk',
    'kEEkEEk',
    'kEEkEEk',
    'kkkkkkk',
    'wwwwwww',
  ]),

  card('hard_deadline', 'Card face: an hourglass pinched to a single pixel waist.', [
    'wwwwwww',
    'kkkkkkk',
    'kyyyyyk',
    'wkyyykw',
    'wwkykww',
    'wwwkwww',
    'wwkykww',
    'wkyyykw',
    'kyyyyyk',
    'kkkkkkk',
    'wwwwwww',
  ]),

  card('return_to_sender', 'Card face: an arrow hitting a solid wall and coming back.', [
    'wwwwwww',
    'wwwwRkk',
    'RRRRRkk',
    'wwwwRkk',
    'wwwwwkk',
    'wRwwwkk',
    'RRRRRkk',
    'wRwwwkk',
    'wwwwwkk',
    'wwwwwkk',
    'wwwwwww',
  ]),

  card('escalation', 'Card face: three stacked orange chevrons pointing up.', [
    'wwwwwww',
    'wwwOwww',
    'wwOOOww',
    'wOOwOOw',
    'wwwOwww',
    'wwOOOww',
    'wOOwOOw',
    'wwwOwww',
    'wwOOOww',
    'wOOwOOw',
    'wwwwwww',
  ]),

  card('meeting_minutes', 'Card face: a scroll, wide rolled ends over a narrow ruled sheet.', [
    'kkkkkkk',
    'kHHHHHk',
    'kkkkkkk',
    'wkwwwkw',
    'wkkkkkw',
    'wkwwwkw',
    'wkkkkkw',
    'wkwwwkw',
    'kkkkkkk',
    'kHHHHHk',
    'kkkkkkk',
  ]),

  card('desk_move', 'Card face: a desk shoved sideways, grey speed streaks trailing it.', [
    'wwwwwww',
    'wwwwwww',
    'wwkkkkk',
    'GGkoook',
    'wwkkkkk',
    'Gwkwwwk',
    'wwkwwwk',
    'GGkwwwk',
    'wwkwwwk',
    'wwwwwww',
    'wwwwwww',
  ]),

  card('quarter_end', 'Card face: four bars climbing left to right, red pennant on the last.', [
    'wwwwrre',
    'wwwwrre',
    'wwwwwwe',
    'wwwwwwe',
    'wwwwewe',
    'wwwwewe',
    'wwewewe',
    'wwewewe',
    'ewewewe',
    'kkkkkkk',
    'wwwwwww',
  ]),
];

// -- 14 supplements: the EFFECT, never the wrapper (GDD 9.7 / R-CON-003) -----
//
// The wrapper is rolled per run, so nothing here may hint at one. Each of the four
// up/down pairs is a true mirror: the mark that sits above the capsule on the
// positive half sits below it, inverted, on the negative half. Colour follows
// (E/e up, R/r down) but never carries the meaning on its own.

const sup = (slug, silhouette, grid) => spr(`sup_${slug}`, silhouette, grid);

const supplements = [
  sup('focus_up', 'A capsule with a chevron rising off the top of it.', [
    '................',
    '................',
    '.......EE.......',
    '......EEEE......',
    '.....EE..EE.....',
    '................',
    '....kkkkkkkk....',
    '..kkEEEEwwwwkk..',
    '.kEEEEEEwwwwwwk.',
    '.kEEEEEEwwwwwwk.',
    '..kkEEEEwwwwkk..',
    '....kkkkkkkk....',
    '....KKKKKKKK....',
    '................',
    '................',
    '................',
  ]),

  sup('focus_down', 'The focus capsule inverted: the chevron drops below it.', [
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkRRRRwwwwkk..',
    '.kRRRRRRwwwwwwk.',
    '.kRRRRRRwwwwwwk.',
    '..kkRRRRwwwwkk..',
    '....kkkkkkkk....',
    '................',
    '.....RR..RR.....',
    '......RRRR......',
    '.......RR.......',
    '................',
    '................',
    '................',
  ]),

  sup('energy_up', 'A capsule under a zigzag climbing left to right.', [
    '................',
    '................',
    '..........EEEE..',
    '........EE......',
    '......EEEE......',
    '....EE..........',
    '..EEEE..........',
    '................',
    '....kkkkkkkk....',
    '..kkEEEEwwwwkk..',
    '.kEEEEEEwwwwwwk.',
    '.kEEEEEEwwwwwwk.',
    '..kkEEEEwwwwkk..',
    '....kkkkkkkk....',
    '.....KKKKKK.....',
    '................',
  ]),

  sup('energy_crash', 'The energy zigzag mirrored: it falls away below the capsule.', [
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkRRRRwwwwkk..',
    '.kRRRRRRwwwwwwk.',
    '.kRRRRRRwwwwwwk.',
    '..kkRRRRwwwwkk..',
    '....kkkkkkkk....',
    '................',
    '..RRRR..........',
    '....RR..........',
    '......RRRR......',
    '........RR......',
    '..........RRRR..',
    '................',
    '................',
  ]),

  sup('heavy_dose', 'A fat upright capsule, seamed at the waist and banded with weight.', [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkvvvvvvkk...',
    '..kvvvvvvvvvvk..',
    '..kvvvvvvvvvvk..',
    '..kvvvvvvvvvvk..',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwwk..',
    '..kwggggggggwk..',
    '..kwwwwwwwwwwk..',
    '..kwggggggggwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '....KKKKKKKK....',
    '................',
  ]),

  sup('numb_hands', 'A grey capsule whose far end dissolves into hatching.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkGGGGkhkhkk..',
    '.kGGGGGGkhkhkhk.',
    '.kGGGGGGhkhkhkk.',
    '..kkGGGGhkhkkk..',
    '....kkkkkkkk....',
    '.....KKKKKK.....',
    '................',
    '................',
    '................',
    '................',
  ]),

  sup('clear_eyes', 'A round tablet stamped with a wide open eye.', [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwwwwwwwk..',
    '.kwwwkkkkkkwwwk.',
    '.kwkCCCCCCCCkwk.',
    '.kwkCCkkkkCCkwk.',
    '.kwkCCCCCCCCkwk.',
    '.kwwwkkkkkkwwwk.',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '....KKKKKKKK....',
    '................',
  ]),

  sup('dry_eyes', 'The same tablet, the eye pinched shut to a red slit.', [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwwwwwwwk..',
    '.kwwwwwwwwwwwwk.',
    '.kwwkkwwwwkkwwk.',
    '.kwkrrrrrrrrkwk.',
    '.kwwkkwwwwkkwwk.',
    '.kwwwwwwwwwwwwk.',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '....KKKKKKKK....',
    '................',
  ]),

  sup('full_recovery', 'A tall all-green capsule carrying a white cross.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkeeewweeekk..',
    '.keeeeewweeeeek.',
    '.keewwwwwwwweek.',
    '.keewwwwwwwweek.',
    '.keeeeewweeeeek.',
    '..kkeeewweeekk..',
    '....kkkkkkkk....',
    '.....KKKKKK.....',
    '................',
    '................',
  ]),

  sup('bad_reaction', 'A red capsule split by a pale crack, one end blotted out black.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '..kkrrrwrrrrkk..',
    '.krkkrrwrrrrrrk.',
    '.krkkkrwwrrrrrk.',
    '.krrkkrrwrrrrrk.',
    '..kkrrrwrrrrkk..',
    '....kkkkkkkk....',
    '.....KKKKKK.....',
    '................',
    '................',
    '................',
  ]),

  sup('telework', 'A small teal capsule with an arrow breaking away from it.', [
    '................',
    '................',
    '................',
    '...........TTTT.',
    '............TTT.',
    '..........TTT...',
    '.........TT.....',
    '..kkkkkkkk......',
    '.kttttwwwwk.....',
    '.kttttwwwwk.....',
    '.kttttwwwwk.....',
    '..kkkkkkkk......',
    '...KKKKKK.......',
    '................',
    '................',
    '................',
  ]),

  sup('adrenaline', 'An upright capsule with a yellow bolt zigzagging down it.', [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '....kwwwyywk....',
    '....kwwyywwk....',
    '....kwyywwwk....',
    '....kyyyyywk....',
    '....kwwyyyyk....',
    '....kwwwyywk....',
    '....kwwyywwk....',
    '....kwyywwwk....',
    '....kwwwwwwk....',
    '.....kkkkkk.....',
    '.....KKKKKK.....',
    '................',
  ]),

  sup('placebo', 'A small blank white tablet. No mark at all, which is the joke.', [
    '................',
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '.....KKKKKK.....',
    '................',
    '................',
    '................',
  ]),

  sup('mystery_snack', 'A sweet twisted shut at both ends, a question mark on the wrapper.', [
    '................',
    '................',
    '................',
    '................',
    '...kkkkkkkkkk...',
    '...kMMMMMMMMk...',
    '...kMMwwwwMMk...',
    'kMMkMwMMMMwMkMMk',
    'kMMkMMMMMwwMkMMk',
    'kMMkMMMMwwMMkMMk',
    '...kMMMwwMMMk...',
    '...kMMMMMMMMk...',
    '...kMMMwwMMMk...',
    '...kkkkkkkkkk...',
    '....KKKKKKKK....',
    '................',
  ]),
];

export default [...actives, ...cards, ...supplements];
