/**
 * Sprite domain: hazards.
 *
 * See content/sprites/index.js for the id-prefix ownership table and
 * src/render/sprites.js for the palette + grid DSL. This module owns the
 * `haz_` prefix and nothing else.
 *
 * GDD refs: 13.3 (the ENV objects that emit these), 18.1 (chunky silhouettes),
 *           18.5 (outline families), R-ART-001 (readable at native scale),
 *           R-ENV-002 (mechanical and decorative decals are visually distinct),
 *           R-UIX-005 (every colour cue has a non-colour cue).
 *
 * Authoring conventions used throughout — this is the R-ENV-002 vocabulary, and
 * it is deliberately shape-based so it survives a grayscale review:
 *
 * - **Thin single-dash border** (`.k..` repeat) = mechanical, costs tempo only.
 * - **Heavy double-dash border** (`kk..` repeat) = mechanical, costs health.
 * - **No border at all** = decorative decal. Nothing borderless ever deals damage
 *   or applies a status, so a player never has to test floor art.
 * - Interior hatch carries the family: diagonal streak = slippery, bubble =
 *   scalding, zigzag/tick = electrical, chevron = directional transport,
 *   stipple = sticky, angular specks = glass, motion streaks = displacement.
 * - Grids are authored at half resolution with `scale: 2`, so 16 grid columns is
 *   exactly one world unit (TILE = 32), matching content/sprites/objects.js.
 * - Every hazard is a floor decal and anchors at its centre (0.5, 0.5), so it
 *   draws below the entity plane and can never occlude a hostile silhouette.
 */

const hazardSprites = [
  // == ELECTRICITY ==========================================================
  {
    id: 'haz_elec_floor_arc',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Two fixed contact pads with a zigzag arc closing the gap between them.',
    frames: [[
      'kk..kk..kk..kk..',
      'k..............k',
      '..kkkk....kkkk..',
      '..kTTk....kTTk..',
      'k.kTTk....kTTk.k',
      '..kkkk....kkkk..',
      'k...TT......TT.k',
      '.....TT....TT...',
      'k......TTTT....k',
      '.....TT....TT...',
      'k...TT......TT.k',
      '..kkkk....kkkk..',
      '..kTTk....kTTk..',
      'k.kTTk....kTTk.k',
      '..kkkk....kkkk..',
      'kk..kk..kk..kk..',
    ]],
  },
  {
    id: 'haz_elec_shock_lane',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Two-tile lane with heavy dashed rails and a teal chevron hatch along it.',
    frames: [[
      'kk..kk..kk..kk..kk..kk..kk..kk..',
      'k..............................k',
      'TTkkTTkkTTkkTTkkTTkkTTkkTTkkTTkk',
      'kkTTkkTTkkTTkkTTkkTTkkTTkkTTkkTT',
      'TTkkTTkkTTkkTTkkTTkkTTkkTTkkTTkk',
      'kkTTkkTTkkTTkkTTkkTTkkTTkkTTkkTT',
      'TTkkTTkkTTkkTTkkTTkkTTkkTTkkTTkk',
      'kkTTkkTTkkTTkkTTkkTTkkTTkkTTkkTT',
      'TTkkTTkkTTkkTTkkTTkkTTkkTTkkTTkk',
      'kkTTkkTTkkTTkkTTkkTTkkTTkkTTkkTT',
      'TTkkTTkkTTkkTTkkTTkkTTkkTTkkTTkk',
      'kkTTkkTTkkTTkkTTkkTTkkTTkkTTkkTT',
      'TTkkTTkkTTkkTTkkTTkkTTkkTTkkTTkk',
      'k..............................k',
      'kk..kk..kk..kk..kk..kk..kk..kk..',
    ]],
  },
  {
    id: 'haz_elec_outlet_spark',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Decorative wall outlet with a borderless spark smudge; no floor plate.',
    frames: [[
      '............',
      '....kkkk....',
      '...kHHHHk...',
      '...kHkkHk...',
      '...kHkkHk...',
      '...kHHHHk...',
      '....kkkk....',
      '...T..T.....',
      '..T..T..T...',
      '...T...T....',
      '....T.......',
      '............',
    ]],
  },

  // == CABLES ===============================================================
  {
    id: 'haz_cable_trip_bundle',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Two floor strands in a thin single-dash border: slows, never damages.',
    frames: [[
      '.k...k...k...k...k...k...k...k..',
      '................................',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
      '.kGGGGGGGGGGGGGGGGGGGGGGGGGGGGk.',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
      '................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kggggggggggggggggggggggggggk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '................................',
      '.k...k...k...k...k...k...k...k..',
      '................................',
    ]],
  },
  {
    id: 'haz_cable_live_run',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Same strands, heavy double-dash border, travelling tick marks on each run.',
    frames: [[
      'kk..kk..kk..kk..kk..kk..kk..kk..',
      'k..............................k',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
      '.kGGTTGGTTGGTTGGTTGGTTGGTTGGTTk.',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
      '................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kTTggTTggTTggTTggTTggTTggTTk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      'k..............................k',
      'kk..kk..kk..kk..kk..kk..kk..kk..',
      '................................',
    ]],
  },
  {
    id: 'haz_cable_slack_coil',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Decorative zip-tied coil: borderless ring, compact shape, no hatch.',
    frames: [[
      '............',
      '...gggggg...',
      '..gg....gg..',
      '..g..gg..g..',
      '..g.g..g.g..',
      '..g.g..g.g..',
      '..g..gg..g..',
      '..gg....gg..',
      '...gggggg...',
      '............',
    ]],
  },

  // == MACHINE_STATES =======================================================
  {
    id: 'haz_machine_steam_vent',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Grille plate with a hard-edged plume that grows to full length as warning.',
    frames: [[
      'kk..kk..kk..kk..',
      'k..............k',
      '..kkkkkkkkkkkk..',
      '..kGkkkkkkkkGk..',
      '..kGkkkkkkkkGk..',
      '..kGkkkkkkkkGk..',
      '..kkkkkkkkkkkk..',
      'k..............k',
      '....wwwwwwww....',
      '...wwwwwwwwww...',
      '..wwwwwwwwwwww..',
      '...wwwwwwwwww...',
      '....wwwwwwww....',
      '.....wwwwww.....',
      'k..............k',
      'kk..kk..kk..kk..',
    ]],
  },
  {
    id: 'haz_machine_toner_cloud',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Dark stippled cloud with a hard dashed rim; shrinks as it dissipates.',
    frames: [[
      'kk..kk..kk..kk..kk..kk..',
      'k......................k',
      '.....KKKKKKKKKKKKKK.....',
      '...KKKKKKKKKKKKKKKKKK...',
      '..KKKgKKKgKKKgKKKgKKKK..',
      '.KKgKKKgKKKgKKKgKKKgKKK.',
      '.KKKgKKKgKKKgKKKgKKKgKK.',
      '.KKgKKKgKKKgKKKgKKKgKKK.',
      '.KKKgKKKgKKKgKKKgKKKgKK.',
      '.KKgKKKgKKKgKKKgKKKgKKK.',
      '..KKKgKKKgKKKgKKKgKKKK..',
      '...KKKKKKKKKKKKKKKKKK...',
      '.....KKKKKKKKKKKKKK.....',
      'k......................k',
      'kk..kk..kk..kk..kk..kk..',
    ]],
  },
  {
    id: 'haz_machine_stamp_press',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Bracketed anvil plate; a shrinking inset square is the impact countdown.',
    frames: [[
      'kk..kk..kk..kk..',
      'k..............k',
      '..kkkk....kkkk..',
      '..kg........gk..',
      '..kg........gk..',
      '...kkkkkkkkkk...',
      '...kGGGGGGGGk...',
      '...kGkkkkkkGk...',
      '...kGkKKKKkGk...',
      '...kGkKKKKkGk...',
      '...kGkkkkkkGk...',
      '...kGGGGGGGGk...',
      '...kkkkkkkkkk...',
      '..kg........gk..',
      '..kkkk....kkkk..',
      'kk..kk..kk..kk..',
    ]],
  },

  // == SPILLS ===============================================================
  {
    id: 'haz_spill_water_slick',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Thin dashed border with a dense diagonal streak hatch: slippery, not hot.',
    frames: [[
      '.k...k...k...k..',
      'k..CcCcCcCcCc..k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k..CcCcCcCcCc..k',
      '.k...k...k...k..',
      '................',
    ]],
  },
  {
    id: 'haz_spill_coffee_scald',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Heavy dashed border, bubble hatch, steam ticks along the top edge.',
    frames: [[
      '.....wwww.......',
      'kk..kk..kk..kk..',
      'k..............k',
      '..oOoOoOoOoOoO..',
      'k.OoOoOoOoOoOo.k',
      '..oOoOoOoOoOoO..',
      'k.OoOoOoOoOoOo.k',
      '..oOoOoOoOoOoO..',
      'k.OoOoOoOoOoOo.k',
      '..oOoOoOoOoOoO..',
      'k.OoOoOoOoOoOo.k',
      '..oOoOoOoOoOoO..',
      'k..............k',
      'kk..kk..kk..kk..',
    ]],
  },
  {
    id: 'haz_spill_dry_stain',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Decorative dried spill: borderless soft blob, no hatch, floor contrast.',
    frames: [[
      '................',
      '.....oooo.......',
      '...oooooooo.....',
      '..oooooooooo....',
      '..oooooooooooo..',
      '.oooooooooooooo.',
      '.oooooooooooooo.',
      '..oooooooooooo..',
      '...oooooooooo...',
      '....oooooo......',
      '......ooo.......',
      '................',
    ]],
  },

  // == CONVEYORS ============================================================
  {
    id: 'haz_conveyor_belt_run',
    scale: 2,
    anchor: [0.5, 0.5],
    frameDurations: [0.18, 0.18],
    silhouette: 'Recessed lane of chevron slats; the chevron point is the travel direction.',
    frames: [
      [
        '.k...k...k...k...k...k...k...k..',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.k...k...k...k...k...k...k...k..',
        '................................',
      ],
      [
        '.k...k...k...k...k...k...k...k..',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.k...k...k...k...k...k...k...k..',
        '................................',
      ],
    ],
  },
  {
    id: 'haz_conveyor_reversing_belt',
    scale: 2,
    anchor: [0.5, 0.5],
    frameDurations: [0.35, 0.7, 0.35],
    silhouette: 'Same slats, but chevrons collapse to flat bars for the reversal warning.',
    frames: [
      [
        '.k...k...k...k...k...k...k...k..',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.k...k...k...k...k...k...k...k..',
        '................................',
      ],
      [
        '.k...k...k...k...k...k...k...k..',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kGGGGkkkkGGGGkkkkGGGGkkkkGGGGk.',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.k...k...k...k...k...k...k...k..',
        '................................',
      ],
      [
        '.k...k...k...k...k...k...k...k..',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kGGkkGGkkGGkkGGkkGGkkGGkkGGkkk.',
        '.kkkGGkkGGkkGGkkGGkkGGkkGGkkGGk.',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '.k...k...k...k...k...k...k...k..',
        '................................',
      ],
    ],
  },
  {
    id: 'haz_conveyor_pinch_roller',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Two counter-rotating drums with a hard black bite line between them.',
    frames: [[
      'kk..kk..kk..kk..',
      'k..............k',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGkkkkkkkkGk..',
      '..kGkKKKKKKkGk..',
      '..kGkkkkkkkkGk..',
      '..kkkkkkkkkkkk..',
      '..kkkkkkkkkkkk..',
      '..kkkkkkkkkkkk..',
      '..kGkkkkkkkkGk..',
      '..kGkKKKKKKkGk..',
      '..kGkkkkkkkkGk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      'kk..kk..kk..kk..',
    ]],
  },

  // == SCANNERS =============================================================
  {
    id: 'haz_scanner_sweep_line',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Narrow travelling line with a dotted track painted along its whole path first.',
    frames: [[
      '................................',
      '.k...k...k...k...k...k...k...k..',
      '................................',
      '..........kkk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kTk...................',
      '..........kkk...................',
      '................................',
      '.k...k...k...k...k...k...k...k..',
      '................................',
    ]],
  },
  {
    id: 'haz_scanner_mark_pulse',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Concentric ring pulse from a floor plate; rings step outward so they can be counted.',
    frames: [[
      '.k...k...k...k..',
      '................',
      '...kkkkkkkkkk...',
      '..k..........k..',
      '..k.kkkkkkkk.k..',
      '..k.k......k.k..',
      '..k.k.kkkk.k.k..',
      '..k.k.kTTk.k.k..',
      '..k.k.kTTk.k.k..',
      '..k.k.kkkk.k.k..',
      '..k.k......k.k..',
      '..k.kkkkkkkk.k..',
      '..k..........k..',
      '...kkkkkkkkkk...',
      '................',
      '.k...k...k...k..',
    ]],
  },
  {
    id: 'haz_scanner_idle_reader',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Decorative dead badge reader: borderless, no floor plate, no dotted track.',
    frames: [[
      '..........',
      '...kkkk...',
      '..kGGGGk..',
      '..kGkkGk..',
      '..kGkkGk..',
      '..kGGGGk..',
      '..kGkkGk..',
      '..kGGGGk..',
      '...kkkk...',
      '....KK....',
      '..........',
    ]],
  },

  // == FIRE =================================================================
  {
    id: 'haz_fire_paper_blaze',
    scale: 2,
    anchor: [0.5, 0.5],
    frameDurations: [0.16, 0.16, 0.16],
    silhouette: 'Hard-edged flame tongues over a dashed scorch plate; shrinks as it burns out.',
    frames: [
      [
        '.....RR.RR......',
        '....RRRRRRR.....',
        '...RRyyRRyyRR...',
        '..RRyyYYyyYYyR..',
        '..RyyYYYYYYyyR..',
        '..RRyyYYYYyyRR..',
        '...RRyyYYyyRR...',
        '....RRyyyyRR....',
        '.....RRRRRR.....',
        'kk..kk..kk..kk..',
        'k..............k',
        '..KKKKKKKKKKKK..',
        '..KKKKKKKKKKKK..',
        'k..............k',
        'kk..kk..kk..kk..',
      ],
      [
        '......RR.RR.....',
        '.....RRRRRRR....',
        '...RRyyRRyyRR...',
        '..RyyYYyyYYyRR..',
        '..RRyyYYYYYYyR..',
        '..RyyYYYYyyRRR..',
        '...RRyyYYyyRR...',
        '....RRyyyyRR....',
        '.....RRRRRR.....',
        'kk..kk..kk..kk..',
        'k..............k',
        '..KKKKKKKKKKKK..',
        '..KKKKKKKKKKKK..',
        'k..............k',
        'kk..kk..kk..kk..',
      ],
      [
        '.....RR.RR......',
        '.....RRRRR......',
        '....RRyyRRyy....',
        '...RRyyYYyyYR...',
        '...RyyYYYYyyR...',
        '...RRyyYYyyRR...',
        '....RRyyYyRR....',
        '.....RRyyRR.....',
        '......RRRR......',
        'kk..kk..kk..kk..',
        'k..............k',
        '..KKKKKKKKKKKK..',
        '..KKKKKKKKKKKK..',
        'k..............k',
        'kk..kk..kk..kk..',
      ],
    ],
  },
  {
    id: 'haz_fire_scorch_mark',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Decorative burn smear: borderless dark blob with no flame tongues at all.',
    frames: [[
      '................',
      '.....KKKK.......',
      '...KKKKKKKK.....',
      '..KKKKKKKKKK....',
      '..KKKKKKKKKKKK..',
      '.KKKKKKKKKKKKKK.',
      '.KKKKKKKKKKKKKK.',
      '..KKKKKKKKKKKK..',
      '...KKKKKKKKKK...',
      '....KKKKKK......',
      '......KKK.......',
      '................',
    ]],
  },

  // == GLASS ================================================================
  {
    id: 'haz_glass_shard_field',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Static angular specks inside a heavy double-dash boundary; specks never travel.',
    frames: [[
      'kk..kk..kk..kk..',
      'k..............k',
      '..H..H....H..H..',
      '.H..H..H....H.H.',
      '..H....H..H...H.',
      'k.H..H....H..H.k',
      '.H....H..H....H.',
      '..H..H....H..H..',
      'k.H....H..H...Hk',
      '.H..H....H..H...',
      '..H....H..H..H..',
      'k.H..H....H...Hk',
      '.H....H..H..H...',
      'k..............k',
      'kk..kk..kk..kk..',
    ]],
  },

  // == PRESSURE =============================================================
  {
    id: 'haz_pressure_hvac_blast',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Vent grille with motion streaks only — no hatch fill, because it pushes.',
    frames: [[
      '.k...k...k...k..',
      '..kkkkkkkkkkkk..',
      '..kGkkkkkkkkGk..',
      '..kGkkkkkkkkGk..',
      '..kGkkkkkkkkGk..',
      '..kkkkkkkkkkkk..',
      '...H..H..H..H...',
      '...H..H..H..H...',
      '....H..H..H.....',
      '....H..H..H.....',
      '...H..H..H..H...',
      '...H..H..H..H...',
      '....H..H..H.....',
      '....H..H..H.....',
      '...H..H..H..H...',
      '...H..H..H..H...',
      '....H..H..H.....',
      '....H..H..H.....',
      '.....H..H.......',
      '.....H..H.......',
      '.k...k...k...k..',
    ]],
  },

  // == DARKNESS =============================================================
  {
    id: 'haz_darkness_outage_zone',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Dim region with corner ticks so its extent stays visible while the inside is dark.',
    frames: [[
      'kkk..................kkk',
      'k......................k',
      'k.KKKKKKKKKKKKKKKKKKKK.k',
      '..KKKKKKKKKKKKKKKKKKKK..',
      'k.KKKKKKKKKKKKKKKKKKKK.k',
      '..KKKKKKKKKKKKKKKKKKKK..',
      'k.KKKKKKKKKKKKKKKKKKKK.k',
      '..KKKKKKKKKKKKKKKKKKKK..',
      'k.KKKKKKKKKKKKKKKKKKKK.k',
      '..KKKKKKKKKKKKKKKKKKKK..',
      'k.KKKKKKKKKKKKKKKKKKKK.k',
      '..KKKKKKKKKKKKKKKKKKKK..',
      'k.KKKKKKKKKKKKKKKKKKKK.k',
      'k......................k',
      'kkk..................kkk',
    ]],
  },

  // == RED_TAPE =============================================================
  {
    id: 'haz_redtape_compliance_band',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Striped barrier band across a lane — stripes mean movement denial, never damage.',
    frames: [[
      '.k...k...k...k...k...k...k...k..',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
      '.kwwrrwwrrwwrrwwrrwwrrwwrrwwrrk.',
      '.krrwwrrwwrrwwrrwwrrwwrrwwrrwwk.',
      '.kwwrrwwrrwwrrwwrrwwrrwwrrwwrrk.',
      '.krrwwrrwwrrwwrrwwrrwwrrwwrrwwk.',
      '.kwwrrwwrrwwrrwwrrwwrrwwrrwwrrk.',
      '.krrwwrrwwrrwwrrwwrrwwrrwwrrwwk.',
      '.kwwrrwwrrwwrrwwrrwwrrwwrrwwrrk.',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
      '.k...k...k...k...k...k...k...k..',
      '................................',
    ]],
  },

  // == PAPER ================================================================
  {
    id: 'haz_paper_drift_bank',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Ankle-high sheet drift in a thin single-dash border: costs tempo, not health.',
    frames: [[
      '.k...k...k...k..',
      '................',
      '...kkkkkkkkkk...',
      '..kwwwwwwwwwwk..',
      '.kwwwwwwwwwwwwk.',
      '.kwwwwwwwwwwwwk.',
      '.kwwwwwwwwwwwwk.',
      '..kwwwwwwwwwwk..',
      '...kkkkkkkkkk...',
      '................',
      '.k...k...k...k..',
      '................',
    ]],
  },

  // == FOAM =================================================================
  {
    id: 'haz_foam_discharge_cloud',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Brightest floor effect in the game: scalloped white bubble mass, thin border.',
    frames: [[
      '.k...k...k...k...k...k..',
      '........wwwwwwww........',
      '......wwwwwwwwwwww......',
      '....wwwwwwwwwwwwwwww....',
      '...wwwwwwwwwwwwwwwwww...',
      '..wwwwwwwwwwwwwwwwwwww..',
      '.wwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwww.',
      '..wwwwwwwwwwwwwwwwwwww..',
      '...wwwwwwwwwwwwwwwwww...',
      '....wwwwwwwwwwwwwwww....',
      '......wwwwwwwwwwww......',
      '........wwwwwwww........',
      '.k...k...k...k...k...k..',
    ]],
  },

  // == VOTE =================================================================
  // HOSTILE outline family (GDD 18.5): a board rule owns this zone, not the
  // building, so it must not share the environment outline language.
  {
    id: 'haz_vote_quorum_circle',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Ring of static seat wedges closing inward; nothing ever detaches from the ring.',
    frames: [[
      'kk..kk..kk..kk..kk..kk..',
      '.......kk..kk..kk.......',
      '....kk............kk....',
      '..kk................kk..',
      '.kk..................kk.',
      '.kk..................kk.',
      'kk....................kk',
      'kk.......AAAAAA.......kk',
      'kk.......AAAAAA.......kk',
      'kk....................kk',
      '.kk..................kk.',
      '.kk..................kk.',
      '..kk................kk..',
      '....kk............kk....',
      '.......kk..kk..kk.......',
      'kk..kk..kk..kk..kk..kk..',
    ]],
  },
];

export default hazardSprites;
