/**
 * Sprite domain: items. Owns the `item_` prefix (plus `active_`, `card_`, `sup_`,
 * `charm_`, `trn_` when those land).
 *
 * GDD refs: 18.2 / R-ART-001 (readable at native gameplay scale - these bake to
 *           32x32 logical px, so silhouette beats detail), R-ART-002 / R-ITM-002
 *           (every collectible gets a visually distinct sprite), 8.2 (the item's
 *           shape is read off the pedestal before pickup), 18.5 (1px `k` outline
 *           family, `K` underside shadow so nothing looks flat).
 *
 * 60 office objects would collapse into "60 grey rectangles" if drawn honestly, so
 * each one is assigned a *shape language* first and a palette second: the wrist rest
 * is the widest flattest bar, the standing desk the only I-beam, the paperweight the
 * only dome, the laser pointer the only diagonal, the rubber bands the only tangle,
 * the reply-all the only swarm. Colour is reinforcement - every pair here still
 * separates in grayscale.
 *
 * Liability items (open_calendar, wet_keyboard, mandatory_training, reply_all) are
 * deliberately drawn *wrong* - gaping, dripping, padlocked, swarming - so the art
 * agrees with the red frame the UI puts around them.
 *
 * Grids are authored at half the 32px reference grid and baked at `scale: 2`.
 */

const SCALE = 2;

const item = (slug, silhouette, grid) => ({
  id: `item_${slug}`,
  anchor: [0.5, 0.75],
  scale: SCALE,
  silhouette,
  frames: [grid],
});

const items = [
  // ITM-001 Espresso Shot - tiny cup riding a wide saucer. Smallest cup + widest plate.
  item('espresso_shot', 'A tiny cup on an oversized saucer; the only cup-on-plate profile.', [
    '................',
    '................',
    '................',
    '....kkkkkk......',
    '...kwwwwwwk.....',
    '...kwoooook.kk..',
    '...kwoooook.kHk.',
    '....kwooowk.kk..',
    '.....kwwwk......',
    '......kkk.......',
    '..kkkkkkkkkk....',
    '..kHHHHHHHHk....',
    '..kKKKKKKKKk....',
    '...kkkkkkkk.....',
    '................',
    '................',
  ]),

  // ITM-002 Milk Carton - gable top. The only sprite that comes to a roof peak.
  item('milk_carton', 'A gable-topped carton; the only silhouette with a roof peak.', [
    '................',
    '................',
    '.....kkkk.......',
    '....kwwwwk......',
    '...kwwwwwwk.....',
    '...kwwwwwwk.....',
    '..kkkkkkkkkk....',
    '..kwwwwwwwwk....',
    '..kwwbbbbwwk....',
    '..kwwbbbbwwk....',
    '..kwwwwwwwwk....',
    '..kwwwwwwwwk....',
    '..kwwwwwwwwk....',
    '..kKKKKKKKKk....',
    '..kkkkkkkkkk....',
    '................',
  ]),

  // ITM-003 Sugar Packets - a cascade of sachets stepping down to the left.
  item('sugar_packets', 'Three paper sachets fanned in a descending stair-step cascade.', [
    '................',
    '................',
    '................',
    '.......kkkkk....',
    '......kwwwwk....',
    '.....kkwwwwk....',
    '.....kwwwwkk....',
    '....kkwwwwk.....',
    '....kwHHwkk.....',
    '...kkwHHwk......',
    '...kwwwwk.......',
    '...kkkkkk.......',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-004 Mechanical Switches - loose parts cluster, stems up. Not a slab: three bodies.
  item('mechanical_switches', 'A loose cluster of three small bodies with stems poking up.', [
    '................',
    '................',
    '.....kk.........',
    '.....hh.........',
    '....kkkkkk......',
    '....kRRRRk......',
    '....kRRRRk......',
    '....kkkkkk......',
    '..kk......kk....',
    '..hh......hh....',
    '.kkkkkk.kkkkkk..',
    '.kRRRRk.kRRRRk..',
    '.kRRRRk.kRRRRk..',
    '.kkkkkk.kkkkkk..',
    '................',
    '................',
  ]),

  // ITM-005 Heavy Keycaps - two thick slabs stacked. Reads as mass, not as a keyboard.
  item('heavy_keycaps', 'Two thick slabs stacked into a double-decker block; reads heavy.', [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kHHHHHHHHHHk..',
    '..kHHHHHHHHHHk..',
    '..kGGGGGGGGGGk..',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '..kkkkkkkkkkkk..',
    '..kHHHHHHHHHHk..',
    '..kHHHHHHHHHHk..',
    '..kGGGGGGGGGGk..',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ]),

  // ITM-006 Ergonomic Chair - tall mesh back over a five-star caster base.
  item('ergonomic_chair', 'Tall mesh back above a single post and a five-star caster base.', [
    '................',
    '..kkkkkkkkkkk...',
    '..kGhhhhhhhGk...',
    '..kGhkhkhkhGk...',
    '..kGhhhhhhhGk...',
    '..kGhkhkhkhGk...',
    '..kkkkkkkkkkk...',
    '.kkkkkkkkkkkkk..',
    '.kGGGGGGGGGGGk..',
    '.kkkkkkkkkkkkk..',
    '......kkkk......',
    '......kGHk......',
    '......kGHk......',
    '..kkkkkkkkkkkk..',
    '..kKKkkKKkkKKk..',
    '..k..kk..kk..k..',
  ]),

  // ITM-007 Standing Desk - full-width top on one tall column. The only I-beam.
  item('standing_desk', 'A full-width top on one tall centre column; the only I-beam shape.', [
    '................',
    '................',
    'kkkkkkkkkkkkkkkk',
    'kooooooooooooook',
    'kkkkkkkkkkkkkkkk',
    '......kkkk......',
    '......kGHk......',
    '......kGHk......',
    '......kGHk......',
    '......kGHk......',
    '......kGHk......',
    '......kGHk......',
    '....kkkkkkkk....',
    '....kGGGGGGk....',
    '....kkkkkkkk....',
    '................',
  ]),

  // ITM-008 Blue Light Glasses - two round tinted lenses bridged, temples at the edges.
  item('blue_light_glasses', 'Two round tinted lenses joined by a bridge, temples out to the edges.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkk....kkkk..',
    '.kcccck..kcccck.',
    'kkcCcckkkkcCcckk',
    '.kcccck..kcccck.',
    '.kcccck..kcccck.',
    '..kkkk....kkkk..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-009 Wrist Rest - edge to edge, five rows tall. The flattest thing in the set.
  item('wrist_rest', 'An edge-to-edge padded bar; the widest and flattest silhouette here.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kHHHHHHHHHHHHk.',
    'kHhhhhhhhhhhhhHk',
    '.kKKKKKKKKKKKKk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-010 Dual Monitors - two panels side by side, each on its own foot. Mirrored pair.
  item('dual_monitors', 'A mirrored pair of panels, each on its own stand and foot.', [
    '................',
    '..kkkkkk.kkkkkk.',
    '..kbbbbk.kbbbbk.',
    '..kbCCbk.kbCCbk.',
    '..kbbbbk.kbbbbk.',
    '..kbbbbk.kbbbbk.',
    '..kkkkkk.kkkkkk.',
    '....kGk....kGk..',
    '....kGk....kGk..',
    '..kkkkkk.kkkkkk.',
    '..kGGGGk.kGGGGk.',
    '..kkkkkk.kkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-011 Pen Laser Pointer - the only diagonal in the set, red beam dot off the tip.
  item('pen_laser_pointer', 'A slim diagonal barrel with a red beam dot floating off the tip.', [
    '................',
    '..............R.',
    '...........kkk..',
    '..........kRRk..',
    '.........kHHk...',
    '........kHHk....',
    '.......kHHk.....',
    '......kHGk......',
    '.....kHGk.......',
    '....kHGkk.......',
    '...kHGkk........',
    '..kHGk..........',
    '..kGk...........',
    '..kk............',
    '................',
    '................',
  ]),

  // ITM-012 Numeric Keypad - tall block ruled into a fine 4x4 key grid.
  item('numeric_keypad', 'A tall narrow block ruled into a fine four-by-four key grid.', [
    '................',
    '.kkkkkkkkkkkkk..',
    '.kwwgwwgwwgwwk..',
    '.kwwgwwgwwgwwk..',
    '.kgggggggggggk..',
    '.kwwgwwgwwgwwk..',
    '.kwwgwwgwwgwwk..',
    '.kgggggggggggk..',
    '.kwwgwwgwwgwwk..',
    '.kwwgwwgwwgwwk..',
    '.kgggggggggggk..',
    '.kwwgwwgwwgwwk..',
    '.kwwgwwgwwgwwk..',
    '.kKKKKKKKKKKKk..',
    '.kkkkkkkkkkkkk..',
    '................',
  ]),

  // ITM-013 USB Hub - small box with a row of dark port slots and a cord off the corner.
  item('usb_hub', 'A small box with three dark port slots and a cord off one corner.', [
    '................',
    '.............k..',
    '............k...',
    '............k...',
    '...........k....',
    '.kkkkkkkkkkk....',
    '.kHHHHHHHHHk....',
    '.kkkGkkGkkGk....',
    '.kHHHHHHHHHk....',
    '.kKKKKKKKKKk....',
    '.kkkkkkkkkkk....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-014 Wireless Dongle - the only sprite with signal arcs floating above it.
  item('wireless_dongle', 'A tiny nub under two floating signal arcs; the only radiating item.', [
    '................',
    '................',
    '......cccc......',
    '....cc....cc....',
    '.......cc.......',
    '......c..c......',
    '................',
    '.....kkkkk......',
    '.....kbbbk......',
    '.....kbbbk......',
    '.....kkkkk......',
    '.....kHHHk......',
    '.....kHkHk......',
    '.....kkkkk......',
    '................',
    '................',
  ]),

  // ITM-015 Macro Pad - six oversized keys, two columns by three rows. Coarse where the keypad is fine.
  item('macro_pad', 'Six oversized keys in two columns; coarse where the keypad is fine.', [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkk..',
    '.kMMMMMgMMMMMk..',
    '.kMMMMMgMMMMMk..',
    '.kgggggggggggk..',
    '.kMMMMMgMMMMMk..',
    '.kMMMMMgMMMMMk..',
    '.kgggggggggggk..',
    '.kMMMMMgMMMMMk..',
    '.kMMMMMgMMMMMk..',
    '.kKKKKKKKKKKKk..',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
  ]),

  // ITM-016 Sticky Keys - two caps fused, goo stringing down into drips.
  item('sticky_keys', 'Two caps fused side by side with goo stringing down into drips.', [
    '................',
    '..kkkkk.kkkkk...',
    '.kHHHHHkHHHHHk..',
    '.kHHHHHkHHHHHk..',
    '.kGGGGGkGGGGGk..',
    '.kkkkkkkkkkkkk..',
    '..yy.yy...yy....',
    '..yy..y....y....',
    '...y..y....y....',
    '...y.......y....',
    '...y............',
    '...Y.......yYy..',
    '..yYy......yYy..',
    '...y............',
    '................',
    '................',
  ]),

  // ITM-017 Autocorrect - a word bar with a red zigzag under it. The only text-plus-squiggle.
  item('autocorrect', 'A block of word glyphs with a red zigzag ruled underneath it.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..gg.ggg.gg.ggg.',
    '..gg.ggg.gg.ggg.',
    '..gg.ggg.gg.ggg.',
    '................',
    '..R.R.R.R.R.R.R.',
    '.r.r.r.r.r.r.r..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-018 Caps Lock - one big lit key, up-arrow punched out, glow pips under it.
  item('caps_lock', 'A single big yellow-lit key with an up-arrow and glow pips below.', [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kYYYYYYYYYYk..',
    '..kYYYYkkYYYYk..',
    '..kYYYkkkkYYYk..',
    '..kYYkkkkkkYYk..',
    '..kYYYYkkYYYYk..',
    '..kYYYYkkYYYYk..',
    '..kYYYYkkYYYYk..',
    '..kYYYYYYYYYYk..',
    '..kaaaaaaaaaak..',
    '..kkkkkkkkkkkk..',
    '...q........q...',
    '................',
    '................',
  ]),

  // ITM-019 Shift Key - same arrow, but edge-to-edge wide and dead grey. Never lit.
  item('shift_key', 'A grey key stretched edge to edge with an up-arrow; wide and unlit.', [
    '................',
    '................',
    '................',
    '................',
    'kkkkkkkkkkkkkkkk',
    'kHHHHHHHHHHHHHHk',
    'kHHHHHHkkHHHHHHk',
    'kHHHHHkkkkHHHHHk',
    'kHHHHkkkkkkHHHHk',
    'kHHHHHHkkHHHHHHk',
    'kHHHHHHkkHHHHHHk',
    'kGGGGGGGGGGGGGGk',
    'kKKKKKKKKKKKKKKk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
  ]),

  // ITM-020 Space Bar - three rows of white, full width. The thinnest bar in the set.
  item('space_bar', 'A three-row white sliver spanning the full width; the thinnest bar.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    'kkkkkkkkkkkkkkkk',
    'kwwwwwwwwwwwwwwk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-021 Backspace - the only key whose arrow points left.
  item('backspace', 'A grey key with a bold left-pointing arrow punched through it.', [
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kHHHHHHHHHHk..',
    '..kHHHkHHHHHHk..',
    '..kHHkkHHHHHHk..',
    '..kHkkkkkkkkHk..',
    '..kHkkkkkkkkHk..',
    '..kHHkkHHHHHHk..',
    '..kHHHkHHHHHHk..',
    '..kHHHHHHHHHHk..',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ]),

  // ITM-022 Ctrl+C - two pages offset on the diagonal; the only stepped double rectangle.
  item('ctrl_c', 'Two pages offset on the diagonal; the only stepped double rectangle.', [
    '................',
    '................',
    '.....kkkkkkkk...',
    '.....kwwwwwwk...',
    '.....kwwwwwwk...',
    '..kkkkkkkkwwk...',
    '..kHHHHHHkwwk...',
    '..kHHHHHHkwwk...',
    '..kHHHHHHkwwk...',
    '..kHHHHHHkwwk...',
    '..kHHHHHHkkkk...',
    '..kHHHHHHk......',
    '..kKKKKKKk......',
    '..kkkkkkkk......',
    '................',
    '................',
  ]),

  // ITM-023 Rubber Bands - the only tangle: irregular overlapping loops, no straight edges.
  item('rubber_bands', 'An irregular tangle of overlapping loops; the only shape with no straight edge.', [
    '................',
    '................',
    '.....OOOO.......',
    '...OO....OO.....',
    '..O..OOO...O....',
    '..O.O...O..O....',
    '..O.O...O.OO....',
    '..O..O.OO..O....',
    '...OO..OO..O....',
    '..O..OO..OOO....',
    '..O.O...O.......',
    '...OOO..OO......',
    '.....OOOO.......',
    '................',
    '................',
    '................',
  ]),

  // ITM-024 Binder Clip - black wedge widening to the base, two wire loops standing up.
  item('binder_clip', 'A black wedge widening to its base with two wire loops standing up.', [
    '................',
    '..hh........hh..',
    '.h..h......h..h.',
    '.h..h......h..h.',
    '..h..hh..hh..h..',
    '...hhh....hhh...',
    '.....kkkkkk.....',
    '....kkkKKkkk....',
    '...kkkkKKkkkk...',
    '..kkkkkKKkkkkk..',
    '.kkkkkkKKkkkkkk.',
    'kkkkkkkKKkkkkkkk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
    '................',
  ]),

  // ITM-025 Ethernet Cable - a thick closed coil under an RJ45 plug with gold contacts.
  item('ethernet_cable', 'A thick closed coil of cable hanging under an RJ45 plug.', [
    '................',
    '.........kkkkk..',
    '.........kAAAk..',
    '.........kAAAk..',
    '........kkHHHkk.',
    '........kHHHHHk.',
    '.......kTTk.....',
    '...kkkkkkkk.....',
    '..kkTTTTTTkk....',
    '..kTTkkkkTTk....',
    '..kTTkkkkTTk....',
    '..kTTkkkkTTk....',
    '..kkTTTTTTkk....',
    '...kkkkkkkk.....',
    '................',
    '................',
  ]),

  // ITM-026 Extension Cord - a cord snaking down to a chunky four-slot socket block.
  item('extension_cord', 'A cord snaking down from a wall plug into a chunky four-slot socket block.', [
    '................',
    '...........k.k..',
    '...........kkk..',
    '..........kwwwk.',
    '..........kkkkk.',
    '............k...',
    '..........kk....',
    '........kk......',
    '......kk........',
    '.kkkkkkkk.......',
    '.kwwwwwwk.......',
    '.kwkwwkwk.......',
    '.kwkwwkwk.......',
    '.kKKKKKKk.......',
    '.kkkkkkkk.......',
    '................',
  ]),

  // ITM-027 Rechargeable Battery - upright cell with a terminal nub and a bolt down its face.
  item('rechargeable_battery', 'An upright cell with a terminal nub and a lightning bolt down its face.', [
    '................',
    '......kkk.......',
    '......kEk.......',
    '....kkkkkkk.....',
    '....kEEEEEk.....',
    '....kEEyEEk.....',
    '....kEyyEEk.....',
    '....kyyyyEk.....',
    '....kEEyyyk.....',
    '....kEEyyEk.....',
    '....kEEyEEk.....',
    '....kEEEEEk.....',
    '....kKKKKKk.....',
    '....kkkkkkk.....',
    '................',
    '................',
  ]),

  // ITM-028 Red Staple Remover - the only fanged shape: two arms up, four teeth down.
  item('red_staple_remover', 'A red head with two arms raised and four teeth biting downward.', [
    '................',
    '..kkk......kkk..',
    '..krk......krk..',
    '..krk......krk..',
    '...krk....krk...',
    '....krk..krk....',
    '.....krrrrrk....',
    '....krrrrrrrk...',
    '....krrrrrrrk...',
    '....krrrrrrrk...',
    '....kkkkkkkkk...',
    '.....k.k.k.k....',
    '.....k.k.k.k....',
    '................',
    '................',
    '................',
  ]),

  // ITM-029 Lucky Paperclip - one bent wire, nested oblongs. Pure line art, no fill.
  item('lucky_paperclip', 'One bent wire folded into nested oblongs; pure line art with no fill.', [
    '................',
    '................',
    '....HHHHHHHH....',
    '...H........H...',
    '...H.HHHHHH.H...',
    '...H.H....H.H...',
    '...H.H.HH.H.H...',
    '...H.H.HH.H.H...',
    '...H.H.HH.H.H...',
    '...H.H.HH.H.H...',
    '...H.H.HH.H.H...',
    '...H.H.HH.H.H...',
    '...H.HHHHHH.H...',
    '...HHHHHHHHHH...',
    '................',
    '................',
  ]),

  // ITM-030 Whiteboard Eraser - wide two-tone block, plastic grip standing off the top.
  item('whiteboard_eraser', 'A wide two-tone block with a raised grip standing off the top.', [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '.....kBBBBk.....',
    '.kkkkkBBBBkkkkk.',
    '.kBBBBBBBBBBBBk.',
    '.kBBBBBBBBBBBBk.',
    '.kkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGk.',
    '.kggggggggggggk.',
    '.kKKKKKKKKKKKKk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ]),

  // ITM-031 Correction Fluid - necked bottle with a long brush cap; the only necked profile.
  item('correction_fluid', 'A squat bottle with a long brush cap; the only necked-bottle profile.', [
    '................',
    '.......kk.......',
    '......kwwk......',
    '......kwwk......',
    '......kwwk......',
    '.....kkwwkk.....',
    '.....kWWWWk.....',
    '.....kkkkkk.....',
    '....kkkkkkkk....',
    '...kwwwwwwwwk...',
    '...kwWWWWWWwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kKKKKKKKKk...',
    '...kkkkkkkkkk...',
    '................',
  ]),

  // ITM-032 Highlighter - fat barrel ending in an angled chisel wedge, cut down-left.
  item('highlighter', 'A fat yellow barrel ending in an angled chisel wedge cut down-left.', [
    '................',
    '.....kkkkkk.....',
    '.....kyyyyk.....',
    '....kkyyyykk....',
    '....kyyyyyyk....',
    '....kyYYYYyk....',
    '....kyYYYYyk....',
    '....kyyyyyyk....',
    '....kaaaaaak....',
    '....kyyyyyyk....',
    '....kkkkkkkk....',
    '....kYYYYYk.....',
    '...kYYYYYk......',
    '...kYYYk........',
    '...kkkk.........',
    '................',
  ]),

  // ITM-033 Paperweight - the only dome: semicircle over a flat base, glass highlight.
  item('paperweight', 'A glass dome: the only semicircle-over-flat-base silhouette in the set.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '....kkCCCCkk....',
    '...kCCCCCCCCk...',
    '..kCWWCCCCCCCk..',
    '..kCWWCCCCCCCk..',
    '..kCCCCCCCCCCk..',
    '..kcccccccccck..',
    '..kkkkkkkkkkkk..',
    '...KKKKKKKKKK...',
    '................',
    '................',
  ]),

  // ITM-034 Printer Ink - stepped shoulder cartridge with a nozzle strip hung below.
  item('printer_ink', 'A cartridge with a stepped shoulder and a nozzle strip hung below it.', [
    '................',
    '................',
    '....kkkkkkkk....',
    '....kbbbbbbk....',
    '..kkkkkkkkkk....',
    '..kbbbbbbbbk....',
    '..kbCCCCCCbk....',
    '..kbCCCCCCbk....',
    '..kbbbbbbbbk....',
    '..kbbbbbbbbk....',
    '..kKKKKKKKKk....',
    '..kkkkkkkkkk....',
    '....kkkkkk......',
    '....kaaaak......',
    '....kkkkkk......',
    '................',
  ]),

  // ITM-035 Toner Dust - an open bottle almost lost under the only billowing cloud.
  item('toner_dust', 'An open bottle half swallowed by the only billowing dust cloud here.', [
    '................',
    '...KK..KKK......',
    '..KKKKKKKKKK....',
    '.KKKKKKKKKKKK...',
    '.KKKgggKKKKKK...',
    '..KKKKKgggKK....',
    '...KKKKKKKK.....',
    '.....KKKK.......',
    '......KK........',
    '.....kkkk.......',
    '....kMMMk.......',
    '...kkMMMkk......',
    '...kMMMMMk......',
    '...kMMMMMk......',
    '...kKKKKKk......',
    '...kkkkkkk......',
  ]),

  // ITM-036 Noise Canceling Headphones - an arch bridging two deep ear cups.
  item('noise_canceling_headphones', 'A headband arch bridging two deep ear cups; an omega silhouette.', [
    '................',
    '.....kkkkkk.....',
    '...kkGGGGGGkk...',
    '..kkGGGGGGGGkk..',
    '..kGGkkkkkkGGk..',
    '..kGk......kGk..',
    '.kkkkk....kkkkk.',
    '.kHHHk....kHHHk.',
    '.kHggk....kggHk.',
    '.kHggk....kggHk.',
    '.kHHHk....kHHHk.',
    '.kKKKk....kKKKk.',
    '.kkkkk....kkkkk.',
    '................',
    '................',
    '................',
  ]),

  // ITM-037 Mini Fridge - upright cabinet, horizontal door seam, vertical handle right of it.
  item('mini_fridge', 'An upright cabinet with a horizontal door seam and a vertical handle.', [
    '................',
    '................',
    '..kkkkkkkkkkk...',
    '..kHHHHHHHHHk...',
    '..kHHHHHHHHHk...',
    '..kHHHHHHHkHk...',
    '..kkkkkkkkkHk...',
    '..kHHHHHHHkHk...',
    '..kHHHHHHHHHk...',
    '..kHHHHHHHHHk...',
    '..kHHHHHHHHHk...',
    '..kHHHHHHHHHk...',
    '..kGGGGGGGGGk...',
    '..kKKKKKKKKKk...',
    '..kkkkkkkkkkk...',
    '................',
  ]),

  // ITM-038 Lunchbox - the only arched carry-handle standing clear above the lid.
  item('lunchbox', 'A red case under the only arched carry-handle standing clear above it.', [
    '................',
    '.....kkkkkk.....',
    '....kk....kk....',
    '....k......k....',
    '.kkkkkkkkkkkkkk.',
    '.kRRRRRRRRRRRRk.',
    '.kRRRRRRRRRRRRk.',
    '.kkkkkkkkkkkkkk.',
    '.kRRRRRRRRRRRRk.',
    '.kRRRRRRRRRRRRk.',
    '.kRRRRRRRRRRRRk.',
    '.kRRRRRRRRRRRRk.',
    '.kKKKKKKKKKKKKk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ]),

  // ITM-039 Company Hoodie - folded stack with a hood bump and two drawstrings.
  item('company_hoodie', 'A folded garment stack topped by a hood bump with two drawstrings.', [
    '................',
    '.....kkkkkk.....',
    '....kvvvvvvk....',
    '....kvVVVVvk....',
    '...kkvvvvvvkk...',
    '..kvvvvvvvvvvk..',
    '..kvvwvvvvwvvk..',
    '..kvvwvvvvwvvk..',
    '.kkkkkkkkkkkkkk.',
    '.kvvvvvvvvvvvvk.',
    '.kvvvvvvvvvvvvk.',
    '.kkkkkkkkkkkkkk.',
    '.kvvvvvvvvvvvvk.',
    '.kKKKKKKKKKKKKk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ]),

  // ITM-040 Visitor Badge - card slung under an alligator clip; photo square, blue band.
  item('visitor_badge', 'A card hanging under an alligator clip, blue name band across its top.', [
    '.......kk.......',
    '......k..k......',
    '......k..k......',
    '.....kkkkkk.....',
    '.....kkkkkk.....',
    '...kkkkkkkkkk...',
    '...kBBBBBBBBk...',
    '...kBkkkkkkBk...',
    '...kwwwwwwwwk...',
    '...kwGGGGwwwk...',
    '...kwGGGGwwwk...',
    '...kwGGGGwwwk...',
    '...kwwwwwwwwk...',
    '...kKKKKKKKKk...',
    '...kkkkkkkkkk...',
    '................',
  ]),

  // ITM-041 Master Access Badge - quality 4. Chunkier slab, solid gold, star punched dead centre.
  item('master_access_badge', 'A chunky solid-gold slab with a five-point star punched dead centre.', [
    '................',
    '..kkkkkkkkkkkk..',
    '..kAAAAAAAAAAk..',
    '..kAqqqqqqqqAk..',
    '..kAqqqqqqqqAk..',
    '..kAqqqkkqqqAk..',
    '..kAqqkkkkqqAk..',
    '..kAkkkkkkkkAk..',
    '..kAqkkkkkkqAk..',
    '..kAqkkqqkkqAk..',
    '..kAqkqqqqkqAk..',
    '..kAqqqqqqqqAk..',
    '..kAAAAAAAAAAk..',
    '..kaaaaaaaaaak..',
    '..kkkkkkkkkkkk..',
    '................',
  ]),

  // ITM-042 Office Plant - broad leaf crown over a tapered pot; tall and bushy.
  item('office_plant', 'A broad bushy leaf crown on a thin stem above a tapered pot.', [
    '................',
    '...E..E..E......',
    '..EEE.EEE.EEE...',
    '.EEEEEEEEEEEEE..',
    '.EEeeEEEEEeeEE..',
    '..EEEEEEEEEEE...',
    '...EEEEEEEEE....',
    '.....EEeEE......',
    '.......e........',
    '...kkkkkkkkkk...',
    '...kooooooook...',
    '...kkkkkkkkkk...',
    '....kooooook....',
    '....kooooook....',
    '.....kKKKKk.....',
    '.....kkkkkk.....',
  ]),

  // ITM-043 Desk Cactus - narrow ribbed column with one stubby arm and spines poking out.
  item('desk_cactus', 'A narrow ribbed column with one stubby side arm and spines poking out.', [
    '................',
    '................',
    '.....H..H.......',
    '.....kkkkk......',
    '....HkeEekH.....',
    '.....keEekkkk...',
    '....HkeEekeEkH..',
    '.....keEekeEk...',
    '.....keEekkkk...',
    '....HkeEekH.....',
    '.....keEek......',
    '.....kkkkk......',
    '....kkkkkkk.....',
    '....koooook.....',
    '....kKKKKKk.....',
    '....kkkkkkk.....',
  ]),

  // ITM-044 Stress Ball - a sphere pinched in at the waist; the only dented circle.
  item('stress_ball', 'A rubber sphere pinched in at the waist; the only dented circle here.', [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkRRRRRRkk...',
    '..kRRRRRRRRRRk..',
    '.kRppRRRRRRRRk..',
    '.kRppRRRRRRRRk..',
    '..kkRRRRRRRRkk..',
    '.kRRRRRRRRRRRRk.',
    '.kRRRRRRRRRRRRk.',
    '..kRRRRRRRRRRk..',
    '...kkRRRRRRkk...',
    '.....kkkkkk.....',
    '....KKKKKKKK....',
    '................',
    '................',
  ]),

  // ITM-045 Company Laptop - open wedge: narrow lid above a base that flares out wider.
  item('company_laptop', 'An open wedge - narrow lid above a base that flares out wider.', [
    '................',
    '..kkkkkkkkkkk...',
    '..kbbbbbbbbbk...',
    '..kbCCCCCCCbk...',
    '..kbCCCCCCCbk...',
    '..kbCCCCCCCbk...',
    '..kbbbbbbbbbk...',
    '..kkkkkkkkkkk...',
    '.kkkkkkkkkkkkkk.',
    '.kHwHwHwHwHwHHk.',
    'kkHHHHHHHHHHHHkk',
    'kKKKKKKKKKKKKKKk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
    '................',
  ]),

  // ITM-046 Webcam - a disc with a ringed lens sitting on a splayed clip foot.
  item('webcam', 'A disc with a deep ringed lens sitting on a splayed clip foot.', [
    '................',
    '................',
    '......kkkk......',
    '....kkGGGGkk....',
    '...kGGGGGGGGk...',
    '..kGGkkkkkkGGk..',
    '..kGkkCCCCkkGk..',
    '..kGkkCCWCkkGk..',
    '..kGGkkkkkkGGk..',
    '...kGGGGGGGGk...',
    '....kkGGGGkk....',
    '.....kkkkkk.....',
    '.....kGGGGk.....',
    '...kkkGGGGkkk...',
    '...kkkkkkkkkk...',
    '................',
  ]),

  // ITM-047 Confidential Stamp - knob and pad above a red line already stamped on the desk.
  item('confidential_stamp', 'A knobbed stamp above the red line of type it has already printed.', [
    '................',
    '......kkkk......',
    '.....kHHHHk.....',
    '.....kHHHHk.....',
    '......kGGk......',
    '......kGGk......',
    '...kkkkkkkkkk...',
    '...kGGGGGGGGk...',
    '...kkkkkkkkkk...',
    '..kkkkkkkkkkkk..',
    '..krrrrrrrrrrk..',
    '..kkkkkkkkkkkk..',
    '................',
    '.rr.rr.rr.rr.rr.',
    '.rr.rr.rr.rr.rr.',
    '................',
  ]),

  // ITM-048 Calendar Reminder - intact page, day dots ruled across it, one date ringed red.
  item('calendar_reminder', 'An intact calendar page of day dots with one date ringed in red.', [
    '................',
    '....k....k......',
    '..kkkkkkkkkkkk..',
    '..kbbbbbbbbbbk..',
    '..kwwwwwwwwwwk..',
    '..kgwgwgwgwgwk..',
    '..kwwwwwwwwwwk..',
    '..kgwgwgwgwgwk..',
    '..kwwwwwwwwwwk..',
    '..kgwgwrrrwgwk..',
    '..kwwwwrkrwwwk..',
    '..kgwgwrrrwgwk..',
    '..kwwwwwwwwwwk..',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '................',
  ]),

  // ITM-049 Reply All - LIABILITY. One envelope with its flap gaping under a swarm of copies.
  item('reply_all', 'LIABILITY: one gaping envelope under a scattered swarm of copies of itself.', [
    '..kkk....kkk....',
    '..kwk....kRk....',
    '..kkk....kkk....',
    '......kkk..kkk..',
    '......kRk..kwk..',
    '......kkk..kkk..',
    '................',
    '.kkkkkkkkkkkk...',
    '.kkwwwwwwwwkk...',
    '.kwkwwwwwwkwk...',
    '.kwwkwwwwkwwk...',
    '.kwwwkwwkwwwk...',
    '.kwwwwkkwwwwk...',
    '.kwwwwwwwwwwk...',
    '.kKKKKKKKKKKk...',
    '.kkkkkkkkkkkk...',
  ]),

  // ITM-050 Open Calendar - LIABILITY. Rings and torn stubs over a hollow, crumbling void.
  item('open_calendar', 'LIABILITY: wire rings and torn stubs above a hollow, crumbling void.', [
    '................',
    '..hhh.hhh.hhh...',
    '..h.h.h.h.h.h...',
    '.kkkkkkkkkkkkkk.',
    '.kwwkkwwkkwwwwk.',
    '.kKKKKKKKKKKKKk.',
    '.kKKKKKKKKKKKKk.',
    '.kKKKKKKKKKKKKk.',
    '.kKKKKKKKKKKKKk.',
    '.kKKKKKKKKKKKKk.',
    '.kKKKKKKKKKKKKk.',
    '.kKKKKKKKKKKKKk.',
    '.kkKKKKKKKKkkk..',
    '..kkKKKKkkkk....',
    '....kkkk........',
    '................',
  ]),

  // ITM-051 Wet Keyboard - LIABILITY. Keys drowned, liquid running off the front and dripping.
  item('wet_keyboard', 'LIABILITY: a key slab drowned in liquid that runs off the front and drips.', [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kHwHwHwHwHwHwk.',
    '.kHHHHHHHHHHHHk.',
    '.kHwHccccccwwHk.',
    '.kHcccccccccwHk.',
    '.kcccccccccccck.',
    '.kkkkkkkkkkkkkk.',
    '..c...c....ccc..',
    '..c...c......c..',
    '..c..........c..',
    '..C..........C..',
    '.cCc........cCc.',
    '..c..........c..',
    '................',
  ]),

  // ITM-052 Cheap Chair - LIABILITY-adjacent sad stool: thin seat, no back, one leg buckling.
  item('cheap_chair', 'A thin backless seat on three legs, the right one visibly buckling inward.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kGGGGGGGGGGk..',
    '..kkkkkkkkkkkk..',
    '...k.....k...k..',
    '...k.....k...k..',
    '...k.....k..k...',
    '...k.....k..k...',
    '...k.....k.k....',
    '..kk....kk.kk...',
    '................',
    '................',
  ]),

  // ITM-053 Burnout - dead bulb: grey glass, a crack down it, filament snapped inside.
  item('burnout', 'A dead bulb - grey glass, a crack down one side, filament snapped inside.', [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkGGGGGGkk...',
    '..kGGGGkGGGGGk..',
    '..kGGGkkGGGGGk..',
    '..kGGkGkkkGGGk..',
    '..kGGGkkkGkGGk..',
    '..kGGGGkkkGGGk..',
    '...kGGGGGGGGk...',
    '....kkkkkkkk....',
    '.....kGGGGk.....',
    '.....kggggk.....',
    '.....kGGGGk.....',
    '......kkkk......',
    '................',
  ]),

  // ITM-054 Mandatory Training - LIABILITY. A certificate clamped shut by a gold padlock.
  item('mandatory_training', 'LIABILITY: a certificate clamped shut under a gold padlock and shackle.', [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkk...',
    '.kwwwwwwwwwwk...',
    '.kwggggggwwwk...',
    '.kwwwwwwwwwwk...',
    '.kwwwwwhhhwwk...',
    '.kwwwwhwwhwwk...',
    '.kwggghwwhwwk...',
    '.kwwkkkkkkkwk...',
    '.kwwkAAAAAkwk...',
    '.kwwkAAkAAkwk...',
    '.kwwkAAAAAkwk...',
    '.kwwkkkkkkkwk...',
    '.kkkkkkkkkkkk...',
  ]),

  // ITM-055 Three Hole Punch - full-width body with a lever bar above and three voids punched out.
  item('three_hole_punch', 'A full-width body with a lever bar above it and three voids punched through.', [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '...kGGGGGGGGk...',
    '...kkkkkkkkkk...',
    'kkkkkkkkkkkkkkkk',
    'kGGGGGGGGGGGGGGk',
    'kGkkGGGkkGGGkkGk',
    'kGkkGGGkkGGGkkGk',
    'kGGGGGGGGGGGGGGk',
    'kKKKKKKKKKKKKKKk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
    '................',
    '................',
  ]),

  // ITM-056 Sticky Notes - three notes fanned in a stepped diagonal, corners splayed.
  item('sticky_notes', 'Three square notes fanned into a stepped diagonal with splayed corners.', [
    '................',
    '................',
    '......kkkkkk....',
    '.....kkYYYYk....',
    '....kkEYYYYkkk..',
    '...kkEEYYYYkppk.',
    '..kkEEEYYYYkppk.',
    '..kEEEEYYYYkppk.',
    '..kEEEEYYYYkppk.',
    '..kEEEEkkkkkppk.',
    '..kEEEEkkkppppk.',
    '..kkkkkkkkppppk.',
    '..........kkkkk.',
    '................',
    '................',
    '................',
  ]),

  // ITM-057 Red Pen - a slim upright barrel with a pocket clip on its right flank.
  item('red_pen', 'A slim upright red barrel with a pocket clip down its right flank.', [
    '................',
    '.......kk.......',
    '......krrk......',
    '......krrk......',
    '......krrkk.....',
    '......krrkHk....',
    '......krrkHk....',
    '......krrkHk....',
    '......krrkkk....',
    '......kkkk......',
    '......krrk......',
    '......krrk......',
    '......krrk......',
    '.......krk......',
    '.......kk.......',
    '................',
  ]),

  // ITM-058 Spare Keyboard - quality 4. Still sealed: a bright sheen streak crossing it, gold seal.
  item('spare_keyboard', 'A sealed key slab crossed by a bright shrink-wrap sheen streak and a gold seal.', [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kWHwHwHwHwHwHk.',
    '.kHWHHHHHHHHHHk.',
    '.kHwWwHwHwHwHHk.',
    '.kHHHWHHHHHHHHk.',
    '.kHwHwWwHwHwHHk.',
    '.kHHHHHWHHHHHHk.',
    '.kHwHwHwWwAAHHk.',
    '.kHHHHHHHWAAHHk.',
    '.kKKKKKKKKKKKKk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ]),

  // ITM-059 Corporate Card - wide thin card, dark stripe across the top, gold chip low-left.
  item('corporate_card', 'A wide thin card with a dark stripe across the top and a gold chip low-left.', [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kbbbbbbbbbbbbk.',
    '.kkkkkkkkkkkkkk.',
    '.kbbbbbbbbbbbbk.',
    '.kbAAAbbbbbbbbk.',
    '.kbAAAbbCCCCbbk.',
    '.kbbbbbbbbbbbbk.',
    '.kKKKKKKKKKKKKk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ]),

  // ITM-060 Suggestion Box - sealed carton with a dark slot and one note still poking out of it.
  item('suggestion_box', 'A sealed carton with a dark top slot and one note still poking out of it.', [
    '................',
    '.......kwwk.....',
    '.......kwwk.....',
    '......kwwwwk....',
    '..kkkkkkkkkkkk..',
    '..kookkwwkkook..',
    '..koooooooooook.',
    '..kowwwwwwwwok..',
    '..kowggggggwok..',
    '..kowwwwwwwwok..',
    '..koooooooooook.',
    '..koooooooooook.',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ]),
];

export default items;
