/**
 * Sprite domain: objects.
 *
 * See content/sprites/index.js for the id-prefix ownership table and
 * src/render/sprites.js for the palette + grid DSL. This module owns the
 * `obj_` prefix and nothing else.
 *
 * GDD refs: 18.1 (chunky silhouettes), 18.2 (32px reference grid, integer
 *           scaling), R-ART-001 (readable at native gameplay scale),
 *           R-ENV-001 (visible shape matches collision), R-ENV-005 (an object
 *           may never read as a hostile entity or projectile).
 *
 * Authoring conventions used throughout:
 * - Grids are authored at half resolution with `scale: 2`, so one grid cell is
 *   two logical pixels and 16 grid columns is exactly one world unit (TILE=32).
 *   That keeps forms chunky at native scale instead of detailed-but-mushy.
 * - Every object carries a hard `k` outline. Interactive machines and reactive
 *   objects are the only ones allowed a saturated accent (status lights), and
 *   those accents are static geometry, never a free-floating glowing dot that
 *   could be mistaken for a projectile (R-ENV-005).
 * - Upright furniture uses a low anchor (~0.82) so the sprite's bottom band is
 *   its collision footprint; flat floor objects anchor at their centre.
 * - Crack/damage states are separate sprite ids rather than palette swaps,
 *   because a damaged object must change silhouette, not just tone.
 */

const objectSprites = [
  // -- ENV-001 Filing Cabinet ------------------------------------------------
  {
    id: 'obj_filing_cabinet',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Squat two-drawer box, flat lit top, two recessed handle slots.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kHHHHHHHHHHk..',
      '..kHHHHHHHHHHk..',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGhhhhhhhhGk..',
      '..kGhkkkkkkhGk..',
      '..kGhhhhhhhhGk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGhhhhhhhhGk..',
      '..kGhkkkkkkhGk..',
      '..kGhhhhhhhhGk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kKKKKKKKKKKk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
    ]],
  },
  {
    id: 'obj_filing_cabinet_damaged',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Same box with a dented top corner and one drawer hanging out left.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kHHHHHHHhkk...',
      '..kHHHHHHHHHk...',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGhhhhhhhhGk..',
      '..kGhkkkkkkhGk..',
      '..kGhhhhhhhhGk..',
      '..kkkkkkkkkkkk..',
      '.kkkkkkkkkkkkk..',
      '.khhhhhhhhhhhk..',
      '.khkkkkkkkkkhk..',
      '.khhhhhhhhhhhk..',
      '.kkkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kKKKKKKKKKKk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
    ]],
  },

  // -- ENV-002 Water Cooler -------------------------------------------------
  {
    id: 'obj_water_cooler',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Narrow white column topped by a wide pale-blue bottle; unmistakable neck.',
    frames: [[
      '..............',
      '....kkkkkk....',
      '...kCCCCCCk...',
      '..kCCCCCCCCk..',
      '..kCccccccCk..',
      '..kCccccccCk..',
      '..kCccccccCk..',
      '..kCccccccCk..',
      '...kCCCCCCk...',
      '....kwwwwk....',
      '...kwwwwwwk...',
      '..kwwwwwwwwk..',
      '..kwHHHHHHwk..',
      '..kwHHHHHHwk..',
      '..kwHkkkkHwk..',
      '..kwHkbbkHwk..',
      '..kwHkkkkHwk..',
      '..kwHHHHHHwk..',
      '..kwwwwwwwwk..',
      '..kkkkkkkkkk..',
      '..kKKKKKKKKk..',
      '...KKKKKKKK...',
    ]],
  },
  {
    id: 'obj_water_cooler_broken',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Bottle gone, jagged collar stumps, column standing in its own puddle.',
    frames: [[
      '..............',
      '..............',
      '....k....k....',
      '...kk...kk....',
      '..kCk...kCk...',
      '..kkk...kkk...',
      '..............',
      '....kkkkkk....',
      '...kwwwwwwk...',
      '..kwwwwwwwwk..',
      '..kwHHHHHHwk..',
      '..kwHHHHHHwk..',
      '..kwHkkkkHwk..',
      '..kwHkccKHwk..',
      '..kwHkkkkHwk..',
      '..kwHHHHHHwk..',
      '..kwHHHHHHwk..',
      '..kwwwwwwwwk..',
      '..kkkkkkkkkk..',
      '.kcccccccccck.',
      '..cccccccccc..',
      '...cccccccc...',
    ]],
  },

  // -- ENV-003 Printer ------------------------------------------------------
  {
    id: 'obj_printer',
    scale: 2,
    anchor: [0.5, 0.8],
    silhouette: 'Wide low copier: pale lid slab, dark output slot with a paper tongue.',
    frames: [[
      '......................',
      '...kkkkkkkkkkkkkkkk...',
      '..kHHHHHHHHHHHHHHHHk..',
      '..kHHkkkkkkkkkkHHHHk..',
      '..kHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGhhhhhhhhhhhhhhGk..',
      '..kGhkkkkkkkkkkkkhGk..',
      '..kGhwwwwwwwwwwwwhGk..',
      '..kGhkkkkkkkkkkkkhGk..',
      '..kGhhhhhhhhhhhhhhGk..',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGGGGkTkGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kKKKKkkkkkkkkKKKKk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKK...',
    ]],
  },
  {
    id: 'obj_printer_jammed',
    scale: 2,
    anchor: [0.5, 0.8],
    frameDurations: [0.45, 0.45],
    silhouette: 'Copier with crumpled paper erupting from the slot and a blinking panel lamp.',
    frames: [
      [
        '........kwwwk.........',
        '...kkkkkkkkkkkkkkkk...',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kHHkkkkkkkkkkHHHHk..',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhwKwwKwwKwwKwhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGGGGkRkGGGGGGGGGk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kKKKKkkkkkkkkKKKKk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKKKKKK...',
      ],
      [
        '.........www..........',
        '...kkkkkkkkkkkkkkkk...',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kHHkkkkkkkkkkHHHHk..',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhwwKwwKwwKwwwhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGGGGkkkGGGGGGGGGk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kKKKKkkkkkkkkKKKKk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKKKKKK...',
      ],
    ],
  },
  {
    id: 'obj_printer_damaged',
    scale: 2,
    anchor: [0.5, 0.8],
    silhouette: 'Copier with a caved-in lid and the front panel hanging off its hinge.',
    frames: [[
      '......................',
      '...kkkkkkkkkkkkkkkk...',
      '..kHHHHkkkHHHHHHHHHk..',
      '..kHHkkKKKkkkkkHHHHk..',
      '..kHHHHkkkHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGhhhhhhhhhhkkkkGk..',
      '..kGhkkkkkkkkkkKKKkk..',
      '..kGhKKKKKKKKKkKKKk...',
      '..kGhkkkkkkkkkkkkk....',
      '..kGhhhhhhhhhhGk......',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGGGGkkkGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kKKKKkkkkkkkkKKKKk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-004 Recycling Bin ------------------------------------------------
  {
    id: 'obj_recycling_bin',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Tapered blue tub with a pale rim and a blocky white recycling glyph.',
    frames: [[
      '..............',
      '..kkkkkkkkkk..',
      '..kHHHHHHHHk..',
      '..kkkkkkkkkk..',
      '..kbBBBBBBbk..',
      '..kbBwwwwBbk..',
      '..kbBwkkwBbk..',
      '..kbBwwwwBbk..',
      '..kbBBBBBBbk..',
      '..kbBBBBBBbk..',
      '..kbBBBBBBbk..',
      '..kbBBBBBBbk..',
      '..kkkkkkkkkk..',
      '...kKKKKKKk...',
      '...kkkkkkkk...',
      '....KKKKKK....',
    ]],
  },

  // -- ENV-005 Vending Machine ----------------------------------------------
  {
    id: 'obj_vending_machine',
    scale: 2,
    anchor: [0.5, 0.86],
    frameDurations: [0.7, 0.7],
    silhouette: 'Tall red cabinet, bright sign band, glass window of stacked snack rows.',
    frames: [
      [
        '..................',
        '..kkkkkkkkkkkkkk..',
        '..kRRRRRRRRRRRRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRwkkkkkkkkwRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkyyKOOKyykRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkEEKccKEEkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkOOKyyKOOkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRRRTkkkkkkRRk..',
        '..kRRRRRRRRRRRRk..',
        '..kkkkkkkkkkkkkk..',
        '..kKKKKKKKKKKKKk..',
        '..kkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKK...',
      ],
      [
        '..................',
        '..kkkkkkkkkkkkkk..',
        '..kRRRRRRRRRRRRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRwkkkkkkkkwRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkyyKOOKyykRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkEEKccKEEkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkOOKyyKOOkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRRRtkkkkkkRRk..',
        '..kRRRRRRRRRRRRk..',
        '..kkkkkkkkkkkkkk..',
        '..kKKKKKKKKKKKKk..',
        '..kkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKK...',
      ],
    ],
  },
  {
    id: 'obj_vending_machine_empty',
    scale: 2,
    anchor: [0.5, 0.86],
    silhouette: 'Same cabinet with a starred glass panel and empty dark shelves.',
    frames: [[
      '..................',
      '..kkkkkkkkkkkkkk..',
      '..kRRRRRRRRRRRRk..',
      '..kRhhhhhhhhhhRk..',
      '..kRhkkkkkkkkhRk..',
      '..kRhhhhhhhhhhRk..',
      '..kRRRRRRRRRRRRk..',
      '..kRkkkkkkkkkkRk..',
      '..kRkKKKKkKKKkRk..',
      '..kRkKKKkKkKKkRk..',
      '..kRkKKkkkkkKkRk..',
      '..kRkKKKkKkKKkRk..',
      '..kRkKKKKkKKKkRk..',
      '..kRkKKKKKKKKkRk..',
      '..kRkKKKKKKKKkRk..',
      '..kRRRRRRRRRRRRk..',
      '..kRkkkkkkkkkkRk..',
      '..kRkKKKKKKKKkRk..',
      '..kRkkkkkkkkkkRk..',
      '..kRRRRRRRRRRRRk..',
      '..kRRRkkkkkkkRRk..',
      '..kRRRRRRRRRRRRk..',
      '..kkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-006 Office Plant -------------------------------------------------
  {
    id: 'obj_office_plant',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'Round leafy crown on a short stem in a tapered terracotta pot.',
    frames: [[
      '..............',
      '.....kek......',
      '...kkeEekk....',
      '..keEEEEEek...',
      '.keEEEeEEEek..',
      '.keEEEeEEEek..',
      '..keEEEEEek...',
      '...kkeeekk....',
      '.....keek.....',
      '....kkkkkk....',
      '...kOOOOOOk...',
      '...koooooook..',
      '...koooooook..',
      '....kooook....',
      '....kooook....',
      '....kkkkkk....',
      '.....KKKK.....',
      '..............',
    ]],
  },
  {
    id: 'obj_office_plant_cactus',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'Vertical barrel cactus with two arms and pale spine ticks on every edge.',
    frames: [[
      '..............',
      '.....kkk......',
      '.....keYk.....',
      '.....keek.....',
      '..kkkkeekkk...',
      '..keYkeekYek..',
      '..keekeekeek..',
      '..kkekeekekk..',
      '...YkeeeekY...',
      '....keeeek....',
      '....kYeeYk....',
      '....keeeek....',
      '....kkkkkk....',
      '...kOOOOOOk...',
      '...koooooook..',
      '....kooook....',
      '....kkkkkk....',
      '.....KKKK.....',
    ]],
  },
];

export default objectSprites;
