/**
 * Sprite domain: objects.
 *
 * See content/sprites/index.js for the id-prefix ownership table and
 * src/render/sprites.js for the palette + grid DSL. This module owns the
 * `obj_` prefix and nothing else.
 *
 * GDD refs: 18.1 (chunky silhouettes), 18.2 (32px reference grid, integer
 *           scaling), R-ART-001 (readable at native gameplay scale),
 *           R-ENV-001 (visible shape matches collision), R-ENV-005 (an object
 *           may never read as a hostile entity or projectile).
 *
 * Authoring conventions used throughout:
 * - Grids are authored at half resolution with `scale: 2`, so one grid cell is
 *   two logical pixels and 16 grid columns is exactly one world unit (TILE=32).
 *   That keeps forms chunky at native scale instead of detailed-but-mushy.
 * - Every object carries a hard `k` outline. Interactive machines and reactive
 *   objects are the only ones allowed a saturated accent (status lights), and
 *   those accents are static geometry, never a free-floating glowing dot that
 *   could be mistaken for a projectile (R-ENV-005).
 * - Upright furniture uses a low anchor (~0.82) so the sprite's bottom band is
 *   its collision footprint; flat floor objects anchor at their centre.
 * - Crack/damage states are separate sprite ids rather than palette swaps,
 *   because a damaged object must change silhouette, not just tone.
 */

const objectSprites = [
  // -- ENV-001 Filing Cabinet ------------------------------------------------
  {
    id: 'obj_filing_cabinet',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Squat two-drawer box, flat lit top, two recessed handle slots.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kHHHHHHHHHHk..',
      '..kHHHHHHHHHHk..',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGhhhhhhhhGk..',
      '..kGhkkkkkkhGk..',
      '..kGhhhhhhhhGk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGhhhhhhhhGk..',
      '..kGhkkkkkkhGk..',
      '..kGhhhhhhhhGk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kKKKKKKKKKKk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
    ]],
  },
  {
    id: 'obj_filing_cabinet_damaged',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Same box with a dented top corner and one drawer hanging out left.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kHHHHHHHhkk...',
      '..kHHHHHHHHHk...',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kGhhhhhhhhGk..',
      '..kGhkkkkkkhGk..',
      '..kGhhhhhhhhGk..',
      '..kkkkkkkkkkkk..',
      '.kkkkkkkkkkkkk..',
      '.khhhhhhhhhhhk..',
      '.khkkkkkkkkkhk..',
      '.khhhhhhhhhhhk..',
      '.kkkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kKKKKKKKKKKk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
    ]],
  },

  // -- ENV-002 Water Cooler -------------------------------------------------
  {
    id: 'obj_water_cooler',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Narrow white column topped by a wide pale-blue bottle; unmistakable neck.',
    frames: [[
      '..............',
      '....kkkkkk....',
      '...kCCCCCCk...',
      '..kCCCCCCCCk..',
      '..kCccccccCk..',
      '..kCccccccCk..',
      '..kCccccccCk..',
      '..kCccccccCk..',
      '...kCCCCCCk...',
      '....kwwwwk....',
      '...kwwwwwwk...',
      '..kwwwwwwwwk..',
      '..kwHHHHHHwk..',
      '..kwHHHHHHwk..',
      '..kwHkkkkHwk..',
      '..kwHkbbkHwk..',
      '..kwHkkkkHwk..',
      '..kwHHHHHHwk..',
      '..kwwwwwwwwk..',
      '..kkkkkkkkkk..',
      '..kKKKKKKKKk..',
      '...KKKKKKKK...',
    ]],
  },
  {
    id: 'obj_water_cooler_broken',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Bottle gone, jagged collar stumps, column standing in its own puddle.',
    frames: [[
      '..............',
      '..............',
      '....k....k....',
      '...kk...kk....',
      '..kCk...kCk...',
      '..kkk...kkk...',
      '..............',
      '....kkkkkk....',
      '...kwwwwwwk...',
      '..kwwwwwwwwk..',
      '..kwHHHHHHwk..',
      '..kwHHHHHHwk..',
      '..kwHkkkkHwk..',
      '..kwHkccKHwk..',
      '..kwHkkkkHwk..',
      '..kwHHHHHHwk..',
      '..kwHHHHHHwk..',
      '..kwwwwwwwwk..',
      '..kkkkkkkkkk..',
      '.kcccccccccck.',
      '..cccccccccc..',
      '...cccccccc...',
    ]],
  },

  // -- ENV-003 Printer ------------------------------------------------------
  {
    id: 'obj_printer',
    scale: 2,
    anchor: [0.5, 0.8],
    silhouette: 'Wide low copier: pale lid slab, dark output slot with a paper tongue.',
    frames: [[
      '......................',
      '...kkkkkkkkkkkkkkkk...',
      '..kHHHHHHHHHHHHHHHHk..',
      '..kHHkkkkkkkkkkHHHHk..',
      '..kHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGhhhhhhhhhhhhhhGk..',
      '..kGhkkkkkkkkkkkkhGk..',
      '..kGhwwwwwwwwwwwwhGk..',
      '..kGhkkkkkkkkkkkkhGk..',
      '..kGhhhhhhhhhhhhhhGk..',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGGGGkTkGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kKKKKkkkkkkkkKKKKk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKK...',
    ]],
  },
  {
    id: 'obj_printer_jammed',
    scale: 2,
    anchor: [0.5, 0.8],
    frameDurations: [0.45, 0.45],
    silhouette: 'Copier with crumpled paper erupting from the slot and a blinking panel lamp.',
    frames: [
      [
        '........kwwwk.........',
        '...kkkkkkkkkkkkkkkk...',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kHHkkkkkkkkkkHHHHk..',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhwKwwKwwKwwKwhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGGGGkRkGGGGGGGGGk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kKKKKkkkkkkkkKKKKk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKKKKKK...',
      ],
      [
        '.........www..........',
        '...kkkkkkkkkkkkkkkk...',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kHHkkkkkkkkkkHHHHk..',
        '..kHHHHHHHHHHHHHHHHk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhwwKwwKwwKwwwhGk..',
        '..kGhkkkkkkkkkkkkhGk..',
        '..kGhhhhhhhhhhhhhhGk..',
        '..kGGGGGGGGGGGGGGGGk..',
        '..kGGGGkkkGGGGGGGGGk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '..kKKKKkkkkkkkkKKKKk..',
        '..kkkkkkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKKKKKK...',
      ],
    ],
  },
  {
    id: 'obj_printer_damaged',
    scale: 2,
    anchor: [0.5, 0.8],
    silhouette: 'Copier with a caved-in lid and the front panel hanging off its hinge.',
    frames: [[
      '......................',
      '...kkkkkkkkkkkkkkkk...',
      '..kHHHHkkkHHHHHHHHHk..',
      '..kHHkkKKKkkkkkHHHHk..',
      '..kHHHHkkkHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGhhhhhhhhhhkkkkGk..',
      '..kGhkkkkkkkkkkKKKkk..',
      '..kGhKKKKKKKKKkKKKk...',
      '..kGhkkkkkkkkkkkkk....',
      '..kGhhhhhhhhhhGk......',
      '..kGGGGGGGGGGGGGGGGk..',
      '..kGGGGkkkGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '..kKKKKkkkkkkkkKKKKk..',
      '..kkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-004 Recycling Bin ------------------------------------------------
  {
    id: 'obj_recycling_bin',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Tapered blue tub with a pale rim and a blocky white recycling glyph.',
    frames: [[
      '..............',
      '..kkkkkkkkkk..',
      '..kHHHHHHHHk..',
      '..kkkkkkkkkk..',
      '..kbBBBBBBbk..',
      '..kbBwwwwBbk..',
      '..kbBwkkwBbk..',
      '..kbBwwwwBbk..',
      '..kbBBBBBBbk..',
      '..kbBBBBBBbk..',
      '..kbBBBBBBbk..',
      '..kbBBBBBBbk..',
      '..kkkkkkkkkk..',
      '...kKKKKKKk...',
      '...kkkkkkkk...',
      '....KKKKKK....',
    ]],
  },

  // -- ENV-005 Vending Machine ----------------------------------------------
  {
    id: 'obj_vending_machine',
    scale: 2,
    anchor: [0.5, 0.86],
    frameDurations: [0.7, 0.7],
    silhouette: 'Tall red cabinet, bright sign band, glass window of stacked snack rows.',
    frames: [
      [
        '..................',
        '..kkkkkkkkkkkkkk..',
        '..kRRRRRRRRRRRRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRwkkkkkkkkwRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkyyKOOKyykRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkEEKccKEEkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkOOKyyKOOkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRRRTkkkkkkRRk..',
        '..kRRRRRRRRRRRRk..',
        '..kkkkkkkkkkkkkk..',
        '..kKKKKKKKKKKKKk..',
        '..kkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKK...',
      ],
      [
        '..................',
        '..kkkkkkkkkkkkkk..',
        '..kRRRRRRRRRRRRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRwkkkkkkkkwRk..',
        '..kRwwwwwwwwwwRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkyyKOOKyykRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkEEKccKEEkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkOOKyyKOOkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRkKKKKKKKKkRk..',
        '..kRkkkkkkkkkkRk..',
        '..kRRRRRRRRRRRRk..',
        '..kRRRtkkkkkkRRk..',
        '..kRRRRRRRRRRRRk..',
        '..kkkkkkkkkkkkkk..',
        '..kKKKKKKKKKKKKk..',
        '..kkkkkkkkkkkkkk..',
        '...KKKKKKKKKKKK...',
      ],
    ],
  },
  {
    id: 'obj_vending_machine_empty',
    scale: 2,
    anchor: [0.5, 0.86],
    silhouette: 'Same cabinet with a starred glass panel and empty dark shelves.',
    frames: [[
      '..................',
      '..kkkkkkkkkkkkkk..',
      '..kRRRRRRRRRRRRk..',
      '..kRhhhhhhhhhhRk..',
      '..kRhkkkkkkkkhRk..',
      '..kRhhhhhhhhhhRk..',
      '..kRRRRRRRRRRRRk..',
      '..kRkkkkkkkkkkRk..',
      '..kRkKKKKkKKKkRk..',
      '..kRkKKKkKkKKkRk..',
      '..kRkKKkkkkkKkRk..',
      '..kRkKKKkKkKKkRk..',
      '..kRkKKKKkKKKkRk..',
      '..kRkKKKKKKKKkRk..',
      '..kRkKKKKKKKKkRk..',
      '..kRRRRRRRRRRRRk..',
      '..kRkkkkkkkkkkRk..',
      '..kRkKKKKKKKKkRk..',
      '..kRkkkkkkkkkkRk..',
      '..kRRRRRRRRRRRRk..',
      '..kRRRkkkkkkkRRk..',
      '..kRRRRRRRRRRRRk..',
      '..kkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-006 Office Plant -------------------------------------------------
  {
    id: 'obj_office_plant',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'Round leafy crown on a short stem in a tapered terracotta pot.',
    frames: [[
      '..............',
      '.....kek......',
      '...kkeEekk....',
      '..keEEEEEek...',
      '.keEEEeEEEek..',
      '.keEEEeEEEek..',
      '..keEEEEEek...',
      '...kkeeekk....',
      '.....keek.....',
      '....kkkkkk....',
      '...kOOOOOOk...',
      '...koooooook..',
      '...koooooook..',
      '....kooook....',
      '....kooook....',
      '....kkkkkk....',
      '.....KKKK.....',
      '..............',
    ]],
  },
  {
    id: 'obj_office_plant_cactus',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'Vertical barrel cactus with two arms and pale spine ticks on every edge.',
    frames: [[
      '..............',
      '.....kkk......',
      '.....keYk.....',
      '.....keek.....',
      '..kkkkeekkk...',
      '..keYkeekYek..',
      '..keekeekeek..',
      '..kkekeekekk..',
      '...YkeeeekY...',
      '....keeeek....',
      '....kYeeYk....',
      '....keeeek....',
      '....kkkkkk....',
      '...kOOOOOOk...',
      '...koooooook..',
      '....kooook....',
      '....kkkkkk....',
      '.....KKKK.....',
    ]],
  },

  // -- ENV-007 Cubicle Divider ----------------------------------------------
  {
    id: 'obj_cubicle_divider',
    scale: 2,
    anchor: [0.5, 0.8],
    silhouette: 'Three-tile fabric panel: top rail, woven body, two stub feet.',
    frames: [[
      '................................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk..',
      '..kGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgk..',
      '..kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk..',
      '..kGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgGgk..',
      '..kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kkkk....................................kkkk..',
      '..KKKK....................................KKKK..',
    ]],
  },
  {
    id: 'obj_cubicle_divider_damaged',
    scale: 2,
    anchor: [0.5, 0.8],
    silhouette: 'Same panel with a torn-through gap in the middle third.',
    frames: [[
      '................................................',
      '..kkkkkkkkkkkkkkkkkkkkk......kkkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHHHHHk......kHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkkkk......kkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGGk......kGGGGGGGGGGGGGGGGGk..',
      '..kGgGgGgGgGgGgGgGgk......kgGgGgGgGgGgGgGgGgGk..',
      '..kGGGGGGGGGGGGGGGGk......kGGGGGGGGGGGGGGGGGGk..',
      '..kGgGgGgGgGgGgGgGgk......kgGgGgGgGgGgGgGgGgGk..',
      '..kGGGGGGGGGGGGGGGGk......kGGGGGGGGGGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkk......kkkkkkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKKKk......kKKKKKKKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkkkkkk......kkkkkkkkkkkkkkkkkkkk..',
      '..kkkk....................................kkkk..',
      '..KKKK....................................KKKK..',
    ]],
  },

  // -- ENV-008 Desk ---------------------------------------------------------
  {
    id: 'obj_desk',
    scale: 2,
    anchor: [0.5, 0.78],
    silhouette: 'Two-tile laminate slab over a modesty panel and a right drawer bank.',
    frames: [[
      '................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kOOOOOOOOOOOOOOOOOOOOOOOOOOk..',
      '..kOooooooooooooooooooooooooOk..',
      '..kOooooooooooooooooooooooooOk..',
      '..kOOOOOOOOOOOOOOOOOOOOOOOOOOk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGkGGGGGGGGGGGGk..',
      '..kGhhhhhhhhhhhhkGhhhhhhhhhhGk..',
      '..kGhhhhhhhhhhhhkGkkkkkkkkkkGk..',
      '..kGhhhhhhhhhhhhkGhhhhhhhhhhGk..',
      '..kGhhhhhhhhhhhhkGkkkkkkkkkkGk..',
      '..kGhhhhhhhhhhhhkGhhhhhhhhhhGk..',
      '..kGGGGGGGGGGGGGkGGGGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kkkk......................kkkk',
      '..KKKK......................KKKK',
    ]],
  },
  {
    id: 'obj_desk_overturned',
    scale: 2,
    anchor: [0.5, 0.7],
    silhouette: 'Desk on its side: slab lying flat, four legs jutting up in a row.',
    frames: [[
      '................................',
      '..kkkk................kkkk......',
      '..kKKk................kKKk......',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kOOOOOOOOOOOOOOOOOOOOOOOOOOk..',
      '..kOooooooooooooooooooooooooOk..',
      '..kOooooooooooooooooooooooooOk..',
      '..kOOOOOOOOOOOOOOOOOOOOOOOOOOk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kGhhhhhhhhhhhhhhhhhhhhhhhhGk..',
      '..kGkkkkkkkkkkkkkkkkkkkkkkkkGk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKKKKKKKKKKKKKk..',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-009 Rolling Chair ------------------------------------------------
  {
    id: 'obj_rolling_chair',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'Mesh back over a seat pad on a single stem with a five-castor base.',
    frames: [[
      '..............',
      '...kkkkkkkk...',
      '..kGGGGGGGGk..',
      '..kGhhhhhhGk..',
      '..kGhhhhhhGk..',
      '..kGhhhhhhGk..',
      '..kGGGGGGGGk..',
      '...kkkkkkkk...',
      '.....kkkk.....',
      '.....kGGk.....',
      '.....kGGk.....',
      '...kkkkkkkk...',
      '..kGGGGGGGGk..',
      '..kkkkkkkkkk..',
      '.kk..kkkk..kk.',
      'kKk..kKKk..kKk',
      '.k...kkkk...k.',
      '..............',
    ]],
  },

  // -- ENV-010 Server Rack --------------------------------------------------
  {
    id: 'obj_server_rack',
    scale: 2,
    anchor: [0.5, 0.9],
    silhouette: 'Two-tile-tall column of eight louvred bays with one LED per bay.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kggggggggggk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kgKKKKKKKKgk..',
      '..kgKKKKKKtKgk..',
      '..kgkkkkkkkkgk..',
      '..kggggggggggk..',
      '..kkkkkkkkkkkk..',
      '..kKKKKKKKKKKk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
      '................',
    ]],
  },

  // -- ENV-011 Cable Bundle -------------------------------------------------
  {
    id: 'obj_cable_bundle',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Two parallel floor strands, hard outlined, entirely below the entity plane.',
    frames: [[
      '................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGGGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '...kkkkkkkkkkkkkkkkkkkkkkkkkk...',
      '...kgggggggggggggggggggggggggk..',
      '...kkkkkkkkkkkkkkkkkkkkkkkkkk...',
      '................................',
    ]],
  },

  // -- ENV-012 Glass Partition ----------------------------------------------
  {
    id: 'obj_glass_partition',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Bright thin frame around a barely tinted pane; a straight wall segment.',
    frames: [[
      '................................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kCccccccccccccccccccccccccccccccccccccccccCk..',
      '..kCccccccccccccccccccccccccccccccccccccccccCk..',
      '..kCccccccccccccccccccccccccccccccccccccccccCk..',
      '..kCccccccccccccccccccccccccccccccccccccccccCk..',
      '..kCccccccccccccccccccccccccccccccccccccccccCk..',
      '..kCccccccccccccccccccccccccccccccccccccccccCk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
    ]],
  },
  {
    id: 'obj_glass_partition_cracked',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Same frame, pane webbed with pale spider cracks — a shape change, not a tint.',
    frames: [[
      '................................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kCccccccccccchcccccccccccccccccccccccccccCCk..',
      '..kCcccccccccccchccccccccccccccchcccccccccccCk..',
      '..kCcccccccccchcchcccccccchccccchccccccccccCCk..',
      '..kCccccccccccchcccccccccchcccccchcccccccccCCk..',
      '..kCcccccccccccchccccccccccchcccccccccccccccCk..',
      '..kCcccccccccccccccccccccccccccccccccccccccCCk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-013 Archive Shelf ------------------------------------------------
  {
    id: 'obj_archive_shelf',
    scale: 2,
    anchor: [0.5, 0.9],
    silhouette: 'Tall two-tile bookcase, five even shelves of cardboard and paper boxes.',
    frames: [[
      '................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgHHHHHHHHHHHHHHHHHHHHHHHHgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgKKKKKKKKKKKKKKKKKKKKKKKKgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
      '................................',
    ]],
  },
  {
    id: 'obj_archive_shelf_overloaded',
    scale: 2,
    anchor: [0.5, 0.9],
    silhouette: 'Same bookcase, boxes stacked above the top edge and one shelf visibly sagging.',
    frames: [[
      '.......OOOOwwww.................',
      '.......OOOOwwww.......OOOO......',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgHHHHHHHHHHHHHHHHHHHHHHHHgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgkkkkkkkkkkkkkkkkkkkkkkkkgk..',
      '..kgkOOOwwwwOOOOwwwwOOOOwwwkgk..',
      '..kgkOOOwwwwOOOOwwwwOOOOwwwkgk..',
      '..kgkkkkkkkkkkkkkkkkkkkkkkkkgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kgwwwwOOOOwwwwOOOOwwwwOOOOgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kgOOOOwwwwOOOOwwwwOOOOwwwwgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgKKKKKKKKKKKKKKKKKKKKKKKKgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
      '................................',
    ]],
  },

  // -- ENV-014 Whiteboard ---------------------------------------------------
  {
    id: 'obj_whiteboard',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'White panel in a thin tray frame on a two-legged easel.',
    frames: [[
      '................................',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kgwwwwwwwwwwwwwwwwwwwwwwwwgk..',
      '..kgwwhwwhwwwwwwwwhwwhwwwwwwgk..',
      '..kgwwwwwwwhwwwwwwwwwwwwwwhwgk..',
      '..kgwhwwwwwwwwhwwhwwwwwwwwwwgk..',
      '..kgwwwwwwwwwwwwwwwwhwwhwwwwgk..',
      '..kgwwhwwhwwwwwwwwwwwwwwwwwwgk..',
      '..kgwwwwwwwwwwwwwwwwwwwwwwwwgk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '..kGGGGGGGGGGGGGGGGGGGGGGGGGGk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '.....kkk................kkk.....',
      '.....kKk................kKk.....',
      '.....kKk................kKk.....',
      '.....kkk................kkk.....',
      '....KKKK................KKKK....',
      '................................',
    ]],
  },

  // -- ENV-015 Coffee Machine -----------------------------------------------
  {
    id: 'obj_coffee_machine',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Small upright box: water window on top, recessed cup bay below.',
    frames: [[
      '..............',
      '..kkkkkkkkkk..',
      '..kHHHHHHHHk..',
      '..kHkkkkkkHk..',
      '..kHkwwwwkHk..',
      '..kHkwwwwkHk..',
      '..kHkkkkkkHk..',
      '..kHHHHHHHHk..',
      '..kHkTkkkkHk..',
      '..kHHHHHHHHk..',
      '..kkkkkkkkkk..',
      '..kGGGGGGGGk..',
      '..kGkkkkkkGk..',
      '..kGkoookkGk..',
      '..kGkoookkGk..',
      '..kGkkkkkkGk..',
      '..kkkkkkkkkk..',
      '...KKKKKKKK...',
    ]],
  },

  // -- ENV-016 Fire Extinguisher --------------------------------------------
  {
    id: 'obj_fire_extinguisher',
    scale: 2,
    anchor: [0.5, 0.85],
    silhouette: 'Smallest object in the catalog: red canister, handle nub, black hose loop.',
    frames: [[
      '..........',
      '...kkkk...',
      '...kKKk...',
      '..kkkkkk..',
      '..krrrrk..',
      '..krRRrk..',
      '..krRRrk..',
      '.kkrRRrkk.',
      '.k.krRRrk.',
      '.kkkrRRrk.',
      '..krRRrk..',
      '..krrrrk..',
      '..kkkkkk..',
      '...KKKK...',
    ]],
  },

  // -- ENV-017 Supply Cart --------------------------------------------------
  {
    id: 'obj_supply_cart',
    scale: 2,
    anchor: [0.5, 0.86],
    silhouette: 'Open wire cage on castors with a horizontal push bar; floor shows through.',
    frames: [[
      '....................',
      '..kkkkkkkkkkkkkkkk..',
      '..kHHHHHHHHHHHHHHk..',
      '..kkkkkkkkkkkkkkkk..',
      '..kgkkkkkkkkkkkkgk..',
      '..kgk.k.k.k.k.k.gk..',
      '..kgkkkkkkkkkkkkgk..',
      '..kgk.k.k.k.k.k.gk..',
      '..kgkkkkkkkkkkkkgk..',
      '..kgk.k.k.k.k.k.gk..',
      '..kgkkkkkkkkkkkkgk..',
      '..kkkkkkkkkkkkkkkk..',
      '..kOOOOOOOOOOOOOOk..',
      '..kOooooOOooooOOok..',
      '..kkkkkkkkkkkkkkkk..',
      '..kKKKKKKKKKKKKKKk..',
      '..kkkkkkkkkkkkkkkk..',
      '..kk............kk..',
      '.kKk............kKk.',
      '..k..............k..',
    ]],
  },

  // -- ENV-018 Locked Cabinet -----------------------------------------------
  {
    id: 'obj_locked_cabinet',
    scale: 2,
    anchor: [0.5, 0.82],
    silhouette: 'Cabinet body split by a heavy vertical hasp plate with a gold keyhole.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kHHHHHHHHHHk..',
      '..kHHHHHHHHHHk..',
      '..kkkkkkkkkkkk..',
      '..kGGGGggGGGGk..',
      '..kGhhhgggh hGk.',
      '..kGhkkggkkhGk..',
      '..kGhhhggghhGk..',
      '..kGGGGggGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kGGGGggGGGGk..',
      '..kGhhhggghhGk..',
      '..kGhhkAAkhhGk..',
      '..kGhhhggghhGk..',
      '..kGGGGggGGGGk..',
      '..kkkkkkkkkkkk..',
      '..kKKKKKKKKKKk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
    ]],
  },

  // -- ENV-019 Power Strip --------------------------------------------------
  {
    id: 'obj_power_strip',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Flat floor bar of socket squares with one baked-in switch pip.',
    frames: [[
      '................',
      '..kkkkkkkkkkkk..',
      '..kGGGGGGGGGGk..',
      '..kkKkKkKkKkTk..',
      '..kkKkKkKkKkTk..',
      '..kGGGGGGGGGGk..',
      '..kkkkkkkkkkkk..',
      '...KKKKKKKKKK...',
    ]],
  },

  // -- ENV-020 Trophy Case --------------------------------------------------
  {
    id: 'obj_trophy_case',
    scale: 2,
    anchor: [0.5, 0.84],
    silhouette: 'Gold-framed glass box with two shelf lines of static award blocks.',
    frames: [[
      '....................',
      '..kkkkkkkkkkkkkkkk..',
      '..kaAAAAAAAAAAAAak..',
      '..kkkkkkkkkkkkkkkk..',
      '..kaCcccccccccccak..',
      '..kaCccAcccccAccak..',
      '..kaCccAcccccAccak..',
      '..kaCcAAAcccAAAcak..',
      '..kaCcccccccccccak..',
      '..kakkkkkkkkkkkkak..',
      '..kaCcccccccccccak..',
      '..kaCcAAcccccAAcak..',
      '..kaCcAAcccccAAcak..',
      '..kaCcccccccccccak..',
      '..kkkkkkkkkkkkkkkk..',
      '..kaAAAAAAAAAAAAak..',
      '..kkkkkkkkkkkkkkkk..',
      '...KKKKKKKKKKKKKK...',
    ]],
  },

  // -- ENV-021 Coffee Stain -------------------------------------------------
  // The three stain sprites are the R-ENV-002 acceptance case: decorative is a
  // borderless soft blob, mechanical variants get a dashed border plus a hatch,
  // and the two mechanical hatches differ from each other (streak vs stipple).
  {
    id: 'obj_coffee_stain',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Decorative: irregular borderless blob, no hatch, low floor contrast.',
    frames: [[
      '................',
      '.....oooo.......',
      '...oooooooo.....',
      '..oooooooooo....',
      '..oooooooooooo..',
      '.oooooooooooooo.',
      '.oooooooooooooo.',
      '..oooooooooooo..',
      '...oooooooooo...',
      '....oooooo......',
      '......ooo.......',
      '................',
    ]],
  },
  {
    id: 'obj_coffee_stain_slick',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Mechanical slick: dashed border plus dense diagonal streak hatch.',
    frames: [[
      '.k.k.k.k.k.k.k..',
      'k..CcCcCcCcCc..k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k.CcCcCcCcCcCc.k',
      '..cCcCcCcCcCcC..',
      'k..CcCcCcCcCc..k',
      '.k.k.k.k.k.k.k..',
      '................',
    ]],
  },
  {
    id: 'obj_coffee_stain_sticky',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Mechanical sticky patch: dashed border plus sparse stipple, warm tone.',
    frames: [[
      '.k.k.k.k.k.k.k..',
      'k..o.o.o.o.o...k',
      '...o.o.o.o.o....',
      'k.o.o.o.o.o.o..k',
      '..o.o.o.o.o.o...',
      'k.o.o.o.o.o.o..k',
      '..o.o.o.o.o.o...',
      'k.o.o.o.o.o.o..k',
      '...o.o.o.o.o....',
      'k..o.o.o.o.o...k',
      '.k.k.k.k.k.k.k..',
      '................',
    ]],
  },

  // -- ENV-022 Paper Pile ---------------------------------------------------
  {
    id: 'obj_paper_pile',
    scale: 2,
    anchor: [0.5, 0.7],
    silhouette: 'Ankle-high fan of overlapping sheets; never rises above the floor plane.',
    frames: [[
      '................',
      '................',
      '.....kkkk.......',
      '...kkwwwwkk.....',
      '..kwwwwwwwwkk...',
      '.kkwwwwwwwwwwk..',
      '.kwwwwwwwwwwwwk.',
      'kkwwwwwwwwwwwwkk',
      'kwwwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkkkk',
      '.KKKKKKKKKKKKKK.',
      '................',
    ]],
  },

  // -- ENV-023 Security Scanner ---------------------------------------------
  {
    id: 'obj_security_scanner',
    scale: 2,
    anchor: [0.5, 0.5],
    silhouette: 'Flush floor plate between two short bracket posts; emits nothing itself.',
    frames: [[
      '................',
      '.kk..........kk.',
      '.kTk........kTk.',
      '.kkk........kkk.',
      '.kkkkkkkkkkkkkk.',
      '.kGGGGGGGGGGGGk.',
      '.kGkkkkkkkkkkGk.',
      '.kGGGGGGGGGGGGk.',
      '.kkkkkkkkkkkkkk.',
      '................',
    ]],
  },

  // -- ENV-024 Conveyor Lane ------------------------------------------------
  {
    id: 'obj_conveyor_lane',
    scale: 2,
    anchor: [0.5, 0.5],
    frameDurations: [0.18, 0.18],
    silhouette: 'Four-tile recessed lane of chevron slats; direction is the chevron point.',
    frames: [
      [
        '................................................................',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '..kgGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgk..',
        '..kgkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgk.',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgk.',
        '..kgGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgk..',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '................................................................',
      ],
      [
        '................................................................',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '..kgGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgk..',
        '..kgkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgk.',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGgk..',
        '..kgGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkGGkkgk..',
        '..kgkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgk.',
        '..kgGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgk..',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '................................................................',
      ],
    ],
  },
];

export default objectSprites;
