/**
 * Sprite domain: player. Owns the `player_` id prefix.
 *
 * GDD refs: 18.1 (chunky silhouettes, slightly grotesque corporate-cartoon tone),
 *           18.3 (the player has a persistent outline and item-layer priority),
 *           R-PLY-005 (the player must remain visually understandable when
 *           surrounded by effects), R-ART-001 (readable at native gameplay scale).
 *
 * Design intent: an ordinary employee, not a hero. Slumped posture, a lanyard, an
 * untucked company polo. The silhouette is deliberately broader at the shoulders
 * than anything in the Open Office enemy roster, so the player never gets lost in a
 * crowd of drones — that is the entire point of R-PLY-005.
 *
 * Palette characters come from PALETTE in src/render/sprites.js:
 *   n hair, s/S/d skin tones, b/B shirt blues, g trousers, k outline,
 *   w paper, y/Y lanyard badge, h grey cord.
 */

const player = [
  {
    id: 'player_idle_south',
    anchor: [0.5, 0.92],
    silhouette: 'Broad shoulders, visible lanyard badge, head slightly forward.',
    frames: [[
      '................',
      '.....nnnnnn.....',
      '....nnnnnnnn....',
      '....nSSSSSSn....',
      '....nSkSSkSn....',
      '....nSSSSSSn....',
      '.....SSddSS.....',
      '......ssss......',
      '...bbbByybbbb...',
      '..bbBBByyBBBbb..',
      '..bSBBBYYBBBSb..',
      '..bSBBBBBBBBSb..',
      '...SBBBBBBBBS...',
      '....gggggggg....',
      '....gggggggg....',
      '....gg....gg....',
      '....gg....gg....',
      '....kk....kk....',
    ], [
      '................',
      '.....nnnnnn.....',
      '....nnnnnnnn....',
      '....nSSSSSSn....',
      '....nSkSSkSn....',
      '....nSSSSSSn....',
      '.....SSddSS.....',
      '......ssss......',
      '...bbbByybbbb...',
      '..bbBBByyBBBbb..',
      '..bSBBBYYBBBSb..',
      '..bSBBBBBBBBSb..',
      '...SBBBBBBBBS...',
      '....gggggggg....',
      '...ggggggggg....',
      '...ggg...ggg....',
      '...gg.....gg....',
      '...kk.....kk....',
    ]],
  },
  {
    id: 'player_idle_north',
    anchor: [0.5, 0.92],
    silhouette: 'Back of head, no face; lanyard cord crosses the neck.',
    frames: [[
      '................',
      '.....nnnnnn.....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '.....nnnnnn.....',
      '......ssss......',
      '...bbbbhhbbbb...',
      '..bbBBBhhBBBbb..',
      '..bSBBBBBBBBSb..',
      '..bSBBBBBBBBSb..',
      '...SBBBBBBBBS...',
      '....gggggggg....',
      '....gggggggg....',
      '....gg....gg....',
      '....gg....gg....',
      '....kk....kk....',
    ], [
      '................',
      '.....nnnnnn.....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '.....nnnnnn.....',
      '......ssss......',
      '...bbbbhhbbbb...',
      '..bbBBBhhBBBbb..',
      '..bSBBBBBBBBSb..',
      '..bSBBBBBBBBSb..',
      '...SBBBBBBBBS...',
      '....gggggggg....',
      '....ggggggggg...',
      '....ggg...ggg...',
      '....gg.....gg...',
      '....kk.....kk...',
    ]],
  },
  {
    id: 'player_idle_east',
    anchor: [0.5, 0.92],
    silhouette: 'Profile: one eye, nose bump, single trailing arm.',
    frames: [[
      '................',
      '.....nnnnnn.....',
      '....nnnnnnnnn...',
      '....nnSSSSSSd...',
      '....nnSSkSSSd...',
      '.....nSSSSSSs...',
      '.....SSSddSs....',
      '......ssss......',
      '....bbbbyybb....',
      '...bbBBByyBBb...',
      '...bSBBBYYBBb...',
      '...bSBBBBBBBb...',
      '....SBBBBBBB....',
      '.....gggggg.....',
      '.....gggggg.....',
      '.....gg.gg......',
      '.....gg.gg......',
      '.....kk.kk......',
    ], [
      '................',
      '.....nnnnnn.....',
      '....nnnnnnnnn...',
      '....nnSSSSSSd...',
      '....nnSSkSSSd...',
      '.....nSSSSSSs...',
      '.....SSSddSs....',
      '......ssss......',
      '....bbbbyybb....',
      '...bbBBByyBBb...',
      '...bSBBBYYBBb...',
      '...bSBBBBBBBb...',
      '....SBBBBBBB....',
      '.....gggggg.....',
      '....ggggggg.....',
      '....ggg..gg.....',
      '...ggg....gg....',
      '...kk.....kk....',
    ]],
  },
  {
    id: 'player_idle_west',
    anchor: [0.5, 0.92],
    silhouette: 'Mirror of the east profile, kept as its own sprite for clarity.',
    frames: [[
      '................',
      '.....nnnnnn.....',
      '...nnnnnnnnn....',
      '...dSSSSSSnn....',
      '...dSSSkSSnn....',
      '...sSSSSSSn.....',
      '....sSddSSS.....',
      '......ssss......',
      '....bbyybbbb....',
      '...bBByyBBBbb...',
      '...bBBYYBBBSb...',
      '...bBBBBBBBSb...',
      '....BBBBBBBS....',
      '.....gggggg.....',
      '.....gggggg.....',
      '......gg.gg.....',
      '......gg.gg.....',
      '......kk.kk.....',
    ], [
      '................',
      '.....nnnnnn.....',
      '...nnnnnnnnn....',
      '...dSSSSSSnn....',
      '...dSSSkSSnn....',
      '...sSSSSSSn.....',
      '....sSddSSS.....',
      '......ssss......',
      '....bbyybbbb....',
      '...bBByyBBBbb...',
      '...bBBYYBBBSb...',
      '...bBBBBBBBSb...',
      '....BBBBBBBS....',
      '.....gggggg.....',
      '.....ggggggg....',
      '.....gg..ggg....',
      '....gg....ggg...',
      '....kk.....kk...',
    ]],
  },
  {
    /**
     * Death pose. GDD 5.3 step 6 freezes pickups and room mutation on death, so
     * this must read as final rather than as one more walk frame.
     */
    id: 'player_collapsed',
    anchor: [0.5, 0.7],
    silhouette: 'Horizontal with scattered paper; unmistakably not a walk frame.',
    frames: [[
      '................',
      '................',
      '................',
      '................',
      '..w..........w..',
      '.....w....w.....',
      '..nnnn..........',
      '.nSSSSn.........',
      '.nSSSSn..w......',
      '..ssss..........',
      '.bbBBBBBBBbb....',
      '.bBBBBBBBBBb....',
      '..ggggggggg.....',
      '...gg....gg.....',
      '...kk....kk.....',
      '................',
      '................',
      '................',
    ]],
  },
];

export default player;
