/**
 * Sprite domain: weapons. Owns the `weapon_` and `prj_` id prefixes.
 *
 * GDD refs: 7.5 ("Every weapon has a distinct silhouette, attack sound, and impact
 *           language before modifiers are applied"), 18.2 (32px reference grid; one
 *           world unit is 32 logical pixels), 18.4 (the held weapon sits in the
 *           highest visual priority band), R-ART-001 (readable at native gameplay
 *           scale), R-ART-002 / R-ITM-002 (a unique sprite per collectible),
 *           18.5 (player attacks use a consistent friendly outline family).
 *
 * Two sprites per weapon:
 *   `weapon_<slug>`       the pedestal / pickup silhouette, 16x16 at scale 2
 *   `weapon_<slug>_held`  the small in-hand version, 10x10 at scale 2
 *
 * The held versions exist because GDD 18.4 puts the current weapon in the
 * gameplay-critical layer: the player must be able to tell what they are carrying
 * without opening anything. They are blockier than the pickups because at 20px on a
 * moving character, silhouette is all that survives.
 *
 * GDD 7.5 asks for a distinct silhouette per weapon, so each one owns a different
 * *shape language*: the Keyboard is the widest flat slab, the Big Laser the most
 * extreme aspect ratio, the Desk Fan the only circle, the Copier the largest box,
 * the Rubber Stamp the only mushroom profile. Grayscale-legible by construction.
 */

const SCALE = 2;

const pickup = (slug, silhouette, frames) => ({
  id: `weapon_${slug}`,
  anchor: [0.5, 0.75],
  scale: SCALE,
  silhouette,
  frames: [frames],
});

const held = (slug, frames) => ({
  id: `weapon_${slug}_held`,
  anchor: [0.5, 0.5],
  scale: SCALE,
  silhouette: `Held form of ${slug.replace(/_/g, ' ')}.`,
  frames: [frames],
});

const weapons = [
  // WPN-001 Keyboard — the baseline. Widest, flattest thing in the roster.
  pickup('keyboard', 'Widest and flattest silhouette; a low horizontal slab of keys.', [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kHHHHHHHHHHHHk.',
    '.kHwwHwwHwwHwHk.',
    '.kHHHHHHHHHHHHk.',
    '.kHwwHwwHwwwwHk.',
    '.kHHHHHHHHHHHHk.',
    '.kHwHwwwwwwHwHk.',
    '.kHHHHHHHHHHHHk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ]),
  held('keyboard', [
    '..........',
    '..........',
    '.kkkkkkkk.',
    '.kHwHwHwk.',
    '.kHHHHHHk.',
    '.kHwHwwHk.',
    '.kkkkkkkk.',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-002 Mouse — small rounded body plus a trailing cord. The cord is the tell.
  pickup('mouse', 'Small rounded body with a long trailing cord; the only corded blob.', [
    '................',
    '................',
    '.....kkkk.......',
    '....kHHHHk......',
    '...kHwHwHHk.....',
    '...kHHHHHHk.....',
    '...kHHHHHHk.....',
    '...kHHHHHHk.....',
    '....kHHHHk......',
    '.....kkkk.......',
    '.......k........',
    '........k.......',
    '.......k........',
    '........kk......',
    '................',
    '................',
  ]),
  held('mouse', [
    '..........',
    '...kkkk...',
    '..kHwHHk..',
    '..kHHHHk..',
    '..kHHHHk..',
    '...kkkk...',
    '.....k....',
    '......kk..',
    '..........',
    '..........',
  ]),

  // WPN-003 Big Laser Pointer — the most extreme aspect ratio, with a hot lens.
  pickup('big_laser_pointer', 'Long thin cylinder with a hot lens; extreme aspect ratio.', [
    '................',
    '................',
    '................',
    '.....kkkkkkkkkk.',
    '....kRRkGGGGGGk.',
    '...kRRRkGgggggk.',
    '....kRRkGGGGGGk.',
    '.....kkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('big_laser_pointer', [
    '..........',
    '..........',
    '.kkkkkkkk.',
    'kRRkGGGGk.',
    '.kkkkkkkk.',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-004 Stapler — the only sloped top; reads as a hinged jaw.
  pickup('stapler', 'Angular wedge with a sloped top; reads as a hinged jaw.', [
    '................',
    '................',
    '................',
    '.........kkkk...',
    '......kkkGGGGk..',
    '...kkkGGGGGGGk..',
    '..kGGGGGGGGGGk..',
    '..kGgggggggggk..',
    '..kkkkkkkkkkkk..',
    '...kHHHHHHHHk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('stapler', [
    '..........',
    '..........',
    '....kkkk..',
    '..kkGGGGk.',
    '.kGGGGGGk.',
    '.kkkkkkkk.',
    '..kHHHHk..',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-005 Hole Punch — bottom-weighted, with a raised lever above the base.
  pickup('hole_punch', 'Squat heavy base under a raised lever; strongly bottom-weighted.', [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kGGGGGGk....',
    '.....kkkkkk.....',
    '.......kk.......',
    '.......kk.......',
    '..kkkkkkkkkkk...',
    '..kGGGGGGGGGk...',
    '..kGwwGwwGwwk...',
    '..kGGGGGGGGGk...',
    '..kkkkkkkkkkk...',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('hole_punch', [
    '..........',
    '...kkkk...',
    '...kGGk...',
    '....kk....',
    '.kkkkkkkk.',
    '.kGwGwGGk.',
    '.kkkkkkkk.',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-006 Marker — held on a diagonal so it can never be read as the laser.
  pickup('marker', 'Slim body on a diagonal with a darker cap; the only tilted weapon.', [
    '................',
    '................',
    '............kk..',
    '...........kEEk.',
    '..........kEEk..',
    '.........kmmk...',
    '........kmmk....',
    '.......kmmk.....',
    '......kmmk......',
    '.....kmmk.......',
    '....kkkk........',
    '...kkk..........',
    '..kk............',
    '................',
    '................',
    '................',
  ]),
  held('marker', [
    '..........',
    '......kk..',
    '.....kEk..',
    '....kmk...',
    '...kmk....',
    '..kmk.....',
    '..kk......',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-007 Rubber Stamp — the only mushroom profile in the roster.
  pickup('rubber_stamp', 'Mushroom profile: a narrow handle over a wide flat pad.', [
    '................',
    '................',
    '......kkkk......',
    '.....kNNNNk.....',
    '.....kNNNNk.....',
    '......kNNk......',
    '......kNNk......',
    '....kkkkkkkk....',
    '...kGGGGGGGGk...',
    '...kkkkkkkkkk...',
    '..kRRRRRRRRRRk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('rubber_stamp', [
    '..........',
    '...kkkk...',
    '...kNNk...',
    '...kNNk...',
    '..kkkkkk..',
    '.kGGGGGGk.',
    '.kRRRRRRk.',
    '.kkkkkkkk.',
    '..........',
    '..........',
  ]),

  // WPN-008 Paper Shredder — tall box with a dark mouth and strips falling out.
  pickup('paper_shredder', 'Tall box with a dark mouth slot and loose strips beneath.', [
    '................',
    '..kkkkkkkkkkkk..',
    '..kGGGGGGGGGGk..',
    '..kkkkkkkkkkkk..',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '..kGGGGGGGGGGk..',
    '..kGGGGGGGGGGk..',
    '..kkkkkkkkkkkk..',
    '...w.w..w..w....',
    '...w..w..w.w....',
    '....w.w...w.....',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('paper_shredder', [
    '..........',
    '.kkkkkkkk.',
    '.kGGGGGGk.',
    '.kKKKKKKk.',
    '.kGGGGGGk.',
    '.kkkkkkkk.',
    '..w.w.w...',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-009 Presentation Remote — the only tall narrow slab, with lit buttons.
  pickup('presentation_remote', 'Tall narrow slab with two lit buttons; palm-sized.', [
    '................',
    '................',
    '.....kkkkkk.....',
    '.....kKKKKk.....',
    '.....kKEEKk.....',
    '.....kKKKKk.....',
    '.....kKRRKk.....',
    '.....kKKKKk.....',
    '.....kKKKKk.....',
    '.....kKwwKk.....',
    '.....kKKKKk.....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('presentation_remote', [
    '..........',
    '...kkkk...',
    '...kKKk...',
    '...kEEk...',
    '...kKKk...',
    '...kRRk...',
    '...kKKk...',
    '...kkkk...',
    '..........',
    '..........',
  ]),

  // WPN-010 Desk Phone — the only two-part silhouette joined by a visible cord.
  pickup('desk_phone', 'Handset above a wide base, joined by a visible cord; two-part.', [
    '................',
    '..kkk......kkk..',
    '.kKKKkkkkkkKKKk.',
    '.kKKKKKKKKKKKKk.',
    '..kkkkkkkkkkkk..',
    '.....k..k.......',
    '......kk........',
    '.....k..k.......',
    '..kkkkkkkkkkkk..',
    '..kKKKKKKKKKKk..',
    '..kKwwKwwKwwKk..',
    '..kKKKKKKKKKKk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ]),
  held('desk_phone', [
    '..........',
    '.kk....kk.',
    'kKKkkkkKKk',
    'kKKKKKKKKk',
    '.kkkkkkkk.',
    '....kk....',
    '..kkkkkk..',
    '..kKKKKk..',
    '..kkkkkk..',
    '..........',
  ]),

  // WPN-011 Label Maker — chunky body, lit screen, and a tape tongue below.
  pickup('label_maker', 'Chunky body with a lit screen and a tape tongue hanging below.', [
    '................',
    '................',
    '...kkkkkkkkk....',
    '...kGGGGGGGk....',
    '...kGCCCCCGk....',
    '...kGGGGGGGk....',
    '...kGwGwGwGk....',
    '...kGGGGGGGk....',
    '...kGwGwGwGk....',
    '...kkkkkkkkk....',
    '.....kwwwk......',
    '......kwk.......',
    '................',
    '................',
    '................',
    '................',
  ]),
  held('label_maker', [
    '..........',
    '..kkkkkk..',
    '..kGGGGk..',
    '..kGCCGk..',
    '..kGwGGk..',
    '..kkkkkk..',
    '...kwwk...',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-012 Copier — the largest, boxiest silhouette, with a lid seam and feet.
  pickup('copier', 'Largest and boxiest silhouette; a wide machine with a lid seam.', [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kHHHHHHHHHHHHk.',
    '.kkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGk.',
    '.kGCCCCCCCCCCGk.',
    '.kGGGGGGGGGGGGk.',
    '.kGGkkkkkkkkGGk.',
    '.kGGkwwwwwwkGGk.',
    '.kGGkkkkkkkkGGk.',
    '.kGGGGGGGGGGGGk.',
    '.kkkkkkkkkkkkkk.',
    '..kk........kk..',
    '................',
    '................',
    '................',
  ]),
  held('copier', [
    '.kkkkkkkk.',
    '.kHHHHHHk.',
    '.kkkkkkkk.',
    '.kGCCCCGk.',
    '.kGkwwkGk.',
    '.kGGGGGGk.',
    '.kkkkkkkk.',
    '..........',
    '..........',
    '..........',
  ]),

  // WPN-013 Desk Fan — the only circular silhouette in the roster.
  pickup('desk_fan', 'The only round silhouette: a caged circle on a small stand.', [
    '................',
    '.....kkkkkk.....',
    '...kkHHHHHHkk...',
    '..kHHkCCCCkHHk..',
    '..kHCCkCCkCCHk..',
    '.kHHCCCkkCCCHHk.',
    '.kHHCCkkkkCCHHk.',
    '.kHHCCCkkCCCHHk.',
    '..kHCCkCCkCCHk..',
    '..kHHkCCCCkHHk..',
    '...kkHHHHHHkk...',
    '.....kkkkkk.....',
    '.......kk.......',
    '....kkkkkkkk....',
    '................',
    '................',
  ]),
  held('desk_fan', [
    '..........',
    '..kkkkkk..',
    '.kHHCCHHk.',
    '.kHCkkCHk.',
    '.kHCkkCHk.',
    '.kHHCCHHk.',
    '..kkkkkk..',
    '....kk....',
    '..kkkkkk..',
    '..........',
  ]),

  // WPN-014 Projector — wide low box dominated by one large forward lens.
  pickup('projector', 'Wide low box dominated by one large forward lens.', [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kHHHHHHHHHHk..',
    '..kHGGGGGGGGHk..',
    '.kkHGkCCCCkGHkk.',
    '.kCkHGkCCkGHkCk.',
    '.kCkHGGkkGGHkCk.',
    '.kkHGGGGGGGGHkk.',
    '..kHGwGwGwGGHk..',
    '..kHHHHHHHHHHk..',
    '..kkkkkkkkkkkk..',
    '...kk......kk...',
    '................',
    '................',
    '................',
  ]),
  held('projector', [
    '..........',
    '.kkkkkkkk.',
    '.kHHHHHHk.',
    'kHGkCCkGHk',
    'kHGGkkGGHk',
    '.kHwGwGHk.',
    '.kkkkkkkk.',
    '..........',
    '..........',
    '..........',
  ]),

  // -------------------------------------------------------------------------
  // Projectiles.
  //
  // The renderer applies the FRIENDLY or HOSTILE outline at draw time rather than
  // baking it in, so one sprite serves both allegiances if a shot is ever reflected
  // (CARD-014 Return to Sender) — and the outline stays the single signal for who
  // owns a projectile, which is what GDD 18.5 and R-ART-003 require.
  // -------------------------------------------------------------------------
  {
    id: 'prj_keycap',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Small square keycap with a lighter face.',
    frames: [[
      '......',
      '.kkkk.',
      'kHwwHk',
      'kHwwHk',
      '.kkkk.',
      '......',
    ]],
  },
  {
    id: 'prj_staple',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Bent metal staple; a squat U.',
    frames: [[
      '......',
      '......',
      'kHkkHk',
      'kHHHHk',
      '.kkkk.',
      '......',
    ]],
  },
  {
    id: 'prj_paper_disc',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Round punched paper disc.',
    frames: [[
      '......',
      '.kkkk.',
      'kwwwwk',
      'kwwwwk',
      '.kkkk.',
      '......',
    ]],
  },
  {
    id: 'prj_ink_stroke',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Diagonal wet ink stroke, longer than it is wide.',
    frames: [[
      '.....k',
      '....km',
      '...kmm',
      '..kmm.',
      '.kmm..',
      'kk....',
    ]],
  },
  {
    id: 'prj_paper_sheet',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Broad flat sheet; the widest projectile.',
    frames: [[
      'kkkkkkkk',
      'kwwwwwwk',
      'kwwwwwwk',
      'kkkkkkkk',
    ]],
  },
  {
    id: 'prj_paper_strip',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Thin shredded strip; the smallest projectile.',
    frames: [[
      '.kk.',
      'kwwk',
      'kwwk',
      '.kk.',
    ]],
  },
  {
    id: 'prj_click_pulse',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Hollow ring pulse; unmistakably not a solid object.',
    frames: [[
      '.kkkk.',
      'kCCCCk',
      'kC..Ck',
      'kC..Ck',
      'kCCCCk',
      '.kkkk.',
    ]],
  },
  {
    id: 'prj_receiver',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Phone receiver on a cord; an asymmetric dumbbell.',
    frames: [[
      'kkk..kkk',
      'kKKkkKKk',
      'kKKKKKKk',
      '.kkkkkk.',
    ]],
  },
  {
    id: 'prj_label',
    anchor: [0.5, 0.5],
    scale: SCALE,
    silhouette: 'Sticky label rectangle with a printed line.',
    frames: [[
      'kkkkkk',
      'kwwwwk',
      'kwkkwk',
      'kwwwwk',
      'kkkkkk',
    ]],
  },
];

export default weapons;
